### ISSUE TITLE
Not easy to understand how to configure the feature extraction

### ISSUE THREAD

**Issue by cprando** [veraPDF/veraPDF-library#1001]
## Dev Effort
1D

## Description
It is not straightforward to understand that to configure which features you want to extract you have to select the Feature Config option from the File menu item.
It is advisable to help the user in understanding how to use this functionality.

**Comment by carlwilson** [comment]
There is some documentation here: https://docs.verapdf.org/cli/config/#features.xml This PR is stale and unclear now so closing.
