### ISSUE TITLE
Difference between xml and mrr output?

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-library#1003]
## Dev Effort
1D

## Description
Applies to VeraPDF 0.26.16

The `-format` switch of the CLI tool has 2 values (xml and mrr) that both write xml output, although the output is somewhat different in both cases. I couldn't find any documentation on the reason for having 2 different XML formats, and I found this a bit confusing.  My suggestion would be to either get rid of one of the XML formats, or otherwise document the differences between them.

**Comment by bdoubrov** [comment]
The latest dev version uses `xml` report format as a synonym of `mrr`, and what was previously called `xml` format is renamed to `raw`. We still need to provide the documentation on the difference between these two.

**Comment by archive-uk** [comment]
We would like to ask in this context, which of these two outputs should we properly use for further machine processing ("raw" or "xml")?

For which of these two outputs can we expect less variability between VeraPDF versions ?

**Comment by bdoubrov** [comment]
`xml` is certainly the main one and is the one recommended for future use. 

`raw` format is aimed for custom checks processing, when the errors need to be handled immediately when they are discovered not waiting till the end of the validation and the proper `xml` validation report.

Both formats are stable. they may have some additional data in the future, but we always maintain backwards compatibility.

**Comment by bdoubrov** [comment]
Documented the difference between `mrr` and `xml` report formats and added a note that `mrr` format is deprecated: https://docs.verapdf.org/cli/validation/#defining-validation-report
