### ISSUE TITLE
extended execution?

### ISSUE THREAD

**Issue by ousia** [veraPDF/veraPDF-library#1006]
## Dev Effort
3D

## Description
I started using your parse to validate PDF/A-3a documents that I need for work. Congratulations and many thanks for the excellent work (I forgot this in my previous reported issue).

There are scenarios where you have to validate the same (recreated) document again and again to see what went wrong.

In that case, I think it would be handy to extend execution.

I mean having a _Report action_ drop-down menu with the following options:

* None
* Save XML
* View XML
* Save HTML
* View HTML

And also a check field that enables reporting only if validation fails.

These fields may be placed below _Report type_ and _Fix metadata_.

So, when the user clicks on the _Execute_ button, this would trigger saving or displaying the report (only when validation fails [when validation is performed], or in any case).

Both values for _Report action_ and _Only if validation fails_ should be included in the _Settings_ dialog.

Could you improve it?

Many thanks for your help.

**Comment by bdoubrov** [comment]
After several discussions we are not convinced that this would be an improvement for all users. If you want to create an automated report, it would be better to look at the CLI. We close this issue for now.
