### ISSUE TITLE
If header version is malformed it is only logged but not reported back.

### ISSUE THREAD

**Issue by ravn** [veraPDF/veraPDF-library#1008]
While writing tests for file descriptor leaks I noticed that a stacktrace was written to the log.

The code in PDFParser.java is

```
        float headerVersion = 1.4f;
        try {
            String[] headerParts = header.split("-");
            if (headerParts.length == 2) {
                headerVersion = Float.parseFloat(headerParts[1]);
            }
        } catch (NumberFormatException e) {
            LOGGER.log(Level.WARNING, "Can't parse the header version.", e);
        }

        result.setVersion(headerVersion);
        checkComment(result);
```

and is triggered by one of the files in the corpus (most likely veraPDF-corpus/PDF_A-1b/6.1 File structure/6.1.2 File header/veraPDF test suite 6-1-2-t01-fail-b.pdf).  As I read the code, this condition is only logged and then silently defaulted to 1.4, so this does not show in the XML reported to the user.

**Comment by bdoubrov** [comment]
Duplicate of #926
