### ISSUE TITLE
Glyph widths (1B 6.3.6)

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#1009]
6.3.6 of ISO 19005-1:2005 (with TC2) reads:
"For every font embedded in a conforming file and used for rendering, the glyph width information in the font dictionary and in the embedded font program shall be consistent."

It does **not** specify that this applies applies only to actually used glyphs. Apparently, veraPDF 1.4.7 compares glyph widths only for glyphs that are rendered.

This document references U+0020 (glyph 3) and has an incorrect width for that glyph; veraPDF reports violation of 6.3.6:
[Widths-1.pdf](https://github.com/veraPDF/veraPDF-parser/files/1044014/Widths-1.pdf)

This document does not reference U+0020 (glyph 3) and has incorrect width for that glyph; veraPDF does not report violation of 6.3.6:
[Widths-2.pdf](https://github.com/veraPDF/veraPDF-parser/files/1044017/Widths-2.pdf)

(Both documents are derived from "veraPDF-corpus/PDF_A-1b/6.1 File structure/6.1.5 Document information dictionary/veraPDF test suite 6-1-5-t02-pass-d.pdf".)

**Comment by bdoubrov** [comment]
Thanks for noticing the incorrect wording in A.3. But I think the meaning of this clause is clear and does not cause any ambiguities. I'll bring this to the attention to the TWG anyway.
