### ISSUE TITLE
FontMatrix of CFF fonts

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#1010]
## Dev Effort
5D

## Description
There is some confusion about whether a CFF font's FontMatrix shall be applied to the glyph width in CharStrings.  (The CFF specification is remarkably silent on that topic.) FontMatrix is pretty much useless if it doesn't apply to the glyph width. For instance, FreeType does apply FontMatrix to the glyph widths from CharStrings. So does Adobe Acrobat when embedding a font, see here:
[FontMatrix-1.pdf](https://github.com/veraPDF/veraPDF-parser/files/896248/FontMatrix-1.pdf)
The SourceSansProLightIt font has been patched to have a non-standard FontMatrix (0.002 0 0 0.001 0 0)
before being installed in Windows and embedded into the document. As you can see, Adobe Acrobat uses the glyph width from the CharStrings, multiplied by the first component of the FontMatrix. It does not use the hmtx table (which still contains the original, unscaled widths). For instance, the Widths entry for 'A' (65) is 976, but the hmtx table and the unscaled width from the CharString is 488. You can also see that the widths actually used for spacing the glyphs are those from the CharStrings, scaled by FontMatrix.

There are (unpatched) fonts with a non-standard FontMatrix where the hmtx table contains the unscaled glyph widths from the CharStrings (ie, they are not multipled by the FontMatrix). Here are two sample PDF documents using such a font (wrapped in OTF and raw):
[FontMatrix-otf.pdf](https://github.com/veraPDF/veraPDF-parser/files/896278/FontMatrix-otf.pdf)
[FontMatrix-raw.pdf](https://github.com/veraPDF/veraPDF-parser/files/896279/FontMatrix-raw.pdf)

VeraPDF apparently compares the W/Widths table either to hmtx (for OTF) or the unscaled glyph widths from the CharStrings (for OTF and for raw CFF), which contradicts the behavior of Adobe Acrobat. I think VeraPDF should compare both to hmtx (if present) and the glyph widths from the CharStrings (if present), scaled by the one FontMatrix or (for fonts with CIDFont operators) the potentially two FontMatrixes.

Note that older versions of Adobe Acrobat (e.g. version 9) do not apply FontMatrix to the glyph width from CharStrings, resulting in incorrect rendering of this document:
[felltypes-test.pdf](https://github.com/veraPDF/veraPDF-parser/files/896326/felltypes-test.pdf)
This is fixed in Adobe Acrobat XI.

**Comment by carlwilson** [comment]
@bdoubrov could you please provide a status update please

**Comment by bdoubrov** [comment]
This one is still open. Please move it to the next release
