### ISSUE TITLE
Clause: 6.3.8, ToUnicode is not checked with Type0

### ISSUE THREAD

**Issue by foxaxel** [veraPDF/veraPDF-library#1011]
## Dev Effort
1D

## Description
Similar to #179, when validating PDF/A-1a files having text with characters outside the ASCII-range the validation rule for clause: 6.3.8 reports a failure regarding the Unicode-mapping.
In this case, the attached file uses a Type0 font having a valid ToUnicode stream defining the Unicode mapping of the characters. However the characters of the Type0 font result in a validation failure.

 Can you confirm this issue?
Thanks
Axel
[type0_tounicode.pdf](https://github.com/veraPDF/veraPDF-validation-profiles/files/1796722/type0_tounicode.pdf)

**Comment by a20god** [comment]
No, the ToUnicode stream is not valid (the beginbfrange operator uses an invalid range).

**Comment by bdoubrov** [comment]
Indeed, the ToUnicode map uses the construction 
```
1 beginbfrange
<0000> <FFFF> <0000>
endbfrange
 ```

This violates the ISO 32000-1, which requires that any bfrange has at most 255 characters. This could be fixed by changing the above cmap code to:
```
256 beginbfrange
<0000> <00FF> <0000>
<0100> <01FF> <0100>
...
<FF00> <FFFF> <FF00>
endbfrange
 ```

**Comment by foxaxel** [comment]
Meanwhile we also found that bfrange is limited to a range that does not exceed the last byte.
We will fix our code.

Thank you,

Axel

Axel Rehse
Software Developer
Enterprise Automation

Foxit Europe GmbH | Neue Kantstraße 14 | 14057 Berlin | Germany
Tel: +49 30 39 40 50 0 | Fax: +49 30 39 40 50 99
Geschäftsführer: Carsten Heiermann | Amtsgericht Berlin Charlottenburg HRB 180235 B
a_rehse@foxitsoftware.com<mailto:a_rehse@foxitsoftware.com> | www.foxitsoftware.com<http://www.foxitsoftware.com/>

[https://www.foxitsoftware.com/resource/images/email-signatures/email-signatures-logo.gif]






This email may contain information which is privileged, confidential, legally privileged, and/or exempt from disclosure under applicable law. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, or use of the information contained herein (including any reliance thereon) is strictly prohibited. It is also the sole responsibility of the recipient to ensure that the email is virus free and no responsibility is accepted by Foxit Corporation, as applicable, for any loss or damage arising in any way from using this email. If you received this email in error, please immediately contact the sender and destroy the material in its entirety.




Von: Boris Doubrov <notifications@github.com>
Gesendet: Mittwoch, 3. April 2019 10:51
An: veraPDF/veraPDF-library <veraPDF-library@noreply.github.com>
Cc: Axel Rehse <A_Rehse@foxitsoftware.com>; Author <author@noreply.github.com>
Betreff: Re: [veraPDF/veraPDF-library] Clause: 6.3.8, ToUnicode is not checked with Type0 (#1011)


Indeed, the ToUnicode map uses the construction

1 beginbfrange

<0000> <FFFF> <0000>

endbfrange

This violates the ISO 32000-1, which requires that any bfrange has at most 255 characters. This could be fixed by changing the above cmap code to:

256 beginbfrange

<0000> <00FF> <0000>

<0100> <01FF> <0100>

...

<FF00> <FFFF> <FF00>

endbfrange
