### ISSUE TITLE
error pointing to a non-existing rule

### ISSUE THREAD

**Issue by ousia** [veraPDF/veraPDF-library#1013]
[Rule 6.8-4](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Parts-2-and-3-rules#rule-68-4) doesn’t exist.

But I got a report from veraPDF-1.9.84 that claims that the PDF document violates it:

> The additional information provided for associated files as well as the usage requirements for associated files indicate the relationship between the embedded file and the PDF document or the part of the PDF document with which it is associated.

What am I missing here?

**Comment by bdoubrov** [comment]
Fixed the link in the wiki
