### ISSUE TITLE
StaticResources and two parsers

### ISSUE THREAD

**Issue by beat2** [veraPDF/veraPDF-library#1015]
Currently two Parsers share the same cache (StaticResources). So it is only possible for serial processing, one must close the first Parser before attempting to parse the second, otherwise the cache is shared and problems may arise. Can this be changed to a cache per parser?

Serial processing works, but parallel would be better.

**Comment by bdoubrov** [comment]
veraPDF supports now parallel processing of different documents in separate threads, but it is not thread-safe when it comes to a single document. We'll provide more detailed documentation this.

**Comment by carlwilson** [comment]
We have no intention of implementing parallel processing of single documents would be difficult and complex.
