### ISSUE TITLE
PDFA compliance issue reporting to VeraPDF - Rule 6.2.2-1

### ISSUE THREAD

**Issue by ramanareddy16** [veraPDF/veraPDF-library#1018]
•	Background:
We are using VeraPDF 1.12.1 to verify if the PDF files, we produce in our application (with PDF spec 1.4 version) are PDF/A 2B compliant as per PDF-A/2 spec (ISO 19005-2:2011)

•	Problem Statement:
o	As part of the verification, the below mentioned error(in the additional details sectio)  is reported in one of the PDF files , related to Rule 6.2.2-1  Content streams shall not contain any operators not defined in ISO 32000-1 even if such operators are bracketed by the BX/EX compatibility operators.

When we analyzed the issue, we couldn’t find any operators that are NOT defined in the ISO 32000-1, but still VeraPDF reports this issue (related to the presence of /F operator inside a stream object). Also to mention, this compliance issue is not getting reported by the earlier version of VeraPDF 1.8.4 and also by Acrobat Pro DC.

•	What help/information we need from you:
Based on our analysis, we think that VeraPDF 1.12.1 is incorrectly reporting this issue. Can you help to investigate this and let us know the possible cause for the issue.
Let us know if you need any further information.

•	Additional Details:
 Rule | Status
Specification: ISO 19005-2:2011, Clause: 6.2.2, Test number: 1 |  
Content streams shall not contain any operators not defined in ISO 32000-1 even if such operators are bracketed by the BX/EX compatibility operators. | Failed
1 occurrences | Hide
Op_Undefined |  
false |  
root/document[0]/pages[0](14 0 obj PDPage)/contentStream[0](48 0 obj PDContentStream)/operators[93]

For your reference, find below the list of operators in the PDF content stream where the issue is reported.
Operator parse..  BI
Operator parse..  BT
Operator parse..  c
Operator parse..  cm
Operator parse..  Do
Operator parse..  EI
Operator parse..  ET
Operator parse..  f
Operator parse..  g
Operator parse..  G
Operator parse..  gs
Operator parse..  h
Operator parse..  ID
Operator parse..  k
Operator parse..  K
Operator parse..  l
Operator parse..  m
Operator parse..  n
Operator parse..  q
Operator parse..  Q
Operator parse..  re
Operator parse..  Td
Operator parse..  Tf
Operator parse..  Tj
Operator parse..  TJ
Operator parse..  Tm
Operator parse..  v
Operator parse..  W
Operator parse..  W*
Operator parse..  y

**Comment by ramanareddy16** [comment]
Could you please help me on this issue

**Comment by THausherr** [comment]
Please attach your file

**Comment by bdoubrov** [comment]
Closing this issue as the test PDF was not provided and the issue can not be reproduced without it.
