### ISSUE TITLE
Validating digitally signed PDF/A-2/3 does take a very long time

### ISSUE THREAD

**Issue by beat2** [veraPDF/veraPDF-library#1026]
A digitally signed PDF/A-2 or PDF/A-3 takes a very long time to validate. The bigger the file, the longer it takes (linear).

The problem is the scanning of the file until an "%%EOF" is found, e.g. here:
https://github.com/veraPDF/veraPDF-parser/blob/integration/src/main/java/org/verapdf/parser/SignatureParser.java#getOffsetOfNextEOF

For a 470 KB file, around 30 seconds are needed (tested with 1.10.x and 1.12, Greenfield parser).

Sample file (470 KB): 
[Big Test File-sig.pdf](https://github.com/veraPDF/veraPDF-library/files/3182358/Big.Test.File-sig.pdf)

**Comment by bdoubrov** [comment]
Thanks for reporting this! We'll try to optimize this part.
