### ISSUE TITLE
rdf:Description without rdf:about attribute

### ISSUE THREAD

**Issue by THausherr** [veraPDF/veraPDF-library#1031]
## Dev Effort
TBC

## Description
Using 1.14.7 RC

The XMP part of the attached PDF has this line:

`<rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/">`

PDF-Tools
https://www.pdf-online.com/osa/validate.aspx
complains:
Anonymous RDF resources (rdf:Description without rdf:about attribute) are not allowed in XMP Metadata.

VeraPDF does not complain about the XMP (there are other errors, that are correctly reported as such)

PDFLib says the XMP is OK
https://www.pdflib.com/pdf-knowledge-base/xmp/free-xmp-validator/

file: [SO56791435-preflight.pdf](https://github.com/veraPDF/veraPDF-library/files/3341825/SO56791435-preflight.pdf)

**Comment by bdoubrov** [comment]
We'll bring this question for discussion at the next meeting of the Validation technical working group. As of now veraPDF indeed is ignoring the missing rdf:about attribute.

**Comment by bdoubrov** [comment]
According to the TWG discussion the missing rdf:about attribute should be treated as if it is present and is equal to the emtry string. This is how it was also worded in the recent version of XMP.
