### ISSUE TITLE
veraPDF does not run on EBCDIC-Platforms like z/OS

### ISSUE THREAD

**Issue by michaelknigge** [veraPDF/veraPDF-library#1032]
We've tried to use veraPDF for PDF/A validation on z/OS - but sadly in vain. This is because veraPDF assumes that it is running on an ASCII based platform and for this reason does not provide a Charset on various byte[] to String and/or String to byte[] transformations.

I did some minor modifications and got it working. I'd like to create a pull request for this if there is any chance it gets integrated.

The only part that needs to be modified is veraPDF-parser. 

Could you please assist me?

1. for what branch I should create the pull request (I guess "integration")?
2. Any chance it gets integrated?
3. if yes, can you give me a timeframe when it might be integrated and when a new version (with the fix) gets released (we need it at a customer site soon)?

Thanks & bye,
Michael

**Comment by carlwilson** [comment]
Hi @michaelknigge thanks for your input, I'll answer your questions as a list:

1. Yes the integration branch is the one to PR against please.
2. I'll review the PR and comment but in principle it sounds a useful addition, particularly if we're making encoding assumptions.
3. If yes then in the 1.16 release in early 2020.

If you set up the PR and ping me I'll take a look within a couple of days.

Thanks,
Carl

**Comment by michaelknigge** [comment]
I've created a pull request - see https://github.com/veraPDF/veraPDF-parser/pull/377

**Comment by BezrukovM** [comment]
@michaelknigge Thanks for your issue and PR. This fix will also required to make a release hotfix about COSName utf-8 validation, so I added all your changes into the another PR against the release branch. The issue will be closed as soon as PR with fix will be merged.

**Comment by BezrukovM** [comment]
Merged into release and dev.
