### ISSUE TITLE
Custom-XMP fields fail rule 6.7.9 even when defined according to PDF/A Schema

### ISSUE THREAD

**Issue by archivist-liz** [veraPDF/veraPDF-library#1035]
Hi, I've been writing and talking to @carlwilson about this, so he should understand what I'm trying to do if I don't explain it well.

I've been trying to write some tags using a custom schema and embed them into my PDF/A files using ExifTool. In order to do this, I need to first define the schema in ExifTool. I have a sample ExifTool config file posted in this repository: https://github.com/archivist-liz/exifTool-configs 

I have then added the definition of the schema to my XMP (to meet PDF/A compliance for a custom schema), and then added some sample values. To see how, see the command.txt file in the repository above. 

If I only define one "Property" and pass it a value, VeraPDF will still read it as valid. However, as soon as I write a second property and pass it a value as well, VeraPDF says it is noncompliant. I am attaching two sample files that I have edited according to the process above -- one is compliant, one is not. At this point, I am quite sure that the schema is properly defined, so I do not understand why VeraPDF does not consider the file valid. Maybe you can provide insight? Perhaps VeraPDF is not set up to read a custom schema? Below are the details of the rule it doesn't pass
[pdfA_noncompliant_two-custom-XMP.pdf](https://github.com/veraPDF/veraPDF-library/files/3424236/pdfA_noncompliant_two-custom-XMP.pdf)
[pdfA_compliant_one-custom-XMP.pdf](https://github.com/veraPDF/veraPDF-library/files/3424237/pdfA_compliant_one-custom-XMP.pdf)

:

` <details passedRules="102" failedRules="1" passedChecks="1060" failedChecks="1">
          <rule specification="ISO 19005-1:2005" clause="6.7.9" testNumber="2" status="failed" passedChecks="0" failedChecks="1">
            <description>Properties specified in XMP form shall use either the predefined schemas defined in XMP Specification, 
			or extension schemas that comply with XMP Specification</description>
            <object>XMPProperty</object>
            <test>(isPredefinedInXMP2004 == true || isDefinedInCurrentPackage == true) &amp;&amp; isValueTypeCorrect == true</test>
            <check status="failed">
              <context>root/document[0]/metadata[0](28 0 obj PDMetadata)/XMPPackage[0]/Properties[4](http://www.loc.gov/premis/v3 - premis:EventDateTime)</context>
            </check>
          </rule>
        </details>`

**Comment by bdoubrov** [comment]
I checked the custom schema. It all looks good except for two minor issues:

1) The value type for the EventDateTime property is specified as Date, but the given value ``2018:01:17 15:59:11+01:00`` does not comply to the XMP Date format. Changing it to ``2018-01-17T15:59:11+01:00`` fixes the issue and makes the second document also veraPDF compliant. 

For the details on the XMP Date syntax see [XMP Specification Part 1, 8.2.1.2 Date](https://wwwimages2.adobe.com/content/dam/acom/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart1.pdf)

2) XMP Specification also contains the following recommendation on the namespace URI: So, I would also recommend to change your namespace URI to  "http://www.loc.gov/premis/v3/". Not s

**Comment by bdoubrov** [comment]
I also attach the fixed file that passes veraPDF validation
[pdfA_noncompliant_two-custom-XMP-fixed.pdf](https://github.com/veraPDF/veraPDF-library/files/3425881/pdfA_noncompliant_two-custom-XMP-fixed.pdf)

**Comment by archivist-liz** [comment]
Thank you. It still is not working when I run it. I tried calling a different date and changing the date to a text field. Both continued to give me the same result - noncompliant. Did you correct the issue using ExifTool as well? If so, could you share the command you used?

**Comment by bdoubrov** [comment]
Did you check the PDF file I attached? It does pass PDF/A validation in both veraPDF and Adobe Acrobat. The file was manually tweaked in the text editor to fix the above issues.

And I don't use ExifTool. If you were updating PDF metadata using this tool, I suggest you provide the details on how you do this. By checking the documentation of this tool, I guess one wound need to specify the DateFormat option as "%Y-%m-%dT%H:%M:%S" or similar.

**Comment by carlwilson** [comment]
Closing this now @archivist-liz as I'm pretty sure it's all sorted out. Shout if not.
