### ISSUE TITLE
Java 11 - validation issues

### ISSUE THREAD

**Issue by bdoubrov** [veraPDF/veraPDF-library#1036]
We are using veraPdf library, version 1.8.1 and we encountered some issues when upgrading to Java 11 with the PDFAValidator.

The “TWG test suite A001-pdfa1-fail-a.pdf” file (taken from GitHub) used to fail validation, as expected, but after upgrading to Java 11 – It passed.  As well as the other files named “-fail-” with b-e of A001.

When rolling back to Java 8, it did fail validation…

We are using the following code:
```
PDFAParser parser = Foundries.defaultInstance().createParser(new FileInputStream(filePath));
PDFAValidator validator = Foundries.defaultInstance().createValidator(parser.getFlavour(), false);
ValidationResult result = validator.validate(parser);
```
And looping result.getTestAssertions()

We also tested it with newer version of veraPdf – 1.12 but the files still passed.

Can you please advise?

**Comment by BezrukovM** [comment]
On my machine (Arch Linux) with OpenJDK 8, 11, 12 and veraPDF library versions 1.12, 1.13, 1.14 for both GF and PB based validation the file is invalid. Tested with the code provided in the issue.
veraPDF 1.8 doesn't officially support Java 11.

**Comment by rosetta-development** [comment]
The ValidationProfile of "1b" flavour contains no rules, as oppose to when running on Java 8:

`File profileFile = new File(".../PDFA-1B.xml");`
`ValidationProfile validationProfile = Profiles.profileFromXml(new FileInputStream(profileFile));`
`validationProfile.getRules();` returns empty..

What is missing? We added the JAX-B dependencies..

**Comment by BezrukovM** [comment]
@rosetta-development No problems on my setup.
I tested your code with 1B profile from veraPDF-validation-profiles repository and all dependencies from veraPDF-apps repo, openjdk 11 (and 8), system: Arch Linux.
Can you try to use dependencies from veraPDF-apps, or add here your pom file and system setup (jdk version, system), please?
