### ISSUE TITLE
is veraPDF Processor API thread safe

### ISSUE THREAD

**Issue by FabianHamm** [veraPDF/veraPDF-library#1037]
In the release notes i read that verapdf cli application supports multi threading. But what about the veraPDF Processor API? Does it still rely on static "containers" / members or can i startup multiple threads?

**Comment by bdoubrov** [comment]
Starting from version 1.12 veraPDF Processor API doesn't use static containers anymore. It does however use thread local containers for caching some data. This means that one can safely use the the API in multiple parallel threads *assuming that each thread processes a single PDF document at a time*.

**Comment by FabianHamm** [comment]
Thank you very much Boris. I am closing the issue.
