### ISSUE TITLE
veraPDF Installer on Windows doesn't work for unsupervised/auto install

### ISSUE THREAD

**Issue by jackdos** [veraPDF/veraPDF-library#1052]
The verapdf-installer.bat script for the 1.14.8 release of veraPDF does not pass command line parameters through the to the java invocation of the installer jar, meaning that you cannot run a headless install with an auto-install XML configuration.  If you manually edit the script to add "%*" to the end of the java line, the installation works as expected, so the functionality appears to be supported if correctly exposed.

I'm not sure this is the correct project for this issue, but the veraPDF-apps project doesn't have an Issues page accessible to me.

The only batch script I could find in the veraPDF-apps code-base looks quite different from the version in the release, so this may have been fixed in integration already.

**Comment by carlwilson** [comment]
I suspect that you're right and that this is fixed but will test before closing.

**Comment by carlwilson** [comment]
Fixed by PR veraPDF/veraPDF-apps#278 in apps project.
