### ISSUE TITLE
PDFA/3A attachment mime type charset causes 6.8-1 failure

### ISSUE THREAD

**Issue by Amphiboly** [veraPDF/veraPDF-library#1061]
Two identical files except that one specifies  `text/plain;charset=UTF-8` for the attachment mime type and the other specifies only `text/plain`.
The file with the charset specification fails clause 6.8 test 1.
The file without the charset is declared valid.
(3Heights accepts both as valid.)
(ConTeXt LMTX source attached as well)

[68_1_fail.txt](https://github.com/veraPDF/veraPDF-library/files/4199224/68_1_fail.txt)
[68_1_fail.pdf](https://github.com/veraPDF/veraPDF-library/files/4199210/68_1_fail.pdf)
[68_1_pass.pdf](https://github.com/veraPDF/veraPDF-library/files/4199211/68_1_pass.pdf)

**Comment by bdoubrov** [comment]
According to the PDF 1.17 specification, the Subtype of the embedded file shall conform to the MIME **media type names** defined in Internet RFC 2046, Multipurpose Internet Mail Extensions (MIME), Part Two: Media Types (ISO 32000-1, 7.11.3). Media type is limited only to the pair of 'type/subtype' and is different from 'Content-Type', which may indeed contain additional parameters. So, the current implementation of veraPDF does correctly reflect the PDF/A requirements.

**Comment by datalogics-pgallot** [comment]
@bdoubrov Not including the charset for plain-text files is…extremely short-sighted.  

Having the charset be required would make more sense from an archival perspective than requiring it be left off. 

The charset may seem optional if you can assume that it will always be ASCII/Latin-1 based; but that’s not a valid assumption for all plaintext files from all parts of the world.  Determining the correct char-set after you have lost track of what it is supposed to be can be a significant technical challenge.

-Patrick

**Comment by bdoubrov** [comment]
This is how it is worded at the moment in ISO 32000-1, and we are not in the position to change this. However, this question was brought to the attention to the experts participating in the ISO process of PDF standardization, including both future PDF and PDF/A standards.
