### ISSUE TITLE
Validating a PDF/A-2B sample pdf yields different results compared to Acrobat.

### ISSUE THREAD

**Issue by PopaDan3** [veraPDF/veraPDF-library#1064]
Hi

I was using veraPDF to validate some pdf against the PDF/A-2B standard and they all passed. 
But then we got around to checking with Adobe Acrobat DC's preflight and some of them returned the following error: "Object uses resources that are inherited from the page (28 matches on 1 page)"

I have attached a small sample file where this behavior is present. It seems Acrobat has an issue with the Type 3 font in there . To be honest I'm not sure this is a veraPDF issue or Acrobat issue and would appreciate another opinion.

Best regards,
Dan Popa

[test_2b.pdf](https://github.com/veraPDF/veraPDF-library/files/4245189/test_2b.pdf)

**Comment by bdoubrov** [comment]
The document indeed contains a Type3 font, where each glyph is defined using an (inline) image mask. s far as I can see, all these glyphs are self-contained and don't use any external resources. So, I believe veraPDF is correct in this case saying that the document is PDF/A-2b valid.
