### ISSUE TITLE
veraPDF rejects a /Lang entry with Unicode value

### ISSUE THREAD

**Issue by a-hirth** [veraPDF/veraPDF-library#1066]
Hi, 

please have a look at the two attached files. Both should be valid PDF/A-2a documents. Both have a /Lang entry in the /Catalog with the same value: 'EN-CA'. The only difference is that in one case the value is stored in PdfDocEncoding and in the other case its the UTF-16BE Unicode character encoding scheme. Both should be valid, given that the data type for the /Lang entry is specified as 'text string' in ISO 32000-1. However, veraPDF reports an issue with the /Lang entry in the case that is using Unicode. 

Thanks,
Andreas

[minimal_pdfa_unicode_lang.pdf](https://github.com/veraPDF/veraPDF-library/files/4288221/minimal_pdfa_unicode_lang.pdf)
[minimal_pdfa.pdf](https://github.com/veraPDF/veraPDF-library/files/4288222/minimal_pdfa.pdf)

**Comment by bdoubrov** [comment]
Fixed in 1.16.1
