### ISSUE TITLE
PDF Creator 4.0.3

### ISSUE THREAD

**Issue by jbfm21** [veraPDF/veraPDF-library#1071]
Hello, 

When i try to convert some documents to PDF A/2B with PDF Creator version 4.0.3 and validate with veraPDF, this erros are reported by VeraPDF.

[RuleId [specification=ISO 19005-2:2011, clause=6.1.3, testNumber=1] /failed]: The file trailer dictionary shall contain the ID keyword whose value shall be File Identifiers as defined in ISO 32000-1:2008, 14.4 [] 

[RuleId [specification=ISO 19005-2:2011, clause=6.1.9, testNumber=1] /failed]: The object number and generation number shall be separated by a single white-space character. The generation number and obj keyword shall be 

[RuleId [specification=ISO 19005-2:2011, clause=6.6.2.1, testNumber=1] /failed]: The Catalog dictionary of a conforming file shall contain the Metadata key whose value is a metadata stream as defined in ISO 32000-1:2008, 14.3.2. [] 

[RuleId [specification=ISO 19005-2:2011, clause=6.6.4, testNumber=1] /failed]: The PDF/A version and conformance level of a file shall be specified using the PDF/A Identification extension schema. [] 

[RuleId [specification=ISO 19005-2:2011, clause=6.1.7, testNumber=2] /failed]: The stream keyword shall be followed either by a CARRIAGE RETURN (0Dh) and LINE FEED (0Ah) character sequence or by a single LINE FEED (0Ah) 

[RuleId [specification=ISO 19005-2:2011, clause=6.2.11.4, testNumber=1] /failed]: The font programs for all fonts used for rendering within a conforming file shall be embedded within that file, as defined in ISO 32000-1:2008, 9.9. [] 

[RuleId [specification=ISO 19005-2:2011, clause=6.2.11.4, testNumber=4] /failed]: If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream, then it shall identify all CIDs which are present in the font program,

If I use PDFCreator version 2.5, the validation ocurrs without erros. I want to know if someone else is getting this issues with PDF Creator 4.0.3 or if is a bug in veraPDF.

Thanks for all

**Comment by bdoubrov** [comment]
Would you please upload one of the PDF documents you get out of PDFCreator 4.0.3? The list of validation errors is suspiciously long. Maybe you were creating just PDF files, not PDF/A?
