### ISSUE TITLE
OpenTypeFontProgram cannot be cast to TrueTypeFontProgram

### ISSUE THREAD

**Issue by Paddre** [veraPDF/veraPDF-library#1073]
Validation of PDF file [1d2d3468_5333HTML000001.pdf](https://github.com/veraPDF/veraPDF-library/files/4608674/1d2d3468_5333HTML000001.pdf) fails with the following Exception: 

> org.verapdf.pd.font.opentype.OpenTypeFontProgram cannot be cast to org.verapdf.pd.font.truetype.TrueTypeFontProgram
>         at org.verapdf.gf.model.impl.external.GFTrueTypeFontProgram.<init>(GFTrueTypeFontProgram.java:55)
>         at org.verapdf.gf.model.impl.pd.font.GFPDFont.getFontProgram(GFPDFont.java:139)
>         at org.verapdf.gf.model.impl.pd.font.GFPDFont.getLinkedObjects(GFPDFont.java:119)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
>         ... 25 more

The PDF contains only Arial fonts:
![Fonts in PDF](https://user-images.githubusercontent.com/9211173/81545053-a1e94780-9378-11ea-9c20-75e318aec0a6.png)

From my understanding, OpenType is a generalization of TrueType so I would expect that there is an apropriate relation between both types.

**Comment by bdoubrov** [comment]
I can not reproduce this issue on the latest veraPDF release 1.16.1. Looks like the issue was fixed a while ago: https://github.com/veraPDF/veraPDF-validation/pull/284
