### ISSUE TITLE
unwanted error message on the TrueType font not embedded

### ISSUE THREAD

**Issue by bdoubrov** [veraPDF/veraPDF-library#1078]
When validating the attached PDF document, veraPDF 1.16.1 reports two error messages: one on the wrong encdoing for a non-symbolic TrueType font, which is correct, and another on the font program not embedded, which is wrong. The TrueType program is embedded, and it seems that veraPDF has issues parsing this font.

[veraPDF test suite 6.2.11.6-t02-fail-a.pdf](https://github.com/veraPDF/veraPDF-library/files/4676161/veraPDF.test.suite.6.2.11.6-t02-fail-a.pdf)

**Comment by Paddre** [comment]
Seems to be related to another issue I reported lately: https://github.com/veraPDF/veraPDF-library/issues/1073
