### ISSUE TITLE
[LIB] Customize error message of files with exceptions

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/veraPDF-library#1081]
[Header.pdf](https://github.com/veraPDF/veraPDF-library/files/4734674/Header.pdf)
[Trailer.pdf](https://github.com/veraPDF/veraPDF-library/files/4734675/Trailer.pdf)

**Comment by bdoubrov** [comment]
Both XML and HTML reports contain a valid error message:
> Exception: Couldn't parse stream caused by exception: PDFParser::GetXRefSection(...) can not locate xref table
