### ISSUE TITLE
CLI "--format text" option generates only one line of output

### ISSUE THREAD

**Issue by Lucas-C** [veraPDF/veraPDF-library#1086]
Hi

I'm new to this tool, so I may be missing something here :)

I installed veraPDF CLI for Windows:
```
$ verapdf --version
veraPDF 1.16.1
Built: Tue May 12 00:59:00 CEST 2020
```

I then attempted to run it on a PDF I've built: https://chezsoi.org/lucas/blog/images/jdr/RunDieRepeat-scenarios-FR-v1.1.pdf and it generated verbose XML output:

```
$ verapdf "RunDieRepeat-scenarios-FR-v1.1.pdf" | wc -l
970
```

Then I noticed there was a `--format text` option, and tried it:
```
$ verapdf --format text "RunDieRepeat-scenarios-FR-v1.1.pdf"
FAIL C:\...\RunDieRepeat-scenarios-FR-v1.1.pdf
```

Is this expected ?
I hoped for a detailed but readable text output,
one that I could use for example in a CI pipeline.

**Comment by bdoubrov** [comment]
text reports are intended for a quick inspection of the batch collection of files. You can get a bit more of info (the rule id's that fail) if you run
```
$ verapdf --format text -v "RunDieRepeat-scenarios-FR-v1.1.pdf"
```

**Comment by Lucas-C** [comment]
Perfect !
That fits my need, thank you :)
Feel free to close this issue
