### ISSUE TITLE
Validation result for attached file is not correct. H7-Hn are not standard type of ISO 32k-1

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/veraPDF-library#1088]
[example.pdf](https://github.com/veraPDF/veraPDF-library/files/4770612/example.pdf)

1. Inspect attached PDF on PDF/UA-1 profile

**Actual result:** Standard tags defined in ISO 32000-1:2008, 14.8.4, shall not be remapped.
**Expected result:** Only rule 7.1-5 shall be present in validation report

**Comment by bdoubrov** [comment]
I see that this is a PDF 2.0 file using the PDF 2.0 namespace. Formally veraPDF should irnore this new logic when doing PDF/UA-1 validation

**Comment by bdoubrov** [comment]
To fix the issue we need to make sure that:
- we ignore the namespaces in PDF/UA-1 (PDF 1.7) flavor
- we do support them in PDF 2.0 flavor (and the future PDF/UA-2)

Current failed rule 7.1.7 seems to be indeed incorrect.
