### ISSUE TITLE
Installing veraPDF on Windows10

### ISSUE THREAD

**Issue by karinbredenberg** [veraPDF/veraPDF-library#1092]
Under Windows 10, Windows SmartScreen might issue a warning when installing VeraPDF. This warning must be accepted properly to be able to finish the installation of VeraPDF.

**Comment by carlwilson** [comment]
Hi @karinbredenberg we believe that this is a Windows feature, that is it will warn you about running batch files downloaded in zip files. We suspect that there's little we can do to address this issue. That said we'll be looking at the installer shortly and might offer a different option in future. For now we're closing this sorry.
