### ISSUE TITLE
Is there a way to disable certain rules when validating PDF documents?

### ISSUE THREAD

**Issue by bajseps** [veraPDF/veraPDF-library#1104]
Hello everyone!

I am using veraPDF with [this](https://docs.verapdf.org/develop/) implementation. I am using the Greenfield parser, where software decides which PDF/A specification to use. 

When I tested some documents, that Adobe Acrobat Reader DC claims to have been PDF/A compliant, my implementation returned that those documents are not PDF/A valid. Then I used the [processor](https://docs.verapdf.org/develop/processor/), to check which rules are not fulfilled. To my surprise every single document breaks the same rule(6.1.8-1 for PDF/A-1 and Rule 6.1.9-1 for PDF/A-2 and PDF/A-3). 

Here is my question, is there a way to disable some rules when I am using this implementation?

Kind Regards
bajseps

**Comment by bdoubrov** [comment]
Hi bajseps,

In general we try hard to be consistent with the results of all available PDF/A validators. So, if you could submit the files in question, we'd be glad to analyze them further.

Note also that development versions of veraPDF might not be fully stable and are not recommended for production purposes. I would suggest that you retest your documents with the stable version of veraPDF 1.16.1 with the installer available at: https://verapdf.org/software/

You also may use veraPDF GUI (included into the installer) that would allow you analyze the issues with any single file.

**Comment by bajseps** [comment]
Thank you for your reply.

I will post URLs for some pdf documents that I tested, as I am not sure if I am allowed to share them directly.
https://dk.um.si/Dokument.php?id=143487&lang=slv&dn=
https://dk.um.si/Dokument.php?id=143054&lang=slv&dn=
https://dk.um.si/Dokument.php?id=142981&lang=slv&dn=
https://dk.um.si/Dokument.php?id=142797&lang=slv&dn=

Note that I just opened them in Adobe to see if it is compliant like [this](https://imgur.com/fvpOEiz), and I did not use the preflight tool.

**Comment by bdoubrov** [comment]
All these files indeed have an extra space character after the keywords `obj` and `endobj`, which contradicts to the PDF/A requirement: 
> The obj and endobj keywords shall each be followed by an EOL marker. 

And, by the way, Adobe Acrobat Preflight does report this issue as well.
