### ISSUE TITLE
2 validators say PDF is valid; veraPDF thinks it is invalid

### ISSUE THREAD

**Issue by mtlmarko89** [veraPDF/veraPDF-library#1105]
Hello veraPDF developers,

I have an example PDF here: [D200001281.pdf](https://sos-develop.de/Validierungsfehler/D200001281.pdf)

veraPDF claims that said PDF is invalid:
"The Catalog dictionary of a conforming file shall contain the Metadata key whose value is a metadata stream as defined in ISO 32000-1: 2008, 14.3.2."

I asked 2 independent validators, but they say that the PDF is valid and complies with the relevant rules.

That maybe 1 validator does not check for this "error" would be conceivable. But with 2 validators I can hardly imagine that.

This is about invoices and most of our customers will probably validate with veraPDF, so it is very urgent that the problem be found and fixed.

If the error is in the PDF and the other two PDF validators actually miss an error, I would be very grateful for information about what exactly is supposed to be wrong.

Thanks for your help!

Best regards
mtlmarko89

**Comment by mtlmarko89** [comment]
Hello MaximPlusov,

that really seems to be the whole problem. I am just surprised that the other validators do not seem to be case-sensitive.

Are you planning to change this or should I close the issue?

Best regards
mtlmarko89

**Comment by bdoubrov** [comment]
PDF keys are always case sensitive. 

I guess other validators still process the Metadata stream with the absent /Subtype entry.  On the other hand, veraPDF requires the presence of /Subtype entry with value /XML in all Metadata streams. This works as a signature that the contents of the stream is an XMP package (see Table 315 from PDF 1.7 specification). 

In fact, this question has already been discussed and reconfirmed at the Technical Working Group of PDF Association.  So, we are not going to change veraPDF implementation for now.

**Comment by mtlmarko89** [comment]
If no change is made, I would now close this issue. Many thanks for the help.
