### ISSUE TITLE
This PDF/A is not valid but should be 

### ISSUE THREAD

**Issue by svocino** [veraPDF/veraPDF-library#1111]
VERAPDF validator gives message : 

Specification: ISO 19005-1:2005, Clause: 6.3.4, Test number: 1 |
The font programs for all fonts used within a conforming file shall be embedded within that file, as defined in PDF Reference 5.8, except when the fonts are used exclusively with text rendering mode 3

[CourrierTitiliumWebEtFormVPF-with-font_pdfa.pdf](https://github.com/veraPDF/veraPDF-library/files/5293402/CourrierTitiliumWebEtFormVPF-with-font_pdfa.pdf)

Is there a problem with the PDF ot with the validator ?

**Comment by bdoubrov** [comment]
Strictly speaking the embedded TrueType fonts are invalid - their tables 'maxp' and 'post' specify different number of glyphs in the font, which is a violation of the format. But we've added the support for this problem and just log this as a warning.
