### ISSUE TITLE
veraPDF sees undefined operators

### ISSUE THREAD

**Issue by alisdev** [veraPDF/veraPDF-library#1121]
For this document:
 [document.pdf](https://github.com/veraPDF/veraPDF-library/files/5703115/document.pdf)
veraPDF 1.16.1 reports

> Content streams shall not contain any operators not defined in ISO 32000-1 even if such operators are bracketed by the BX/EX compatibility operators.

But when I checked the document using 3-HEIGHTS™ PDF VALIDATOR ONLINE TOOL
https://www.pdf-online.com/osa/validate.aspx
the result was: Document validated successfully.

**Comment by bdoubrov** [comment]
Thanks for submitting this issue. It is related to the incorrect space delimiter processing at the end of inline image data in veraPDF. And this has already been fixed in the latest development  version: https://software.verapdf.org/dev/1.17/verapdf-pdfbox-1.17.40-installer.zip

**Comment by alisdev** [comment]
Thanks for the dev. bundle, it works.
