### ISSUE TITLE
PDF/A-2U Document validation fails although expected to pass

### ISSUE THREAD

**Issue by sashkica** [veraPDF/veraPDF-library#1126]
Hello, I am having a problem with the validation of this sample PDF/A-2U Document ([TestfilePdfA2U.pdf](https://github.com/veraPDF/veraPDF-library/files/5782231/TestfilePdfA2U.pdf)).  I am expecting the document to be valid, but the validator says that the following check fails:

```
Specification: ISO 19005-2:2011, Clause: 6.2.4.2, Test number: 2 |
OOverprint mode (as set by the OPM value in an ExtGState dictionary) shall not be one (1) when an ICCBased CMYK colour space is used for stroke and overprinting for stroke is set to true, or when ICCBased CMYK colour space is used for fill and overprinting for fill is set to true, or both. | Failed
1 occurrences | Hide
PDICCBasedCMYK |  
overprintFlag == false \|\| OPM == 0 |  
root/document[0]/pages[2](3 0 obj PDPage)/contentStream[0](6 0 obj PDContentStream)/operators[187]/fillCS[0](51 0 obj PDICCBasedCMYK 1 true)

Specification: ISO 19005-2:2011, Clause: 6.2.4.2, Test number: 2 |
OOverprint mode (as set by the OPM value in an ExtGState dictionary) shall not be one (1) when an ICCBased CMYK colour space is used for stroke and overprinting for stroke is set to true, or when ICCBased CMYK colour space is used for fill and overprinting for fill is set to true, or both. | Failed
1 occurrences | Hide
PDICCBasedCMYK |  
overprintFlag == false \|\| OPM == 0 |  
root/document[0]/pages[2](3 0 obj PDPage)/contentStream[0](6 0 obj PDContentStream)/operators[187]/fillCS[0](51 0 obj PDICCBasedCMYK 1 true)

```
I have tried validating it with other online validators and the result is "valid".
The project I am working on has test cases failing because of this. The project uses org.verapdf with version 1.16.1, but same issue appears when using older versions of the library and also using the online validator https://demo.verapdf.org/.

I would be happy to get some Feedback on this problem.  
Thanks 
Sashka

**Comment by bdoubrov** [comment]
Hi Sashka,

I do confirm that at least one of the form XObjects (26 0 obj) in the document indeed uses the CMYK-based ICC color space (via the DefaultCMYK color space set in the resource dictionary) with both overprint mode enabled (OPM=1) and overprint flags (op/OP) set to true. So, I believe veraPDF is fully correct in this case.

In fact, the same error is reported by Preflight tool in Acrobat.

**Comment by sashkica** [comment]
Thank you very much for the Feedback
