### ISSUE TITLE
Error building from source: missing class java/util/jar/Pack200

### ISSUE THREAD

**Issue by alexreg** [veraPDF/veraPDF-library#1128]
Apologies for posting about veraPDF-apps here, but that project doesn't have an issues page, and I see no other obvious way to contact you.

I am building the source of veraPDF-apps per the [README instructions](https://github.com/veraPDF/veraPDF-apps/blob/integration/README.md#use-maven-to-compile-the-source), but it seems that you use this builds dependency "izpack", which is itself using the long-obsolete and even-longer-deprecated `java/util/jar/Pack200` class (removed in Java 14 I believe). Naturally, it doesn't find the class on my Java 18 system.

Build command:

```sh
mvn clean install -P clone-test-resources
```

Most relevant lines from log ([full log](https://gist.github.com/5716af2533c3b622b3726d34d7269b48)):

```
[ERROR] Failed to execute goal org.codehaus.izpack:izpack-maven-plugin:5.0.10:izpack (default) on project installer: Execution default of goal org.codehaus.izpack:izpack-maven-plugin:5.0.10:izpack failed: A required class was missing while executing org.codehaus.izpack:izpack-maven-plugin:5.0.10:izpack: java/util/jar/Pack200
```

To be clear, I am using the latest release source (https://github.com/veraPDF/veraPDF-apps/archive/v2.0.68.tar.gz).

**Comment by bdoubrov** [comment]
Fixed in PR: https://github.com/veraPDF/veraPDF-apps/pull/286

**Comment by alexreg** [comment]
Thanks!
