### ISSUE TITLE
veraPDF distributed on Flathub.org

### ISSUE THREAD

**Issue by nbenitez** [veraPDF/veraPDF-library#1132]
Hi folks,

[Flathub](https://flathub.org) is a build and distribution platform for Linux apps, packaged in
a way that makes them portable and running on all major distributions.
Anyone can submit an app (we're not doing it for profit), but one of the
requirements is to reach out to the application's authors if they would
like to help with maintenance and thus making that distribution channel
considered official.

[I've just submitted veraPDF for review](https://github.com/flathub/flathub/pull/2073) to be published in https://flathub.org.
The usual maintenance for new releases is just changing version string and
the file checksum. The rest is done by flathub's build infraestructure. 

It's understandable if you can't commit to maintaining it, I can do the new
version updates as I'm the original packager and interested in having
veraPDF on flathub, but we'd like to know **if you are not against 
distributing it on Flathub in general**.

Thank you,
Nelson

**Comment by bdoubrov** [comment]
We have no objections for adding veraPDF to Flathub.org. 

As we keep maintaining the product, we don't mind to be involved into the maintenance of  new releases at Flathub.org, if we understand better what is required from our side.

**Comment by nbenitez** [comment]
Yes, that's the ideal situation when proper authors also maintain it in Flathub, you can subscribe to https://github.com/flathub/flathub/pull/2073 in the meantime, when it's finally published I can guide you how to add new releases (usually just a matter of a git commit to add new download file and version string).

**Comment by carlwilson** [comment]
@nbenitez we can see that publication happened a year ago. We now have a 1.20 release ready, is there anything we need to do here.

**Comment by carlwilson** [comment]
Note to selves that Flathub is now on the phantom 2.0 https://flathub.org/apps/details/org.verapdf.veraPDF

**Comment by nbenitez** [comment]
> @nbenitez we can see that publication happened a year ago. We now have a 1.20 release ready, is there anything we need to do here.

Current version in flathub is 2.0.72 -> `verapdf-greenfield-2.0.72-installer.zip` so why now 1.20, has the versioning scheme changed? so is now 1.20 indeed newer that 2.0.72 ?

**Comment by nbenitez** [comment]
I just asked permission so you can commit new releases to flathub if you want, it's easy just see how I do in my next commit.
