### ISSUE TITLE
After Validation i get the error: "IOException when saving the HTML report"

### ISSUE THREAD

**Issue by Kirparon** [veraPDF/veraPDF-library#1136]
Hello,

i have a Problem with VeraPDF. When i validat a PDF Document, it works, but i cant geht the HTML Report.

Everytime when i use a Validation i get the Error: "IOException when saving the HTML report".

Did someone know, what the problem is?

**Comment by Kirparon** [comment]
I use it on Windows 10 Pro 2004 and the VeraPDF Version is 1.16.1

**Comment by carlwilson** [comment]
Hi, @Kirparon please can you confirm what folder the application is trying to write the results to. Please check that the folder is writeable by the account that veraPDF is running under.

**Comment by irinamavrina** [comment]
https://github.com/veraPDF/veraPDF-validation/pull/425

**Comment by irinamavrina** [comment]
https://github.com/veraPDF/veraPDF-library/pull/1203

**Comment by bdoubrov** [comment]
Fix released in v1.20
