### ISSUE TITLE
Calculation of glyph width when nominalWidthX in the font dictionary is 0, which is the default value.

### ISSUE THREAD

**Issue by trueroad** [veraPDF/veraPDF-library#1145]
When validating [test-rel.pdf](https://github.com/veraPDF/veraPDF-library/files/6036573/test-rel.pdf) with veraPDF 1.19.10 reports the following error.

| Rule | Status |
| ---- | ----|
| Specification: ISO 19005-2:2011, Clause: 6.2.11.5, Test number: 1 | |
| For every font embedded in a conforming file and used for rendering, the glyph width information in the font dictionary and in the embedded font program shall be consistent. | Failed |
| 1 occurrences | Hide |
| Glyph | |
| renderingMode == 3 || isWidthConsistent == null || isWidthConsistent == true | |
| root/document[0]/pages[0](9 0 obj PDPage)/contentStream[0](10 0 obj PDContentStream)/operators[11]/usedGlyphs[0](RPIXYR+HaranoAjiMincho-Regular 15520 0 0) | |

However, other validators report different results.

* pdfen.com
    * valid
* pdf-online.com
    * valid

If I understand correctly, veraPDF seems to have a problem calculating glyph width when nominalWidthX in the font dictionary is 0, which is the default value.

**Comment by bdoubrov** [comment]
Fixed in https://github.com/veraPDF/veraPDF-parser/pull/448
