### ISSUE TITLE
stderr and stdout interleave output from CLI

### ISSUE THREAD

**Issue by jackdos** [veraPDF/veraPDF-library#1155]
When running verapdf from the command line, the XML report appears to be streamed to stdout line by line, if an error during processing occurs after this has started, messages printed to stderr as a result will end up on the console display in the middle of the xml. This can be fixed by ensuring stdout and stderr are written to different pipes, but the documentation does not indicate that this is necessary. This is a problem if any process wrapping the CLI doesn't separate stderr and stdout as the error message in the middle of the xml means the resultant overall stream is not valid XML.

This would probably not be an issue if the entire XML output was written to stdout at the end of the process when the whole document is ready, rather than line by line in sync with when each line is ready, as this would likely at least mean that the valid XML block could be separated from the error messages.

See attached screenshots

![console-output-default](https://user-images.githubusercontent.com/10220473/111669848-1d284f00-880f-11eb-89c2-a1782aa3b247.png)
![console-output-no-stderr](https://user-images.githubusercontent.com/10220473/111669853-1dc0e580-880f-11eb-8c1f-d4fa1bcfee1c.png)

**Comment by carlwilson** [comment]
Hi @jackdos we believe we are doing this right at the moment and the solutions are pretty standard. Closing.
