### ISSUE TITLE
PFB extra binary markers - veraPDF

### ISSUE THREAD

**Issue by anna091621** [veraPDF/veraPDF-library#1157]
I am getting the warning below when trying to validate a PDF/A-1b with veraPDF. The same file does not shows any warnings with Adobe. 

_"WARNING: Type 1 fonts in PFB format are not permitted"
"The font programs for all fonts used within a conforming file shall be embedded within that file, as defined in PDF Reference 5.8, except when the fonts are used exclusively with text rendering mode 3"_

Based on this https://github.com/veraPDF/veraPDF-library/issues/1118: 
_"PFB is a special packaging format for Type1 fonts. It is a fairly simple technical task to "unpackage" the font by removing extra binary markers introduced by PFB package. This is what normally a PDF processor implements when embedding such fonts into PDF. Embedding PFB files as is leads to the violation of the standard. Although most of the font libraries are flexible enough to accept PFB files. But this doesn't make PDF files compliant to the specification."_ 

It looks like the .PFB file is composed of three parts (a dictionary with font info, actual font bytes encoded, and the fixed content). These three parts are defined by Lenght1, Length2, and Length3 in the FontFile field of the FontDescription dictionary.

Which of the above are the extra binary markers that needs to be removed to make it compliant with veraPDF?

**Comment by bdoubrov** [comment]
Packaging of PostScript fonts into PFB files is specified in [Adobe Technical Note #5040](https://adobe-type-tools.github.io/font-tech-notes/pdfs/5040.Download_Fonts.pdf). In particular, a PFB font is split into multiple binary or ASCII segments as specified in Section 3.3 of this Technical Note. 

This is not to be confused with three parts of PostScript fonts defined by Length1, Length2 and Length3.
