### ISSUE TITLE
Add link to documentation on VeraPDF web site

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-library#1158]
On the [VeraPDF website](https://verapdf.org/) I can no longer find any reference to the documentation that's available on <https://docs.verapdf.org/>. I'm not even sure if there ever was such a link, but whatever the case the docs are now impossible to find unless you know they exist. I would suggest to add a menu item for this.

Related side-note: even though VeraPDF has excellent support for various kinds of metadata extraction, this functionality is now buried under a sub-page  of <https://docs.verapdf.org/cli/>, which is difficult to find. I have the impression that most people aren't even aware that VeraPDF is capable of this. I think this could be featured/advertised more prominently in the description and docs.

**Comment by bdoubrov** [comment]
The link to the documentation has been added to the Software page
