### ISSUE TITLE
verapdf-gui.bat does not open the GUI window

### ISSUE THREAD

**Issue by audealexandre** [veraPDF/veraPDF-library#1159]
Hi,

I installed the last stable version of Verapdf (Greenfield branch) on Windows 10, in the recommanded location (Users/myusername/verapdf). Everything seemed to work fine.

Following the user guide, I then tried to start the GUI by double-clicking on the file verapdf-gui.bat. However, I see only a cmd shell briefly opening and shutting down, without any error message or opening of the GUI window. It seems that the software just opens and closes. 

I uninstalled and reinstalled verapdf, but the problem is still the same. 

Could you help me with this problem? (I am sorry if it has already be covered, I didn't find any other similar issue). 

Thanks in advance,

Best wishes

Aude

**Comment by bdoubrov** [comment]
Would you please specify version of Java installed on your system. You can use `java -version` in the Windows cmd tool to find it.

**Comment by audealexandre** [comment]
It does not work via the Windows cmd ("java" is not recognized as internal command"), but herunder the printscreen of the Java runtime environment. Does that help? 
![Java](https://user-images.githubusercontent.com/81013898/115595629-72a4bf80-a2d7-11eb-8925-d12cbb3bc581.PNG)

Thanks

**Comment by bdoubrov** [comment]
Please make sure the Java folder is included into your PATH environment variable. Looks like it is not the case

**Comment by audealexandre** [comment]
Thanks. I am sorry, but could you give me more specific steps to follow? I do not know how to configure this. 
Thanks in advance,

**Comment by bdoubrov** [comment]
Please check for example this video: https://www.youtube.com/watch?v=41aElKvKnwg

**Comment by audealexandre** [comment]
Thanks a lot, Boris, it is now working fine!
Best wishes,

Aude
