### ISSUE TITLE
PDF Association logo is old

### ISSUE THREAD

**Issue by petervwyatt** [veraPDF/veraPDF-library#1162]
The PDF Association logo is out of date in the 1.18 release GUI Help | About dialog:

![image](https://user-images.githubusercontent.com/26521615/116197463-24306e80-a778-11eb-8e86-6477bf3777d8.png)

Please update.

**Comment by carlwilson** [comment]
Thanks for this @petervwyatt it's the new coloured square logo now used on the website I presume?

![pdf-association-logo-300x141](https://user-images.githubusercontent.com/440634/116206916-33db9300-a737-11eb-90fd-04509be95d3a.png)

**Comment by carlwilson** [comment]
We've released a new apps build (1.18.6) that has the new logo instead. @petervwyatt if you could confirm that the new about page is OK we will close this issue. Thanks for reporting this.

**Comment by petervwyatt** [comment]
Confirmed that the above image is the correct logo and that 1.18.6 dialog has the same new logo. 
Thanks for the rapid fix!
