### ISSUE TITLE
There is a difference in feature.xml fields between VeraPDF 1.16.1 and those described in the docs today, are the fields missing from the docs

### ISSUE THREAD

**Issue by ross-spencer** [veraPDF/veraPDF-library#1165]
Question/issue as per: https://github.com/veraPDF/verapdf-webapp-gui/issues/134 - were the fields removed or do the docs need updating?

**Comment by bdoubrov** [comment]
Thanks, @ross-spencer . I misunderstood initially your question. Yes, this is the documentation that needs to be updated. 

Actions (ACTION feature) and Interactive form fields (INTERACTIVE_FORM_FIELDS feature) are available as PDF features reported by veraPDF. And yes, Errors were deprecated at some moment and are included (if any) in the veraPDF report unconditionally.  

We'll update the documentation at docs.verapdf.org

**Comment by bdoubrov** [comment]
The documentation was updated at https://docs.verapdf.org/cli/config/#features.xml
