### ISSUE TITLE
JPX ColorSpace can be overridden

### ISSUE THREAD

**Issue by faceless2** [veraPDF/veraPDF-library#1183]
Attached PDF has a JPX compressed stream with ColorSpace specified; this overrides any colorspace in the JPX content, so the fact the JPX stream doesn't have the correct colr box is immaterial

[preflight-PDF_1575_492551.pdf](https://github.com/veraPDF/veraPDF-library/files/7259955/preflight-PDF_1575_492551.pdf)

**Comment by bdoubrov** [comment]
This one is very interesting. I agree that all PDF/A requirements on JPEG 2000 embedded color space definition are not relevant if they are overridden by the explicitly defined **ColorSpace** in the image dictionary. Yet, there is nothing about this in ISO 19005-2(3) and as read now, the clause 6.2.8.3 (JPEG2000) is applicable to both situations: when we have and do not have such **ColorSpace** externally defined. 

Again, I'd double check this at the TWG.

**Comment by bdoubrov** [comment]
As per resolution of PDF/A TWG we exclude `colr` box from the PDF/A-2,3,4 requirements (rules 6.2.7.3-2, 6.2.7.3-3, 6.2.7.3-4) if the image dictionary has an explicitly specified ColorSpace entry.

**Comment by bdoubrov** [comment]
Fix released in v1.20
