### ISSUE TITLE
Separations All and None are exempt from ColorSpace requirements.

### ISSUE THREAD

**Issue by faceless2** [veraPDF/veraPDF-library#1184]
As title. From ISO32K:

> A conforming reader shall support Separation colour spaces with the colorant names All and None on all devices, even if the devices are not capable of supporting any others. When processing Separation spaces with either of these colorant names conforming readers shall ignore the alternateSpace and tintTransform parameters (discussed below), although valid values shall still be provided.

[preflight-PDF_675_184127.pdf](https://github.com/veraPDF/veraPDF-library/files/7259966/preflight-PDF_675_184127.pdf)

**Comment by bdoubrov** [comment]
Indeed, veraPDF reports an error that a separation **All** uses different alternate CS and tint Transform on different pages. 

I would agree that this contradicts to what ISO32K states, even if ISO 19005-2(3) does not explicitly exclude All and None from the requirement for Separation arrays with the same name to be consistent. 

Yet, I see at least one other validator to follow the current veraPDF logic. So, I'd reconfirm this at the PDF/A TWG to have a community consensus on this.

**Comment by faceless2** [comment]
Bounced issue to PDF/A TWG - thanks.

**Comment by bdoubrov** [comment]
Per resolution of PDF/A TWG, we indeed should exclude All and None separations from the requirements of the rule 6.2.4.4-2 (PDF/A-2, PDF/A-3, PDF/A-4).

**Comment by bdoubrov** [comment]
Fix released in v1.20

**Comment by bdoubrov** [comment]
Discussion group "Aligning PDF/X and PDF/A" reverted this decision: the rule on identical alternate CS and Transfer function is also applicable to `All` and `None` colorants. The corresponding changes were done in the dev version veraPDF 1.25 and will be included into the next release 1.26
