### ISSUE TITLE
XMP Extensions: doesn't like "Part" type definition

### ISSUE THREAD

**Issue by faceless2** [veraPDF/veraPDF-library#1185]
We've got quite a few files like this. We think this is valid, but veraPDF doesn't. The common thread through all of them seems to be that veraPDF doesn't like the way we define the "Part" type in the PDF/A extension schema. Boris, we've discussed out-of-band about "ResourceRef" being defined before "Seq ResourceRef" and whether that matter, but I don't think this is the same issue.

[preflight-veraPDF.PDF_A-1b.6-7-2-t09-pass-o.pdf](https://github.com/veraPDF/veraPDF-library/files/7260451/preflight-veraPDF.PDF_A-1b.6-7-2-t09-pass-o.pdf)

**Comment by bdoubrov** [comment]
The issue with `valueType Part` in this document is that it is defined in one namespace (`xmpMM`), but is used (without any prefix) for field definition in another namespace (`stRef`). 

Citing ISO 19005-3, the paragraph after Table 4 - PDF/A Property value type:
_The values for pdfaProperty:valueType shall either be value types defined in the XMP Specification or
custom value types defined within **the extension schema**._

I would assume that **the extension schema** is the schema where this new property is defined and not any extension schema within this document. But this is indeed tricky and I suggest to move this to the PDF/A issues for further discussion.

**Comment by faceless2** [comment]
Right, that makes sense - thanks. I'll raise an issue there and try and find some more evidence to back up my belief that its necessary.

**Comment by faceless2** [comment]
Followup - I think I largely agree with you actually, but I'm still having trouble generating something veraPDF will accept. I've opened https://github.com/pdf-association/pdfa-twg/issues/8 to carry on discussion and will close this.
