### ISSUE TITLE
Reference to wrong GPG public key

### ISSUE THREAD

**Issue by aschokker** [veraPDF/veraPDF-library#1190]
Hi,

I imported GnuPG key ID 1C124847 in my GPG key chain (https://docs.verapdf.org/install/  refers to this key). Please note that this key has expired on 2020-06-07. Furthermore it seems that the software I downloaded from the same website (i.e. verapdf-installer.zip and verapdf-installer.zip.asc) has not been signed with this key, since the command:

`gpg --verify verapdf-installer.zip.asc verapdf-installer.zip`

resulted in:

```
gpg: Signature made Fri 08 Oct 2021 11:59:16 AM CEST
gpg:                using RSA key 13DD102B4DD69354D12DE5A83184863278B17FE7
gpg: Can't check signature: No public key
```

Looking for key 0x78B17FE7 on keyserver https://keyserver.ubuntu.com lead to uid: Carl Wilson <techlead@verapdf.org>, while the expired key 0x1C124847 has uid; veraPDF Jenkins (veraPDF development key) <techlead@verapdf.org>.

Since both keys have the same email address and Carl Wilson's signature is made on 2020-06-19 (12 days later than the expired key), I assume it's all safe. Please confirm (and update :-).

Regards,
aschokker

**Comment by carlwilson** [comment]
Hi @aschokker I've taken a look at this and can confirm that we lost access to `0x1C124847` and it is now defunct. I've just extended `0x78B17FE7` for another year so all is well now thanks. Closing this.
