### ISSUE TITLE
greenfield and pdfbox 1.19.232 diverging on clause 6.2.11.4

### ISSUE THREAD

**Issue by lenoleno** [veraPDF/veraPDF-library#1198]
Attached PDF/A-2B file is checked successfully by verapdf 1.19.232 greenfield implementation, while pdfbox implementation detects a violation of clause 6.2.11.4.

    If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream ...

According to #956, "the goal is always to have both versions of veraPDF to be fully compatible. So, any difference in validation results are to be fixed."

[a-2b-6.2.11.4.pdf](https://github.com/veraPDF/veraPDF-library/files/7516391/a-2b-6.2.11.4.pdf)
[dev-1.19.232-gf.xml.txt](https://github.com/veraPDF/veraPDF-library/files/7516392/dev-1.19.232-gf.xml.txt)
[dev-1.19.232-pb.xml.txt](https://github.com/veraPDF/veraPDF-library/files/7516393/dev-1.19.232-pb.xml.txt)

**Comment by carlwilson** [comment]
duplicate of #956
