### ISSUE TITLE
XMP parsing of empty Seq

### ISSUE THREAD

**Issue by eabalea** [veraPDF/veraPDF-library#1200]
When validating a PDF/A-1b document containing empty Author and empty Subject keys in the information dictionary (among other keys), an attempt is made to compare the keys with the metadata stream content (using table 1/2 of ISO19005-1).
Empty Subject compares positively with an empty subject Bag (<dc:subject><rdf:Bag/></dc:subject>).
Empty Author compares negatively with an empty creator Seq (<dc:creator><rdf:Seq/></dc:creator>), the metadata fixer changes this to <dc:creator><rdf:Seq><rdf:li/></rdf:Seq></dc:creator> (i.e. a sequence of one empty element, instead of an empty sequence).

XMP2014 is clear that an rdf:Bag/Seq/Alt consists of zero or more rdf:li elements.

Is it a bug in veraPDF?

PDF/A-2 and 3 avoid this validation step (the information dictionary shall ignore it).

**Comment by bdoubrov** [comment]
Note that **Subject** entry in the Info dictionary shall be compared with `dc:description['x-default']` in XMP schema (not `dc:subject` !). As for the **Author** entry, it is compared with `dc:creator[1]`, that is the first (and the only one) element in `dc:creator Seq`.

This is not fully clear in ISO 19005-1, but is clarified in TechNote 0003 of PDF Association: https://www.pdfa.org/wp-content/uploads/2011/08/tn0003_metadata_in_pdfa-1_2008-03-182.pdf (Section 3.3)

**Comment by bdoubrov** [comment]
closing this issue after the release of 1.20. @eabalea feel free to reopen it if disagree. See also the previous comment.
