### ISSUE TITLE
PDF/A-3A validation failed for file with non embedding type2 CID fonts

### ISSUE THREAD

**Issue by payaln** [veraPDF/veraPDF-library#1209]
We are talking about rule https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Parts-2-and-3-rules#rule-62113-2
It is implied that CIDToGIDMap should be present **only for embedded** fonts. But the check is performed regardless of whether the font is embedded.
The attached file does not pass validation in VeraPDF, although it meets the specification (with text rendering mode 3, non-embedding of fonts is allowed)
[Result._Metrics.pdf](https://github.com/veraPDF/veraPDF-library/files/7669317/Result._Metrics.pdf)

**Comment by bdoubrov** [comment]
Thanks! This is a valid point. We'll adjust this validation rule to make sure it is applicable only to the fonts with the embedded font programs.

**Comment by bdoubrov** [comment]
Fix released in v1.20
