### ISSUE TITLE
Online REST API

### ISSUE THREAD

**Issue by marco-zorzi** [veraPDF/veraPDF-library#1214]
It would be useful to have an online service to check pdf/a using cURL and authenticating with an API key.

**Comment by bdoubrov** [comment]
Could you check that the existing REST API running at https://demo.verapdf.org and documented here: https://github.com/veraPDF/veraPDF-rest works already for you.

**Comment by marco-zorzi** [comment]
Hi @carlwilson, 
It works, Thanks.
