### ISSUE TITLE
Latest version of verapdf-apps

### ISSUE THREAD

**Issue by alexreg** [veraPDF/veraPDF-library#1218]
I'm a little confused that verapdf-apps seems to have a v2.0.75, but this is quite old, and v1.21.4 seems to be created most recently. Could someone please explain this to me?

**Comment by bdoubrov** [comment]
Sorry for confusion. 

2.0.x was a development branch for PDF/UA-1 support. But in the end it was decided to release it as 1.18, as public API was not affected. So, there is no veraPDF version 2.x, in fact. The latest release version is 1.20.1, and 1.21.x is the new development branch, that will eventually lead to 1.22 release.

**Comment by alexreg** [comment]
Okay, thanks. Maybe you can remove or rename those tags at some point... but big deal if not.

**Comment by bdoubrov** [comment]
Removed 2.0.* tags to avoid confusion.
