### ISSUE TITLE
Exception on Windows OS, if "destination folder name" contains spaces

### ISSUE THREAD

**Issue by georgetarazevich** [veraPDF/veraPDF-library#1230]
On Windows v. 10 & 11 when using Java v. 11, if "destination folder name" contains spaces one gets the Exception: ClassNotFoundException for GUI and CLI independently - is defined 'CLASSPATH' or not.

No problem if using Java v. 1.8.

**Exception details:**
![spaces_win_11_java_11](https://user-images.githubusercontent.com/12056147/156720869-2c36c67b-7dcf-47db-89ad-aae58b9fdd1b.jpg)
![spaces_win_10_java_11](https://user-images.githubusercontent.com/12056147/156720870-1845583d-a3b6-493f-a97b-0bc88b976a75.jpg)

**Comment by irinamavrina** [comment]
https://github.com/veraPDF/veraPDF-library/issues/1230
