### ISSUE TITLE
VeraPDF V1.20.1 Release: PDFA-1b Testcase 6.3.4 is not longer an error?

### ISSUE THREAD

**Issue by IssueReporter12345** [veraPDF/veraPDF-library#1233]
We have three PDF in a directory and call: VeraPDF.bat -f 1b
There are differents in the last pdf "pdfa1b.pdf".

The PDFA-1b check with VeraPDF version 1.14.102 deliver follow check result file: result-f-1b_Version1.14.102.xml
[result-f-1b_Version1.14.102.xml.txt](https://github.com/veraPDF/veraPDF-library/files/8321814/result-f-1b_Version1.14.102.xml.txt)

The PDFA-1b check with VeraPDF version 1.20.1 deliver follow check result file: result-f-1b_Version1.20.1.xml
[result-f-1b_Version1.20.1.xml.txt](https://github.com/veraPDF/veraPDF-library/files/8321817/result-f-1b_Version1.20.1.xml.txt)

During check send VeraPDF 1.20.1 follow warnings to the console:
M├ñr 18, 2022 11:44:46 AM org.verapdf.pd.font.type1.Type1PrivateParser decodeCharString
WARNING: Error in parsing private data in Type 1 font: incorrect amount of charstings specified.

Question:
Does this "parsing error" cause the testcase 6.3.4 found in version 1.14 to be erroneously not complained about in version 1.20?
Remark: The testcase 6.3.4 is further documented on https://docs.verapdf.org/validation/pdfa-part1/

**Comment by bdoubrov** [comment]
In the latest release 1.20 we've added a more robust logic of parsing the embedded Type1 fonts. Certain non-critical violations of the font format are now reported as warnings in the log, while earlier versions were treating such font files as invalid. This in its turn was resulting in the failed rule 6.3.4-1, which requires all fonts to be (correctly) embedded.

Depending on your policy you may or may not ignore such warnings.
