### ISSUE TITLE
Split pacakges cause failure when migrating to Java 9+

### ISSUE THREAD

**Issue by ivsart** [veraPDF/veraPDF-library#1237]
I'm working on a migration of a legacy Java 8 application which uses veraPDF as a dependency. 

The `org.verapdf.pdfa.VeraGreenfieldFoundryProvider` and the `org.verapdf.pdfa.PDFAParser`, `org.verapdf.pdfa.Foundries`, `org.verapdf.pdfa.PDFAValidator` are all declared in the `org.verapdf.pdfa` package, albeit in different libraries (`core` and `validation model`). 

As a result they cannot be used with the JPMS, the Java module system introduced in Java 9, since the common package name creates a split package. Although there are ways to circumvent the issue, the best way to resolve this would be to avoid the split packages altogether, by moving the affected classes to new ones.

**Comment by carlwilson** [comment]
Hi @ivsart and thanks for reporting this though I confess that JPMS is new to me. Could you give us a little more information as to how to go about reproducing the issue, please? You mention that there are established methods to circumvent/resolve the issue, would you mind expanding a little. We'll be happy to try to put this right for you. Thanks.

**Comment by ivsart** [comment]
Hi, Carl and thanks for the outstanding work!

Here is  a small example for clarification: [verapdfsplitpackageissue.tar.gz](https://github.com/veraPDF/veraPDF-library/files/8396911/verapdfsplitpackageissue.tar.gz)

When this is build and executed, the following error is produced by the compiler:
`java: the unnamed module reads package org.verapdf.pdfa from both validation.model and core`

This error is a result of the incorrectly [splitting packages](https://docs.oracle.com/cd/E36784_01/html/E36856/glyrq.html) between the two libraries (`core` and `validation model`). 

So the solution would be to rename the org.verapdf.pdfa in either `core` or `validation-model`, so that they do not overlap. 

The workarounds are not great, but work when dealing with such an issue. In the example above, the [`--patch-module`](https://docs.oracle.com/en/java/javase/14/docs/specs/man/javac.html#patching-modules) Java compiler runtime option works, by artificially merging the `core` and `validation-model` libraries at compile time into a new module to overcome the problem, but this is highly undesirable way to solve the issue and is not recommended for production environments. 

You can test that the above solution works by removing the `requires validation.model;` line from `module-info.java` and by uncommenting the `compilerArgs` part of the `maven-compiler-plugin` in the `pom.xml`.


Other available options are excluding classes from dependencies, but this is also not possible in all cases (as is this one).

**Comment by carlwilson** [comment]
I've at least investigated this properly now. It appears that there are three projects that are causing the issue:

- the classes in [veraPDF-library:core](https://github.com/veraPDF/veraPDF-library/tree/integration/core/src/main/java/org/verapdf/pdfa);
- the classes in [veraPDF-validation:validation-model](https://github.com/veraPDF/veraPDF-validation/tree/integration/validation-model/src/main/java/org/verapdf/pdfa); and
- the classes in [veraPDF-pdfbox-validation:pdfbox-validation-model](https://github.com/veraPDF/veraPDF-pdfbox-validation/tree/integration/pdfbox-validation-model/src/main/java/org/verapdf/pdfa).

I think we'll be able to make this change without breaking our API by changing the package declarations in the two validation projects.
