### ISSUE TITLE
veraPDF CLI - add an option to export the XML report to a defined folder

### ISSUE THREAD

**Issue by miguelsalesb** [veraPDF/veraPDF-library#1241]
Is it possible to add an option to the command line interface, to export an XML file with the validation report, to a folder defined by the user, and run it on a Windows machine?

**Comment by bdoubrov** [comment]
This should already work by redirecting the standard output (where the report is written by default) to any file at any location. For example:
`./verapdf.bat ./mytest.pdf > C:/Temp/myreport.xml`

**Comment by miguelsalesb** [comment]
Yes, it is working. Thank you very much, Boris!

**Comment by miguelsalesb** [comment]
Hi Carl, it worked with multiple files. 

I ran the following command in a Windows command prompt: verapdf C:\Users\mbaptista\verapdfGreenfield\input > C:\Users\mbaptista\verapdfGreenfield\output\report.xml, 
and an xml file was created with the validation report of all the files that were inside the 'input' folder. 

I attached the report file.

Thank you all for helping me!

[report.txt](https://github.com/veraPDF/veraPDF-library/files/8484101/report.txt)

**Comment by miguelsalesb** [comment]
Great tip, Carl! We will do as you suggest.
We have everything we need. Thank you very much for the tip, as well as for the call, and for the great software that you contribute to.
