### ISSUE TITLE
Review and enhance error messages 

### ISSUE THREAD

**Issue by bdoubrov** [veraPDF/veraPDF-library#1246]
Currently error messages are present only in XML reports and are not visible in HTML reports. One big advantage for error messages is the possibility to use variable data placeholders that can provide additional info on the underlying property values that are relevant for better understanding of an error.

As  a part of this issue, we'd like to:
- review and improve the existing error messages
- optionally enable / disable them in the XML report (having all of them in XML might cause significant increase of XML report size in batch processing)  
- optionally add them to HTML report, eg., as tooltips

**Comment by MaximPlusov** [comment]
Included into release 1.24
