### ISSUE TITLE
PDF/A invalid due to missing element (according to technical notes should be valid?)

### ISSUE THREAD

**Issue by ostnatalie** [veraPDF/veraPDF-library#1257]
We are using VeraPdf in version 1.16 and 1.18.6 (and we also tested the newest 1.20.3 to see if it reports the same) and we have found out, that our PDF/A-1b documents are marked as invalid. The reason they are marked invalid is this error in PDF: https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-678-3

![image](https://user-images.githubusercontent.com/97174678/171169411-5ba01203-2c52-418a-b0f6-9d4f62eee84d.png)

Element **<pdfaSchema:valueType>** is missing in our PDF/A. But technical notes (page 9, chapter 4.3:https://www.pdfa.org/wp-content/uploads/2011/09/tn0009_xmp_extension_schemas_in_pdfa-1_2008-03-20.pdf) says, that this property may be absent (or empty) if there are no custom types. Based on our tests, VeraPdf says, that if element <pdfaSchema:valueType> is empty, then the PDF/A-1b is valid, but if the property <pdfaSchema:valueType> is missing, then the PDF/A-1b is invalid. 

We have validated the same PDF/A-1b (the one missing element <pdfaSchema:valueType>) with 3-Heights validator and the PDF is marked as valid. We have found that this topic was discussed
in this issue: [https://stackoverflow.com/questions/38997297/tcpdf-generated-pdf-does-not-conform-to-pdf-a-standart ](https://stackoverflow.com/questions/38997297/tcpdf-generated-pdf-does-not-conform-to-pdf-a-standart%20) from 2017 where 3-Heights validator marked this also as an error in PDF and thus marked it as invalid, but actual version of 3-Heights validator does not mark this as an error, so they made correction of the tool. This is the test file https://tcpdf.org/examples/example_065/ with missing <pdfaSchema:valueType>. 
Could you please look into it?

**Comment by MaximPlusov** [comment]
verapdf error is caused by missing **pdfaSchema:property** in this schema definition:
```
<rdf:li rdf:parseType="Resource">
	<pdfaSchema:namespaceURI>http://ns.adobe.com/pdf/1.3/</pdfaSchema:namespaceURI>
	<pdfaSchema:prefix>pdf</pdfaSchema:prefix>
	<pdfaSchema:schema>Adobe PDF Schema</pdfaSchema:schema>
</rdf:li>
```

**Comment by ostnatalie** [comment]
Ok, now I see it, thank you for your answer and clarification!  pdfaSchema:property was really missing in our PDF. It is not problem of veraPdf so I am closing this issue.
