### ISSUE TITLE
Find rule not described in specification

### ISSUE THREAD

**Issue by cybernetic10** [veraPDF/veraPDF-library#1268]
In one file was found this error:
```
          <rule specification="ISO 19005-4:2020" clause="6.9" testNumber="1" status="failed" passedChecks="0" failedChecks="1">
            <description>The embedded file stream dictionary shall include a valid MIME type value for the Subtype key.
                If the MIME type is not known, the value "application/octet-stream" shall be used.</description>
            <object>EmbeddedFile</object>
            <test>Subtype != null &amp;&amp; /^[-\w+\.]+\/[-\w+\.]+$/.test(Subtype)</test>
            <check status="failed">
              <context>root/indirectObjects[106](223 0)/directObject[0]/EF[0]</context>
              <errorMessage>The MIME type information (Subtype entry) of an embedded file is missing or invalid</errorMessage>
             </check>
          </rule>
```
But in cluase 6.9 of ISO 19005-4:2020, there is no infromation about such error (MIME type).

**Comment by bdoubrov** [comment]
Thanks a lot for bringing this up. 

Indeed, this requirement on a valid MIME type has moved from PDF/A specifications to the code PDF 2.0 specification (clause 14.13.2) with the identical wording:
> The embedded file stream dictionary shall include a valid MIME type value for the Subtype key. If the MIME type is not
known, the value "application/octet-stream" shall be used.

We'll correct the reference in the rule.
