### ISSUE TITLE
Expose current job execution status to the user

### ISSUE THREAD

**Issue by bdoubrov** [veraPDF/veraPDF-library#1271]
As an initial step, we would like to optionally output in the CLI the current status of the validation job:
- number of passed / failed checks
- number of processed objects
- number of objects in the stack to be processed

As initial prototype, we would like to add an option to output this information as a one-line message to the stdout per each 1000  (this number can be configurable) checks.   

The option might look like:

`verapdf --progress 1000 test.pdf`

where `--progress 0` (default) means no progress is shown.

**Comment by bdoubrov** [comment]
Extra requests: 
- try to keep the progress line updated instead of outputting the new line each time. See how this works for example for Docker pull/run and other installation tools
- remove the argument from --progress property and instead start updating the progress each 10^n checks, when more than 10^n checks were performed . So, initially we update progress each check, then each 10 checks, then 100 checks, and so on.

**Comment by bdoubrov** [comment]
Looks like Node.js package https://www.npmjs.com/package/log-update is able to update logs in a very flexible way. Makes sense to check if the equivalent functionality is already available or can be easily implemented in Java.

**Comment by irinamavrina** [comment]
https://github.com/veraPDF/veraPDF-apps/pull/347
https://github.com/veraPDF/veraPDF-library/pull/1276

**Comment by MaximPlusov** [comment]
Included into release 1.24
