### ISSUE TITLE
Not expected logs on CLI

### ISSUE THREAD

**Issue by georgetarazevich** [veraPDF/veraPDF-library#1273]
Steps to reproduce:

Select Logging level "ALL"  mode  and run validation (any PDF file).  
Don't wait for the logging to finish - Close GUI.

If you try to start veraPDF in the CLI (even without option) you will see a continuation of the logs from the last start. 
(Ubuntu 20.04, veraPDF 1.22.0-RC, Java 11).

**Comment by irinamavrina** [comment]
https://github.com/veraPDF/veraPDF-apps/pull/331

**Comment by georgetarazevich** [comment]
Verified in v. 1.22.0-RC2
