### ISSUE TITLE
consistency between cli and gui outputs

### ISSUE THREAD

**Issue by dmm108** [veraPDF/veraPDF-library#1278]
Hello – I could use some help understanding how to get consistent results using the gui and cli versions of verapdf, and also the role of the config files using the cli interface.
I ran the same pdf through verapdf-gui, in mode validate, and also using the cli.
The features were all unselected both in the gui features dialog, and removed from the features.xml config file. Additionally, the app.xml file was set to VALIDATE, and the fixer.xml config file had the fixId set to “false”, and the corresponding gui controls were set the same way.  
Both versions were run with  maximum failures set to 2, since without that there was a voluminous amount of assertion checks.  This is the command line invocation:

verapdf --format xml --maxfailures 2 radiation.pdf 

These are the lengths of the outputs:
dmm@DB-len:VERA)  ls -l radiation--val-[cg]??-m*
-rw-rw-r-- 1 dmm dmm  3047 Sep 12 11:34 radiation--val-cli-max2.xml
-rw-rw-r-- 1 dmm dmm 50280 Sep 12 12:27 radiation--val-gui-max2.xml

The cli output, which follows is pretty much as expected.  Present is both a validationReport and validationResult section, and 2 failed tests, after which following tests are suppressed.

The gui output has no validationResult section, and has 590 lines of test results.  It also has a metadataRepairReport, not present in the cli output, even though the ‘fix metadata’ box was unselected in the gui.

It seems to me that the cli invocation does not strictly follow the config files in the config directory, but it’s not clear what is and is not used.  I know that validation is run automatically unless the --off option is used, even if the app.xml file does not specify validation.  

So any help is very much appreciated in sorting this out.
Below are the cli and gui outputs, as well as the validator, features and app config files.

Sincerely,
David

This is the gui output, with about 590 lines of rule specifications suppressed:

![vera-gui-m2](https://user-images.githubusercontent.com/19844514/189993573-e68f2011-f960-4ca0-9d5c-1083afca7f58.JPG)

This is the cli output:

![vera-cli-m2](https://user-images.githubusercontent.com/19844514/189996379-62e54f69-2a17-467a-8227-b5e5d31adfa5.JPG)

Config files:

![configs](https://user-images.githubusercontent.com/19844514/189998401-27fb874e-5f72-4a5e-a1d4-fd7469474342.jpg)

**Comment by bdoubrov** [comment]
There might indeed be a slight inconsistency in the terminology. The XML report format generated by the GUI is called `mrr` in CLI terminology and is also a default one. So, you either omit `--format` option or use `--format mrr` to generate the report format identical to the one you get from the GUI as XML report.  

Next, CLI does not reuse the config files of the GUI application. It has instead equivalent options available as command line arguments.  

There is one exception though: veraPDF CLI reuses `features.xml` in case of feature extraction and policy checks (see https://docs.verapdf.org/policy/), as this is the only way to specify the categories of extracted features in case of CLI. 

I do agree this might look a bit confusing, and we'll see what we can improve here in terms of consistency between GUI and CLI apps.

**Comment by bdoubrov** [comment]
The latest dev version uses `xml` report format as a synonym of `mrr`, and what was previously called `xml` format is renamed to `raw`. In particular, XML reports from GUI and CLI now have the same format.

**Comment by MaximPlusov** [comment]
Included into release 1.24
