### ISSUE TITLE
Incorrect decryption of strings in the encrypted documents

### ISSUE THREAD

**Issue by bdoubrov** [veraPDF/veraPDF-library#1295]
The attached document raises the error on the invalid Lang value in the catalog in PDF/UA-1 validation. But the Lang is a correct string "JA". 

The document itself is encrypted, and veraPDF seem to incorrectly decrypt /Lang string.

[r5-tokushoku-hogaku.pdf](https://github.com/veraPDF/veraPDF-library/files/9798595/r5-tokushoku-hogaku.pdf)

**Comment by MaximPlusov** [comment]
Included into release 1.26
