### ISSUE TITLE
Unable to access Maven dependencies on https://artifactory.openpreservation.org/

### ISSUE THREAD

**Issue by jpl-jengelke** [veraPDF/veraPDF-library#1310]
Clean Maven builds fail when gathering VeraPDF dependencies. Bad gateway/Cloudflare message. 

See attached screenshot. 

Reproduce with: 
```
mkdir -p .tmp && mvn -U clean package -DskipTests -Dmaven.repo.local=$PWD/.tmp
```

![validate_vera_bad_gateway_20221129](https://user-images.githubusercontent.com/52300928/204698279-f0311b3d-895c-48ef-8f7b-6d46b2254723.png)

**NOTE:** It appears the top-level URL also results in a "bad gateway" message from Cloudflare.

**Error:** 
```
Failed to collect dependencies at org.verapdf:pdfbox-validation-model:jar:1.20.1 -> org.verapdf.pdfbox:pdfbox:jar:2.0.62[m: Failed to read artifact descriptor for org.verapdf.pdfbox:pdfbox:jar:2.0.62: Could not transfer artifact org.verapdf.pdfbox:pdfbox:pom:2.0.62 from/to vera-dev (https://artifactory.openpreservation.org/artifactory/vera-dev): Transfer failed for https://artifactory.openpreservation.org/artifactory/vera-dev/org/verapdf/pdfbox/pdfbox/2.0.62/pdfbox-2.0.62.pom 502 Bad Gateway -> [1m[Help 1]
```

**Comment by carlwilson** [comment]
Apologies @jpl-jengelke our artifactory server was knocked down by a hosting issue and we didn't notice until later than you. That's all fixed now but we will look at the possibility of adding an alternative in case something similar occurs.

**Comment by jeremyrsellars** [comment]
It seems this may be happening again.

**Comment by carlwilson** [comment]
Thanks for reporting @jeremyrsellars, there was an issue with our proxy server that's now fixed. The build should be working properly now.
