### ISSUE TITLE
VeraPDF throws validation error while Adobe Acrobat Reader states it's conforming to PDF/A standards

### ISSUE THREAD

**Issue by gianpaca** [veraPDF/veraPDF-library#1316]
Greetings,

I typically validate for PDF/A-1b my produced PDF documents using VeraPDF, but after some point of last year's last quarter I get the following error:

Specification: ISO 19005-1:2005, Clause: 6.3.5, Test number: 3 
For all CIDFont subsets referenced within a conforming file, the font descriptor dictionary shall include a CIDSet stream identifying which CIDs are present in the embedded CIDFont file, as described in PDF Reference Table 5.20

Test condition: fontName.search(/[A-Z]{6}\+/) != 0 || (CIDSet_size == 1 && cidSetListsAllGlyphs == true)

However, Adobe Acrobat Reader stills deems the file as conforming to PDF/A, and when I check the font name of the embedded fonts they would seem correct (for example EAAAAA+ArialUnicodeMS). I haven't been able to understand why VeraPDF throws this error or what steps should I follow to fix it.

I made a couple of sample PDFs that show this issue and will attach them to this issue along with the sample XSL file (as a txt) used for transformation and a few screenshots that may or not be of help.

Thank you in advance for your assitance.
---
[PDFA test Times New Roman.pdf](https://github.com/veraPDF/veraPDF-library/files/10482098/PDFA.test.Times.New.Roman.pdf)
![Adobe Acrobat Reader visualization of the sample pdf Arial](https://user-images.githubusercontent.com/90575997/214104774-c5ef900e-3a80-42b8-8cf5-55ef07cf3fa7.png)
![FontName EAAAAA+Arial using cmd from sample pdf](https://user-images.githubusercontent.com/90575997/214104776-30856d82-01a9-4d1b-9bfd-63e59b1549e0.png)
[PDFA test Arial.pdf](https://github.com/veraPDF/veraPDF-library/files/10482099/PDFA.test.Arial.pdf)
[Sample XSL.txt](https://github.com/veraPDF/veraPDF-library/files/10482108/Sample.XSL.txt)

**Comment by bdoubrov** [comment]
@gianpaca thanks a lot for bringing this issue. 

I see that Adobe Acrobat Preflight tool reports the same PDF/A validation error as veraPDF:
![image](https://user-images.githubusercontent.com/10971979/214275051-163959e5-1def-4c75-83a3-a97795c4d7f0.png)

Your screenshot of Adobe Reader just indicates that the document claims to be PDF/A compliant in its metadata. But this does not guarantee that the document is indeed a valid PDF/A file. Indeed, if you perform validation in Adobe Acrobat Professional, you will this that this claim is not verified:
![image](https://user-images.githubusercontent.com/10971979/214275416-1f4372fe-a2a6-4b25-9832-d7237e41fcbb.png)
  
So, veraPDF results are fully in sync with Adobe Acrobat ones on your files.

**Comment by gianpaca** [comment]
> Your screenshot of Adobe Reader just indicates that the document claims to be PDF/A compliant in its metadata.
Oh, I thought it was a way of verification. Thank you for clearing that for me!

I also believed as long as the subset was indicated it was ok, given the test condition was fontName.search(/[A-Z]{6}+/) != 0 and the file specified it as EAAAAA+ArialUnicodeMS.

Unfortunately I am a novice in the area, could you give me some guidance or point me towards where I could find a solution on how to generate a pdf with the complete CIDSet?

**Comment by bdoubrov** [comment]
Generating the correct CIDSet is the responsibility of the tool that created the document or did the conversion to PDF/A. You can normally raise issue against this tool, and their support team might be able to resolve it. 

We'll think also about adding the fix for CharSet / CIDSet to veraPDF fixer, which is limited only to Metadata fixes at the moment.

**Comment by gianpaca** [comment]
I see, thank you for your reply! I'll try updating to the latest version of FOP.

Thank you for your support
