### ISSUE TITLE
Question regarding PDF versions

### ISSUE THREAD

**Issue by AFalut** [veraPDF/veraPDF-library#1317]
We recently encountered an issue where documents saved as PDF/A-1, PDF/A-2 or PDF/A-3 using the ABBYY FineReader PDF editor always declare version 1.5 in their header. Despite this, veraPDF validates these documents as compliant with the flavor selected to save them, and we saw that its validation rules for PDF/A-1 did accept any version number, and the rules for PDF/A-2 and PDF/A-3 any version from 1.0 to 1.7.
We were wondering if this matched a tolerance of the PDF/A-1, 2 and 3 specifications for a range of declared versions (as opposed to our previous assumption that only 1.4 would be accepted for PDF/A-1, and 1.7 for PDF/A-2 and 3), or if a choice had been made to accept a range of versions as long as their properties match the specifications.

**Comment by bdoubrov** [comment]
The exact wording of the ISO 19005-1 specification (PDF/A-1) is:
> Neither the version number in the header of a PDF file nor the value of the Version key in the document catalog dictionary shall be used in determining whether a file is in accordance with this part of ISO 19005.

Similar wording exists also in PDF/A-2 and PDF/A-3, where an additional technical requirement added:
> The file header shall begin at byte zero and shall consist of “%PDF-1.n” followed by a single EOL marker, where ‘n’ is a single digit number between 0 (30h) and 7 (37h).  

So, a valid PDF/A-1 file may indeed have version 1.5 as declared in the document header, and nothing prevents a valid PDF/A-2 file from having PDF version 1.4.

**Comment by AFalut** [comment]
Thank you very much !
