### ISSUE TITLE
`GFPDCIDFont` doesn't support `OpenTypeFontProgram`

### ISSUE THREAD

**Issue by zhiayang** [veraPDF/veraPDF-library#1323]
I'm validating with PDF/A-2U, and I've attached a reproduction PDF to the issue as well.

I believe the issue stems from here: https://github.com/veraPDF/veraPDF-validation/blob/189e61231232fde4fd8da454ce77c92911dd216f/validation-model/src/main/java/org/verapdf/gf/model/impl/pd/font/GFPDCIDFont.java#L165

It doesn't appear to support OpenTypeFontProgram (verified by adding some logging and `cidFont.getClass().getName()`. Is this expected?

The structure of the font in the PDF is like this:

- `Type0` font - `NYRTOG+XCharter-Roman`
  - Descendant font: `CIDFontType0`
    - Font descriptor: `FontFile3`
      - `FontFile3`: 
        - Subtype `/OpenType`
        - data: OpenType file with CFF outlines

The validation error is [Specification: ISO 19005-2:2011, Clause: 6.2.11.4.2, Test number: 2](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Parts-2-and-3-rules#rule-621142-2) (which I guess is expected, since the CIDSet will contain CIDs that the font "doesn't have").

PDF: [test.pdf](https://github.com/veraPDF/veraPDF-library/files/11302236/test.pdf)

**Comment by bdoubrov** [comment]
@zhiayang thanks for reporting this issue. It was fixed in the latest dev build 1.23.209. Note that it is not (yet) included into the pre-release build of 1.24
