### ISSUE TITLE
Rule 6.2.2-1: Body content of the inline image is perceived as not defined operators

### ISSUE THREAD

**Issue by payaln** [veraPDF/veraPDF-library#1335]
[pdfa_2TextAndImage_English.pdf](https://github.com/veraPDF/veraPDF-library/files/11398059/pdfa_2TextAndImage_English.pdf)
![image](https://user-images.githubusercontent.com/20249328/236223248-bd61a340-affc-44d2-93b4-317cd2300842.png)

Attached file failed validation. I think validation is failed because the content analyzer treats the inline image body as commands.

**Comment by bdoubrov** [comment]
@payaln thanks a lot for reporting this issue! Indeed, this is related to the issues how veraPDF parses inline images at the moment. We'll improve parsing logic, which will potentially fix this issue.

**Comment by bdoubrov** [comment]
We have improved inline image parsing in the latest dev version of veraPDF. It will be included in the next release. Feel free to verify.

**Comment by MaximPlusov** [comment]
Included into release 1.26
