### ISSUE TITLE
BitsPerComponent value in image objects not checked

### ISSUE THREAD

**Issue by vasterasstad** [veraPDF/veraPDF-library#1344]
According to the PDF Reference, 3rd edition, p. 268, only 1, 2, 4 and 8 are valid values for BitsPerComponent in image objects. The image in [237400.pdf](https://github.com/veraPDF/veraPDF-library/files/11674240/237400.pdf) have a color depth of 16 bits, but the document still validates as a compliant PDF/A-1b in veraPDF 1.22.3. Adobe Preflight 18.6 instead gives an error message claiming that 16-bit images is not permitted in PDF/A-1.

After further testing using other documents, it appears that veraPDF for some reason doesn't check the BitsPerComponent value in image objects.

**Comment by bdoubrov** [comment]
@vasterasstad thanks for reporting this. The scope of PDF/A validation doesn't cover all requirements of PDF specification, only PDF/A ones. But I do agree that correct **BitsPerComponent** is essential for the image rendering. SO, we'll consider adding an extra rule to check this.

**Comment by bdoubrov** [comment]
The checks for **BitsPerComponent** are added in the latest development version.

**Comment by MaximPlusov** [comment]
Included into release 1.26
