### ISSUE TITLE
Validating a PDF/A-3 digitally signed document with a PDF/A-2 flavour doesn't remove the metadata xml from tmp folder.

### ISSUE THREAD

**Issue by SimenBentdal** [veraPDF/veraPDF-library#1346]
We are using verapdf with greenfield to validate a bunch of incoming PDF documents.
If the PDF document has embedded files for instance a digital signature, when validating with 2A/2B/2U it leaves tmp_pdf_file***.pdf in tmp folder. These aren't actually PDF files, but are XML files containing the metadata of the digital signature.

These xml files can be quite big because it sometimes contains the original pdf document aswell as the metadata, so we have had a lot of issues of our tmp catalog going full.

This issue occurs when using the org.verapdf:validation-model:1.22.2 in our project.

**Comment by MaximPlusov** [comment]
Included into release 1.24
