### ISSUE TITLE
Latests artefacts missing on maven central

### ISSUE THREAD

**Issue by dgt-amexio** [veraPDF/veraPDF-library#1361]
Hello,

I am relying on verapdf-model to validate PDF/A documents processed by an in-house application. 
And I am currently facing issues when attempting to update my maven dependency org.verapdf:validation-model to 1.24+ (in order to access the new build relying on jakarta.xml packages.

Seems that org.verapdf packages are no longer published on maven central (latest version available 1.22.2, published in Sept 2022).
Could you kindly check ?

Kind regards
Denis

**Comment by ch-ar-vi** [comment]
+1

**Comment by carlwilson** [comment]
Apologies both. This process seems to have misfired and failed on the publication. I've been chasing this up this morning and I believe that it is fixed, the jakarta artefacts are still here: <https://repo1.maven.org/maven2/org/verapdf/>
