### ISSUE TITLE
Installation on Windows is Broken - No Profiles Available

### ISSUE THREAD

**Issue by kenmcd** [veraPDF/veraPDF-library#1368]
Installation of 1.24.1 on Windows does not appear to work properly.
The Choose Profile button remains grayed-out.
Like this:
![Choose Profile not Available](https://github.com/veraPDF/veraPDF-library/assets/844920/b1030e1f-c8ab-4d54-8c98-63c56fea0a0c)

Same result with either the greenfield or pdfbox installation.

Where should the profiles be located?
It appears they were installed in:
`C:\Users\Ken\verapdf\profiles\veraPDF-validation-profiles-rel-1.24\`

I tried moving the files and folders in that folder to:
`C:\Users\Ken\verapdf\profiles\`
and that had no effect.

So what needs to be done so the application can find the profiles?

**Comment by kenmcd** [comment]
I think I see what is happening.
The PDF QuickStart Guide is very old and shows a different interface - where the second line is where the user selects a profile.
Which is different from the online documentation (when finally found).
Now that second line is for selecting _custom_ profiles **which is not labeled that way** - and the actual profiles selection in hidden in the `PDF flavour:` drop-down list.
No, that is not confusing.
Nice intuitive interface. <roll-eyes>

The Quick Start Guide should be updated (obviously).

Guess I answered my own issue.

**Comment by bdoubrov** [comment]
@kenmcd these are all  very valid comments. We'll reopen this issue and plan:
- updating PDF guide
- making GUI interface a bit more intuitive

**Comment by bdoubrov** [comment]
Booth GUI and the PDF documentation are updated in the latest release 1.26
