### ISSUE TITLE
File with XRef stream claimed to be a valid PDF/A-1b

### ISSUE THREAD

**Issue by THausherr** [veraPDF/veraPDF-library#1375]
The attached file is claimed to be a valid PDF/A-1b in VeraPDF greenfield 1.25.53, just downloaded.
[soknadskvittering.pdf](https://github.com/veraPDF/veraPDF-library/files/12705501/soknadskvittering.pdf)
From my understanding, this is a PDF 1.5 feature and PDF/A-1b is only allowed to have PDF 1.4 features.

And here's the report that another guy got with Adobe for this file:
![grafik](https://github.com/veraPDF/veraPDF-library/assets/6665575/c8dc7fb3-bdd9-4443-ae0d-9c7e99eccecd)

**Comment by bdoubrov** [comment]
During PDF/A-1 validation we parse a document according to PDF 1.4 specification and thus do not recognize compressed object streams as an error. This is why the document is reported to be conforming to PDF/A-1b.

But I do agree this is not fully correct, as for example, just retrieving PDF/A XMP metadata and identifying the PDF/A conformance would already require full support of xref streams. In addition, this is indeed a very valuable information to the user. So, we'll add this extra check in PDF/A-1 validation to the next release and will be in sync with Adobe (and others) on this issue.

**Comment by bdoubrov** [comment]
The latest dev version of veraPDF includes the error on the presence of xref stream in the PDF/A-1 documents.

**Comment by MaximPlusov** [comment]
Included into release 1.26
