### ISSUE TITLE
Auto-install documentation missing?

### ISSUE THREAD

**Issue by jens-st** [veraPDF/veraPDF-library#1378]
I can not find any documentation on github or the project website on CLI arguments for the installer and how to use the `auto-install.xml` for an automated installation.

**Comment by bdoubrov** [comment]
@jens-st thanks for reporting this issue. veraPDF installers are based on IzPack tool (izpack.org). The documentation on IzPack is avaliable at https://izpack.atlassian.net/wiki/spaces/IZPACK/overview?homepageId=491616 . In particular, the use of so-called unattended installation mode is described here: https://izpack.atlassian.net/wiki/spaces/IZPACK/pages/42663940/Installation+Modes

We'll add all this information to the veraPDF documentation.

**Comment by bdoubrov** [comment]
Added missing documentation at the end of https://docs.verapdf.org/install/
