### ISSUE TITLE
Latests artefacts missing on maven central

### ISSUE THREAD

**Issue by dgt-amexio** [veraPDF/veraPDF-library#1401]
Hello,

Linked to original issue #1361, seems that org.verapdf packages are no longer published on maven central (latest version available 1.24.1, published in July 2023).
Could you kindly check and ensure the publishing process is kept active for all new releases ?

Kind regards
Denis

**Comment by bdoubrov** [comment]
The version 1.24.1 is the latest released one. So, no issues here. 

If the development builds are of interest, they are pushed to the Open Preservation artifactory at https://artifactory.openpreservation.org/artifactory/vera-dev/org/verapdf/ .

**Comment by dgt-amexio** [comment]
My bad.
Thanks for clarification
