### ISSUE TITLE
Duplicate MCID in tagged content not identified

### ISSUE THREAD

**Issue by jozefbaranec** [veraPDF/veraPDF-library#1405]
The attached PDF has a content with two objects with MCID 23 separated by an Artifact. PDF/UA validation does not report this issue.
[duplicate-mcid.pdf](https://github.com/veraPDF/veraPDF-library/files/14209814/duplicate-mcid.pdf)

the content:
```
/P <</MCID 23>>BDC
q
BT
/F0 10.5 Tf
1 0 0 1 51.02298 340.273041 Tm
[(S)-2(alo)3(n)]TJ
ET
Q
EMC
/Artifact <</BBox[ 51.023 340.126 84.8225 347.728]/Type/Layout>>BDC
q
BT
/F0 10.5 Tf
1 0 0 1 74.395966 340.273041 Tm
(...)Tj
ET
Q
EMC
/P <</MCID 23>>BDC
q
BT
/F0 10.5 Tf
1 0 0 1 80.80098 340.273041 Tm
<94>Tj
ET
Q
EMC
```

**Comment by bdoubrov** [comment]
Another related issue with broken structure of marked content sequences is when one sequence is contained in another (both having possibly different MCIDs). We'll add this check as well, as we see different implementations handing this violation of the spec in non-consistent ways.

**Comment by bdoubrov** [comment]
Latest dev version adds log warnings in case of duplicated MCIDs or when one marked content sequence is embedded into another.

**Comment by bdoubrov** [comment]
Added to the latest veraPDF release 1.26
