### ISSUE TITLE
JavaScriptEvaluator.getTestEvalResult blocks threads while concurrent validation

### ISSUE THREAD

**Issue by SalomScala** [veraPDF/veraPDF-library#1408]
In our scenario we parallize validations with 20 Threads in a single JVM.
We recognized a big bottleneck in the `JavaScriptEvaluator.getTestEvalResult`-Method, since it is synchronized and only one thread at a time can evaluate its result.

To show the problem I have attached
- a sample java program [veraPDF-PerfTest.zip](https://github.com/veraPDF/veraPDF-library/files/14265259/veraPDF-PerfTest.zip)
- a screenshot of jvisualvm ![JavaScriptEvaluatorBlockingJVisualVm](https://github.com/veraPDF/veraPDF-library/assets/13928125/c4fc75f0-ce65-4e2d-8d47-6db187da0c1d) and
- a threaddump [JavaScriptEvaluatorBlockingThreadDump.txt](https://github.com/veraPDF/veraPDF-library/files/14265192/JavaScriptEvaluatorBlockingThreadDump.txt)

I have tried to fix it locally by adjusting `JavaScriptEvaluator` to use `ThreadLocals`.
I got the following results:

**Testscenario:**
- Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
-  20 parallel threads
- 100 validations per thread

**Result before optimization:**
- 537 seconds in total
- 268 milliseconds per validation
-  4 validations per second

**Result after optimization:**
- 114 seconds in total after optimization
- 57 milliseconds per validation after optimization
- 17 validations per second
 
Thus an validation speed improvement of **325%** in the concurrent case with 20 threads.

As far as I understand the `JavaScriptEvaluator` code, the change should be ok.
All testcases work and the rhino javascript engine can execute scripts in parallel.

But maybe you have further insight, why the synchronisation was used?
It got introduced in https://github.com/veraPDF/veraPDF-library/pull/960 because multithreading was not possible before.
Now I would like to improve the performance for multithreading.

I have created pull request #1409

I welcome any feedback. 
Thanks.

**Comment by bdoubrov** [comment]
Thanks a lot, @SalomScala ! Looks like a great optimization indeed! We have enabled thread-safety of veraPDF only recently and there are still places that need improvements. We'll review and merge your PR if all goes well.

**Comment by MaximPlusov** [comment]
Included into release 1.26
