### ISSUE TITLE
Question: Validation for PDF/A-1 without conformance-level

### ISSUE THREAD

**Issue by Lolf1010** [veraPDF/veraPDF-library#1411]
Hey,
as far as i unterstand it - please correct me if i am wrong - there is a difference between A-1 and A-1a / A-1b. The conformance-levels add additional rules.
Based on the enum `PDFAFlavour` it appears to me that veraPDF can validate A-1a and A-1b, but not "pure" A-1.
Where are planning to use veraPDF as a library in our software.

**Question**
Is it possible to validate just A-1?
Is is maybe possible to only read and use the ValidationProfile for A-1?
Is it maybe possible to identify that a PDF is A-1 but not A-1b (for example) by using`getFailedChecks`?

Thank you.

**Comment by bdoubrov** [comment]
No, PDF/A-1 does not exist without conformance Level (A or B). Note that Level A is a superset of Level B requirements. 

In your internal workflow you can specify `PDF/A-1` as a synonym of either `PDF/A-1a` or `PDF/A-1b` depending on your policies. But on the level of the ISO specification 19005-1 there are only conformance levels: `PDF/A-1a` and `PDF/A-1b`.
