### ISSUE TITLE
"PDF file is not compliant with Validation Profile requirements" in fresh windows install (v1.24.1)

### ISSUE THREAD

**Issue by kjosh** [veraPDF/veraPDF-library#1412]
**What have I done:**

1. run the installation with default options on Windows 11
2. start GUI via verapdf-gui.bat
3. select a PDF with the "Choose PDF" file picker to validate
4. click "Execute"

**What happens?**

The described error message appears after a short time:

![grafik](https://github.com/veraPDF/veraPDF-library/assets/821079/05f07ef8-c784-4e64-89ca-aedefa5bac3e)

**Additional information:**

I've tried a couple different PDFs I had lying around, the behaviour is always the same.

**Comment by bdoubrov** [comment]
Hi @kjosh

You can't expect a random PDF conform to either PDF/A or PDF/UA. So, this is not surprising that you get this message, which says that the PDF doesn't pass validation. To see exactly what goes wrong you can View HTML report.

If you do have a file which you believe is a valid PDF/A (or PDF/UA) document, and if veraPDF still reports this file as invalid, feel free to create a separate issue for this document.

**Comment by kjosh** [comment]
Hey, thanks 🤦, I misunderstood the message and assumed the PDF couldn't be processed at all.
