### ISSUE TITLE
Unknown error in font program (6.3.4-1) and CharSet (6.3.5-2)

### ISSUE THREAD

**Issue by vasterasstad** [veraPDF/veraPDF-library#1419]
When validating [Klippstugan_doc.pdf](https://github.com/veraPDF/veraPDF-library/files/14569356/Klippstugan_doc.pdf) veraPDF 1.26.0-RC1 reports two errors regarding the Type1 font GGMJJK+Verdana,Bold used on the second page:

- 6.3.4-1, that the font program is missing.
- 6.3.5-2, that the CharSet entry in the font descriptor dictionary is missing.

As the font program is indeed present in the file, I interpret the 6.3.4-1 error as there is something wrong with the CFF font program itself. But after much testing I've failed to figure out the source of the issue. The only clue is the veraPDF warning "The Top DICT does not begin with ROS operator", but doesn't this only apply to CID-keyed fonts?

I've encountered the 6.3.5-2 error many times in the past. In my experience it's usually caused by an invalid character name, like `;#23#23#23` and can be fixed by changing the name in CharSet and in the font program. In this particular instance however, I'm unable to find something wrong with the CharSet.

Am I missing some issues with this font program? Adobe Preflight (latest version) as well as several online validators reports the file as compliant with PDF/A-1b.

**Comment by MaximPlusov** [comment]
@vasterasstad thanks for reporting this issue. It was fixed in the latest dev build [1.25.225](https://software.verapdf.org/develop/1.25)
