### ISSUE TITLE
Question regarding tmp-file

### ISSUE THREAD

**Issue by Lolf1010** [veraPDF/veraPDF-library#1420]
Hey,
if i understand it correctly the Inputstream that is given to `Parser.createParser` is written into a temp-file and the library then reads from that file. Meaning that if i would parse a 1 MB InputStream a 1 MB temp-file would be temporarily exist.

I think the answer is no but just to make sure: 

- Is it possible to change the directory of the tmp-file without changing the java-property (java.io.tmpdir) or overwriting the class code?
- Is there an alternative to the tmp-file (excluding small pdf-files which are kept in-memory it appears) ?

Thank you

**Update:**
It appears that the classes are signed which means that its not easily possible to overwrite the `InternalInputStream` to change the directory. So i guess the only option would be to change the java-property.

**Comment by bdoubrov** [comment]
Normally small cached data is not written into tmp files and kept in memory. "Small" means `< SeekableInputStream.MAX_BUFFER_SIZE`. This is a private constant, which we can expose as one of the veraPDF configuration parameters.

Temporary files are always created by standard Java call `File.createTempFile(String prefix, String suffix);` . Again, we can use another version of this method `File.createTempFile(String prefix, String suffix, File directory);` and expose `directory` as yet another config parameter.

Would this work for your purposes?
