### ISSUE TITLE
Inaccurate Validation Failure of PDF/A-2b document

### ISSUE THREAD

**Issue by computerguycj** [veraPDF/veraPDF-library#1421]
I've created several PDF/A-2b files using DevExpress' PDF Document API, but each one fails validation using veraPDF. I've attached the failure report, an example of one of the files I created, and a successful validation result printout from Adobe's Preflight tool. The font is embedded within the file, so it shouldn't fail validation. 

![veraPDF Validation Report Embedded Font Failure](https://github.com/veraPDF/veraPDF-library/assets/7907637/6bd2ea26-c0b5-4aac-a891-93df72560c2f)

[veraPDF Validation Report.zip](https://github.com/veraPDF/veraPDF-library/files/14576029/veraPDF.Validation.Report.zip)

![Adobe Pro Preflight Success Result (provided by DevExpress Support)](https://github.com/veraPDF/veraPDF-library/assets/7907637/0ade9c41-0ff1-4209-8726-c23f52f409be)

[devexpress Default a2b.pdf](https://github.com/veraPDF/veraPDF-library/files/14575966/devexpress.Default.a2b.pdf)

Can you please provide details of why this fails validation?

**Comment by computerguycj** [comment]
Thanks, MaximPlusov! I've verified it succeeds on my end as well!

**Comment by MaximPlusov** [comment]
Included into release 1.26
