### ISSUE TITLE
JavaDocs or any code documentation.

### ISSUE THREAD

**Issue by Samyssmile** [veraPDF/veraPDF-library#1457]
In one of you code examples I found this.

`Foundries.defaultInstance().createValidator(parser.getFlavour(), false);`

I try to figure it out what boolean false is meaning here. Is any documentation available?

**Comment by MaximPlusov** [comment]
hi @Samyssmile You can find the documentation of this method [here](https://javadoc.io/doc/org.verapdf/validation-model/latest/org/verapdf/pdfa/AbstractFoundry.html#createValidator(org.verapdf.pdfa.flavours.PDFAFlavour,boolean)).
