### ISSUE TITLE
Documentation of "javax vs jakarta" is not complete

### ISSUE THREAD

**Issue by cristalp** [veraPDF/veraPDF-library#1463]
I'm using veraPDF within a Quarkus project. During build time, everything went smoothly, but then as soon as I built the image and ran it, I got `java.lang.NoClassDefFoundError: javax/activation/DataSource`.

[MaximPlusov](https://stackoverflow.com/users/20401449/maximplusov) thankfully pointed me to ["javax vs jakarta"](https://docs.verapdf.org/develop/#javax-vs-jakarta) and I tried this, but got the same result.

By chance, however, I noticed that using `org.verapdf:validation-model-jakarta` was not enough, since I was still using `org.verapdf:core`. I have to use `org.verapdf:core-jakarta`. With that dependency, everything runs smoothly.

Could you please add this information to your documentation? I'm sure it would help the new developer who encounters the problem.

Thanks a lot for this great library!

**Comment by cristalp** [comment]
Thanks for the information! Well, in my case, we check in the build that all dependencies that are required are also stated in the Maven POM. This helps keep the dependencies tidy. We use the [Maven Dependency plugin](https://maven.apache.org/plugins/maven-dependency-plugin/analyze-mojo.html) for that.

**Comment by nikitakovaliov92** [comment]
@cristalp The documentation has been updated: https://docs.verapdf.org/develop/#javax-vs-jakarta
