### ISSUE TITLE
Cannot read metadata during PDF/A validation

### ISSUE THREAD

**Issue by achelos-enn** [veraPDF/veraPDF-library#1469]
We tried to validate that a PDF is conformant to PDF/A, but did not succeed. We used a document that can be validated in the following online validator: https://www.pdfforge.org/online/en/validate-pdfa I attached the document to this issue: [helloworld.pdf](https://github.com/user-attachments/files/16438948/helloworld.pdf)

We got a log message indicating that the meta data of the PDF document could not be parsed:

> Juli 31, 2024 10:57:52 AM org.verapdf.model.impl.pb.pd.PBoxPDMetadata getXMPPackage
INFORMATION: Problems with parsing metadata. COSStream has been closed and cannot be read. Perhaps its enclosing PDDocument has been closed?

We used the following code:
```java
@Test
public void test() throws Exception {
    PdfBoxFoundryProvider.initialise();
    
    try (InputStream inputStream = PdfCheckerTest.class.getResourceAsStream("/helloworld.pdf")) {
	    try (VeraPDFFoundry veraPDFFoundry = Foundries.defaultInstance()) {
		    try (PDFAParser parser = veraPDFFoundry.createParser(inputStream, PDFAFlavour.PDFA_3_A)) {
			    PDFAValidator validator = veraPDFFoundry.createValidator(PDFAFlavour.PDFA_3_A, false);
			    ValidationResult result = validator.validate(parser);
			    System.out.println("Is PDF/A-3a compliant: " + result.isCompliant());
		    }
	    }
    }
}
```

The validationresult showed the following failed tests:
![grafik](https://github.com/user-attachments/assets/c2da1996-5068-43ee-ac06-e7eeddbe2b28)

Used veraPDF-pdfbox-validation versions: 1.27.27, 1.26.1, 1.24.2 (all versions showed the same behavior)

We tested a few different PDF files and it seems like the meta data could never be read correctly.

Does anybody know if we are doing something wrong? Or could this be a bug in the veraPDF library?

**Comment by MaximPlusov** [comment]
@achelos-enn This is bug of PDFBox version and we suggest switching to Greenfield version, which will resolve the issue. The support for PDFBox version will stop after the next release 1.28.

**Comment by achelos-enn** [comment]
Ok, switching to Greenfield solved the issue for us. Thank you!
