### ISSUE TITLE
Version 1.26.2 is not in Maven Central

### ISSUE THREAD

**Issue by hypfvieh** [veraPDF/veraPDF-library#1480]
Hi,

because of the bug fixed in #1415 we get some reporting of our dependency analyzer tool regarding vulnerabilities. 
In the bug report it says the this is fixed in the latest version (1.26.2 I guess). 

I can see the release and tag here on Github, but there is no new version in Maven Central.
This makes updating inconvenience. 

Is it possible to get this version uploaded to Maven Central too?

**Comment by MaximPlusov** [comment]
The latest versions of artifacts seem to be correct on maven. It is 1.26.1 except for veraPDF Application, which is 1.26.2 due to some technical reasons related to Jenkins failure.

In any case the correct latest maven version is 1.26+ for all veraPDF dependencies.

**Comment by hypfvieh** [comment]
Ok... 
Anyway, I guess that the report vulnerability is a false positive then.

Sorry for the noise.
