### ISSUE TITLE
Validation of documents that are not strongly structured

### ISSUE THREAD

**Issue by Intelligent2013** [veraPDF/veraPDF-library#1482]
In https://github.com/veraPDF/veraPDF-library/blob/integration/core/src/main/resources/org/verapdf/pdfa/validation/PDFUA-1.xml there is a rule `For documents that are not strongly structured, as described in`:
```xml
<rule object="SEHn" tags="structure,heading">
	<id specification="ISO_14289_1" clause="7.4.2" testNumber="1"/>
	<description>For documents that are not strongly structured, as described in ISO 32000-1:2008, 14.8.4.3.5, heading tags shall be used as follows: (*) If any heading tags are used, H1 shall be the first. (*) A document may use more than one instance of any specific tag level. For example, a tag level may be repeated if document content requires it. (*) If document semantics require a descending sequence of headers, such a sequence shall proceed in strict numerical order and shall not skip an intervening heading level. (*) A document may increment its heading sequence without restarting at H1 if document semantics require it</description>
	<test>hasCorrectNestingLevel == true</test>
	<error>
		<message>Heading level %1 is skipped in a descending sequence of header levels</message>
		<arguments>
			<argument>nestingLevel - 1</argument>
		</arguments>
	</error>
	<references>
		<reference specification="ISO 32000-1:2008" clause="14.8.4.3.5"/>
	</references>
</rule>
```

From ISO-32000-1, 14.8.4.3.5:

> The block-level structure may follow one of two principal paradigms:
> 
> - Strongly structured. The grouping elements nest to as many levels as necessary to reflect the organization of the material into articles, sections, subsections, and so on. At each level, the children of the grouping element should consist of a heading (H), one or more paragraphs (P) for content at that level, and perhaps one or more additional grouping elements for nested subsections.
> - Weakly structured. The document is relatively flat, having perhaps only one or two levels of grouping elements, with all the headings, paragraphs, and other BLSEs as their immediate children. In this case, the organization of the material is not reflected in the logical structure; however, it may be expressed by the use of headings with specific levels (H1–H6).

Question: regarding the phrase `For documents that are not strongly structured`, how/where does the veraPDF check that document isn't strongly structured?
Thanks.

**Comment by bdoubrov** [comment]
@Intelligent2013 thanks for bringing this up. 

As soon as veraPDF sees any of H1-H7 tags, it assumes that the document is not strongly structured and starts checking the PDF/UA-1, 7.4.2 requirements (mostly cited in the error message). 

I do agree this is not clearly worded, but is implied by ISO-32000-1, 14.8.4.3.5 you cite.

**Comment by Intelligent2013** [comment]
@bdoubrov thank you for the answer!
