### ISSUE TITLE
Question: how to extract  signatures with the API

### ISSUE THREAD

**Issue by Chlara** [veraPDF/veraPDF-library#1491]
Hi 
In the example integration from the veraPDF Processor API the signatures are not extracted.
https://docs.verapdf.org/develop/processor/
Can you give me an example how signatures can be extracted with the API?
Thanks, Chlara

**Comment by MaximPlusov** [comment]
Hi @Chlara You should add line `featureConfig.getEnabledFeatures().add(FeatureObjectType.SIGNATURE);` after creating `featureConfig`.
