### ISSUE TITLE
VeraPDF's core 1.26.2 is not on Maven Central

### ISSUE THREAD

**Issue by bjoernmartin** [veraPDF/veraPDF-library#1494]
On Dec 6, VeraPDF's `validation-model` was released with version `1.26.2` to Maven Central, see https://mvnrepository.com/artifact/org.verapdf/validation-model. However, one of its dependencies, `core`, was not, see https://mvnrepository.com/artifact/org.verapdf/core. 

This seems to be an error state, as there is a tag [1.26.2](https://github.com/veraPDF/veraPDF-library/releases/tag/v1.26.2) within this repo and thus for `core` as well, dated Dec 4. Confusingly, there is a release [1.26.1](https://github.com/veraPDF/veraPDF-library/releases/tag/v1.26.1) which has `1.26.2` in its title. 

Maybe something went wrong during publishment?

**Comment by bdoubrov** [comment]
@bjoernmartin thanks for reporting this. We are looking into this right now

**Comment by MaximPlusov** [comment]
Now `core` version `1.26.2` available on Maven Central.

**Comment by bjoernmartin** [comment]
Thanks for the quick fix! 👍
