### ISSUE TITLE
GUI Installer doesn't close after installation is over

### ISSUE THREAD

**Issue by DmitryRemezow** [veraPDF/veraPDF-library#398]
1. After installation GUI installer closes, but after it opens on more time starting from beginning

2. The same problem is reproduced with "Quit" button. If we push "Quit" button at first step or second step, GUI installer closes, but after it opens on more time starting from beginning

**Comment by carlwilson** [comment]
Could you please indicate the platform / operating system you were testing on please?

**Comment by DmitryRemezow** [comment]
Windows 7, version 6.1, 7601:Service Pack 1
Java version 1.8.0.66 / JRE build 1.8.0.66-b18
