### ISSUE TITLE
CLI: --profile argument

### ISSUE THREAD

**Issue by DmitryRemezow** [veraPDF/veraPDF-library#399]
Profile selection works only for predefined profiles.

A. verapdf.bat -p "path to profile\PDFA-2B.xml" "path to pdf/somename.pdf"

Validation with -p argument, containing full path to profile (PDFA-2B.xml) gives incorrect result : 

<validationResult flavour="NO_FLAVOUR" totalAssertions="0" isCompliant="true">

B. verapdf.bat -p 2b "path to pdf/somename.pdf"

But works fine with predefined profile for the same pdf file

OS: Windows 7, version 6.1, 7601:Service Pack 1
JM: Java version 1.8.0.66 / JRE build 1.8.0.66-b18

**Comment by carlwilson** [comment]
I believe this is fixed by #409 @DmitryRemezow to confirm.

**Comment by DmitryRemezow** [comment]
This issue was solved in 0.7.48 version
