### ISSUE TITLE
CLI application outputs log4j configuration errors. 

### ISSUE THREAD

**Issue by carlwilson** [veraPDF/veraPDF-library#447]
The startup error reads:

    $ .\verapdf
    log4j:ERROR Could not find value for key log4j.appender.file
    log4j:ERROR Could not instantiate appender named "file".

It's possibly caused by misconfiguration of PDF box log4j.

**Comment by timurkamalov** [comment]
https://github.com/veraPDF/veraPDF-library/pull/467
