### ISSUE TITLE
Enhancements to GUI front end.

### ISSUE THREAD

**Issue by carlwilson** [veraPDF/veraPDF-library#452]
These suggestions are taken from the KEEPS technical report:

- [x] The “Validate” button should be renamed to something like “Run”, “Execute” or just “Go”. When we choose the option “Features”, the app is not really “Validating”, but doing a different operation.
- [x] Move the “Generate reports” line one up in the interface so that it stands above the “Validate” button (move the “Validate” button down as well). This is because we need to choose a “Generate reports” option before starting the processing.
- [x] Consider renaming “Generate reports” to “Action” or “Report type”

**Comment by BezrukovM** [comment]
Points 1-3 are corrected in https://github.com/veraPDF/veraPDF-library/pull/461. Point 4 needs additional discussing.

**Comment by timurkamalov** [comment]
Closed.
