### ISSUE TITLE
Possible false positive in veraPDF when testing for CIDSystemInfo entry in CIDFont dictionary

### ISSUE THREAD

**Issue by a7k** [veraPDF/veraPDF-library#558]
http://bugs.ghostscript.com/show_bug.cgi?id=696797#c1
https://0x0.st/qpS.html

The validation test detailed in https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Parts-2-and-3-rules#rule-62113-1 could  lead to false positives.
I can't attach a PDF to test this issue directly on this bug tracker.

**Comment by bdoubrov** [comment]
I can't access the attachments at bugs.ghostscript.com without authorization. Is there any way to share a test file that reproduces the issue?

**Comment by a7k** [comment]
I could send a copy of the file by mail, in that case I'd ask if admin@verapdf.org is a correct address for this purpose. I've been asked not to make the test files publicly available.

**Comment by bdoubrov** [comment]
If you could send test files to boris.doubrov@duallab.com, it would really be great. Thanks!

**Comment by a7k** [comment]
I've sent you an e-mail, anyway I've just noticed that the issue can be reproduced converting a LibreOffice PDFA/1-a to PDFA/2-b via ghostscript, hence I'll link a sample PDF here as well.
https://0x0.st/bwh.pdf

**Comment by bdoubrov** [comment]
Apparently, the issue is already fixed in the integration branch. It will be included into the coming VeraPDF release.

**Comment by a7k** [comment]
I see. I've tried to validate with development snapshots/integration branch last wee but the outcome was the same.
I've now grabbed again the latest snapshot and I can confirm that this issue is fixed.
Thank you for having looked at it
