### ISSUE TITLE
validation throws an exception

### ISSUE THREAD

**Issue by vandenoever** [veraPDF/veraPDF-library#564]
Validating the attached (invalid) file throws an exception in verapdf gui 0.16.2.

[resulticbe852e3-c9ed-4668-998b-203d2a354a06.pdf](https://github.com/veraPDF/veraPDF-library/files/295511/resulticbe852e3-c9ed-4668-998b-203d2a354a06.pdf)

**Comment by bdoubrov** [comment]
The document has broken xref table. This causes an exception reported by the application. Do you expect a different behaviour in case when the code PDF syntax is broken?

**Comment by vandenoever** [comment]
I would still expect to be able to get a validation report instead of an error. Even when trying to validate a text file or png file as pdf, I'd expect a normal report instead of an error or exception.

**Comment by BezrukovM** [comment]
Fixed in https://github.com/veraPDF/veraPDF-apps/pull/46

**Comment by bdoubrov** [comment]
Included into 0.20 release
