### ISSUE TITLE
Validation via GUI renders mostly blank XML - no log messages to support any errors

### ISSUE THREAD

**Issue by ross-spencer** [veraPDF/veraPDF-library#583]
Output:

		<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
		<report xmlns="http://www.verapdf.org/MachineReadableReport" creationDate="2016-08-16T14:52:51.914+12:00" processingTime="00:00:02.225">
			<itemDetails size="1443616">
				<name>\\arcwn-fp02.archives.net\homefolders$\spencero\Desktop\224727.pdf\224727.pdf</name>
			</itemDetails>
			<pdfFeaturesReport/>
		</report>

The file comes from Govdocs Selected and is attached. 

[224727.pdf](https://github.com/veraPDF/veraPDF-library/files/419385/224727.pdf)

**Comment by timurkamalov** [comment]
Hello

I've tried validating attached file on my machine and got correct report (attached). Could you please provide more details about your environment? I'm using :

- Windows 10
- verapdf version 0.21.3
- java version 1.7.0_79

[xmlReport.xml.txt](https://github.com/veraPDF/veraPDF-library/files/420180/xmlReport.xml.txt)

**Comment by ross-spencer** [comment]
Hi, 

I apologize for not providing this information before. I haven't the environment available to recreate this right now, so happy to close this as just an anomaly. 

Ross
