### ISSUE TITLE
Execution exception in processing: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by Artemyj** [veraPDF/veraPDF-library#585]
1. Open VeraPDF Conformance Checker
2. Choose File 
[159759_(PDFA).pdf](https://github.com/veraPDF/veraPDF-library/files/446611/159759_.PDFA.pdf)
3. Set Program options as in screenshot
4. Press Execute

![image](https://cloud.githubusercontent.com/assets/7796919/18119797/14306292-6f65-11e6-83b1-b7929fddcb75.png)

**Comment by timurkamalov** [comment]
Fixed in 0.21.9 version.
