### ISSUE TITLE
JVM startup seems to be included in first file's processingTime

### ISSUE THREAD

**Issue by david-russo** [veraPDF/veraPDF-library#595]
When processing files in batches, the first file seems to count the JVM's loading time in its `processingTime` attribute. Any files processed afterwards generally report significantly shorter times. Below are the results from a sample batch of five files, three of which were identical.

```
<report ... processingTime="00:00:02.128">  <---
<report ... processingTime="00:00:00.700">     ¦
<report ... processingTime="00:00:00.734">  <--- SAME FILE
<report ... processingTime="00:00:00.607">     ¦
<report ... processingTime="00:00:00.715">  <---
```

Ideally the times would be comparable between all files. As it stands, the loading and processing times can't be separated for the first file, and so can't be accurately compared with the others' times.

**Comment by bdoubrov** [comment]
JVM loading time is excluded from processing time. But we compile validation resources (JavaScript conditions) only when we encounter them the first time. This indeed results in a bit longer processing time for the very first job.

**Comment by carlwilson** [comment]
Hi @david-russo, I believe that this is definitely no longer the case, the batch start and finish times are set by the processor and are accurate.

**Comment by david-russo** [comment]
Hi @carlwilson, this issue isn't about the total batch processing time, but the individual processing times of files in a batch. Testing with either version of 1.0.6 still generates the discrepancy mentioned above.

Would it be possible to compile the validation resources before starting the clock on each job? Or have them pre-compiled?

**Comment by carlwilson** [comment]
Hi @david-russo, we'll open this again and look into pre-compiling the Javascript resources before the first job timer starts.

**Comment by carlwilson** [comment]
There's been no action on this and it doesn't feel like a serious / live issue so we're closing.
