### ISSUE TITLE
Crash on running feature extraction

### ISSUE THREAD

**Issue by prwheatley** [veraPDF/veraPDF-library#643]
Here are four files that cause a crash when running the feature extractor of veraPDF (0.26.16), either GUI or CLI:
http://web.archive.org/web/20071009190733/http://www.thpct.nhs.uk/uploads/Trust%20Board%20Papers/01_07%20Papers.pdf
http://web.archive.org/web/20080702075816/http://news.bbc.co.uk/2/shared/bsp/hi/pdfs/14_01_08_lanarkshire.pdf
http://web.archive.org/web/20080702075821/http://news.bbc.co.uk/2/shared/bsp/hi/pdfs/14_01_08_ayrshire.pdf
http://web.archive.org/web/20080412102905/http://www.plymouth.gov.uk/260308lacmfinalsubmission.pdf

The first three give an Execution Exception, the last gives "Some error in saving the HTML Report ..."

I can provide further examples if needed.

**Comment by bdoubrov** [comment]
Fixed for the first three files. The last file seems to be OK. Will double check this with the latest dev version.

**Comment by shem-sergey** [comment]
Problem was fixed in https://github.com/veraPDF/veraPDF-pdfbox-validation/pull/121, in latest dev version all files are processed without exceptions.

**Comment by prwheatley** [comment]
No problems with the rest of my test set now - thanks guys!
