### ISSUE TITLE
Validation error with a scanned document

### ISSUE THREAD

**Issue by tomko80** [veraPDF/veraPDF-library#671]
I recently received a scanned document that won't validate. V24 gave the error "unexpected error" and the latest v28 says "not valid". The command prompt shows the attached exceptions.

I can't provide the file, but is there an switch to turn on  for more detailed logging?
[verapdf_error.txt](https://github.com/veraPDF/veraPDF-library/files/673762/verapdf_error.txt)

Adobe Acrobat declares the file to be PDF/A.

**Comment by bdoubrov** [comment]
I see that the crash log saying that apparently there is an issue with one of the embedded fonts of type CIDFont2. 

Could you please provide also the validation report in HTML format for version V28?

**Comment by tomko80** [comment]
Here is the report. It does not reveal that much...
[htmlReport.zip](https://github.com/veraPDF/veraPDF-library/files/674264/htmlReport.zip)

**Comment by tomko80** [comment]
Any ideas?

**Comment by bdoubrov** [comment]
I clearlysee that one of the embedded fonts TrueType fonts (CIDFontType2 in terms of PDF) is causing issues for our low level font parser.

Ideally, we need to have a look at your file to analyse this. So,I wonder if you could send this file to me directly by email (boris.doubrov@duallab.com) to check it?

If this is impossible, we would then ask you to extract all embedded TrueType fonts from the document and send them to us. This is more complex, by feasible with some assisance from your side. To start with, please enable fonts in the features report (see https://github.com/veraPDF/veraPDF-policy-docs/wiki for information how to do this), execute just feature report generation and send me back the generated XML report. I hope it would contain the list of all fonts embedded into your document. We'll then try to guess which ones might be the reason of the issue.

**Comment by tomko80** [comment]
I have asked to get a document I can send you. In the mean while, see the attached XML.
I tried enablling every checkbox in the feature config.

[xmlReport.zip](https://github.com/veraPDF/veraPDF-library/files/677058/xmlReport.zip)
![features](https://cloud.githubusercontent.com/assets/4721854/21543916/66fa84fe-cdd3-11e6-8d6c-b4132bc084ab.PNG)

**Comment by bdoubrov** [comment]
Well, unfortunately, the report says the same: the file is broken according to our PDF parser. This might the issue in our code. But I am afriad, we can't proceed without the file in question.

**Comment by tomko80** [comment]
Here is a file to look at. The atatched file produces also an error, not the same one though. I was told the attached file was not scanned but generated using the same pdf archiving tool as the initial one I have.
[Testfile_1.pdf](https://github.com/veraPDF/veraPDF-library/files/678603/Testfile_1.pdf)

**Comment by bdoubrov** [comment]
Yes, I see that veraPDF is not able to decode the OutputIntent ICC profile, which results in several color-related validation errors. We'll check this in more detail.

**Comment by bdoubrov** [comment]
Looks like only the null-pointer exception was fixed. The latest version still reports validation errors related to the ICC output profile.

**Comment by bdoubrov** [comment]
There is a checksum error when decoding output ICC profile (FLATE encoded). To fix this issue we need to catch and ignore the internal Java exception in the Flate implementation.

**Comment by bdoubrov** [comment]
Fixed in the latest development version [1.17.45](https://software.verapdf.org/develop/1.17)
