### ISSUE TITLE
PDFBOX and Greenfield version - different outputs

### ISSUE THREAD

**Issue by EPavlaskova** [veraPDF/veraPDF-library#674]
There is a difference in behavior of PDFBOX and Greenfield version of veraPDF 1.0.3. PDFBOX  validates file MS2016.pdf as a PDF/A 3a without any further problems. Greenfield version finds a problem with clause _6.2.11.7 - The Unicode values specified in the ToUnicode CMap shall all be greater than zero (0), but not equal to either U+FEFF or U+FFFE_
[MS2016.pdf](https://github.com/veraPDF/veraPDF-library/files/701304/MS2016.pdf)
The file was made by MS Word 2016, but same problem appears with files exported from Word 2010 (PDF/A 1a). 
I am not sure, if it is a major issue, but MS Office is our main source of PDF/A files, so it kind of bothers me.
Sorry, if it is not relevant.

**Comment by BezrukovM** [comment]
fixed by https://github.com/veraPDF/veraPDF-parser/pull/175
