### ISSUE TITLE
release .zip signature

### ISSUE THREAD

**Issue by randomice42** [veraPDF/veraPDF-library#675]
Hi, 
your download directory features the *.asc signature for the files. That's great.
Yet, your long gpg key ID (1C124847) is neither visibly published on the verapdf.org website, nor on regular keyservers (e.g. sks-keyservers, pgpkeys.mit.edu). So, it is pretty difficult to actually check them. 

To make use of it: 
1. publish the long gpg key ID on the website and github home. 
2. for linux, add a line to "gpg --verify verapdf-installer.zip.asc" in the install instructions.[1] 

[1] https://github.com/veraPDF/veraPDF-library#linux-full-command-line-download-and-install

**Comment by carlwilson** [comment]
Keys now published to keyserver, documentation to come for release next week

**Comment by carlwilson** [comment]
These are now published and instructions are on the new download site, this can be closed.
