### ISSUE TITLE
PDF/A valid in Adobe Acrobat but not in VeraPDF

### ISSUE THREAD

**Issue by stanislav-rogozhin** [veraPDF/veraPDF-library#676]
Attached document validates fine in Adobe Acrobat Preflight, but VeraPDF (both PDFBox and Greenfield versions) reports an error:
All properties specified in XMP form shall use either the predefined schemas defined in the XMP Specification, ISO 19005-1 or this part of ISO 19005, or any extension schemas that comply with 6.6.2.3.2.

Both reports attached
[pdfa_11-1257-1399811.pdf](https://github.com/veraPDF/veraPDF-library/files/702024/pdfa_11-1257-1399811.pdf)
[validation_reports.zip](https://github.com/veraPDF/veraPDF-library/files/702027/validation_reports.zip)

**Comment by bdoubrov** [comment]
I believe veraPDF is correctly reporting validation errors in this case. The XMP metadata  packages in question are attached to two /Part structure elements (indirect objects 206 and 248) anddo indeed contain non-standard properties, defined neither in XMP specification nor in any Extension Schemas in the document.

If these properties are manually copied to the document level XMP metadata, Adobe does also report them as invalid. I'm not sure why these properties are not reported asinvalid, if they sit in another XMP package.

The PDF/A-2 specification is very clear about this. 

ISO 19005-2, 6.6.2 Metadata streams - 6.6.2.1 General: 
> The Catalog dictionary of a conforming file shall contain the Metadata key whose value is a metadata stream as defined in ISO 32000-1:2008, 14.3.2.<br/> **In addition, all metadata streams present in the PDF shall conform to the XMP Specification.**

and then in 6.6.2.3 Schemas - 6.6.2.3.1 General:
> All properties specified in XMP form shall use either the predefined schemas defined in the XMP Specification, ISO 19005-1 or this part of ISO 19005, or any extension schemas that comply with 6.6.2.3.2.
