### ISSUE TITLE
Different reports when using Greenfield and PDFBox

### ISSUE THREAD

**Issue by nunovieira220** [veraPDF/veraPDF-library#678]
When validating using Greenfield and PDFBox versions (v1.0.5), the final report shows different validation information. We tested with some files, for example, [file](https://publications.europa.eu/pt/publication-detail/-/publication/1d77ce47-3dfa-4fb9-ac27-223975ce3795) and, in this case, it returned the following reports.

[PDFBox report](https://github.com/veraPDF/veraPDF-library/files/704139/htmlReportWithBox.html.txt)
[Greenfield report](https://github.com/veraPDF/veraPDF-library/files/704140/htmlReportWithGF.html.txt)

**Comment by shem-sergey** [comment]
Fixed in https://github.com/veraPDF/veraPDF-parser/pull/177.

**Comment by blackbeam** [comment]
There is another document with different reports (specification="ISO 19005-1:2005" clause="6.3.4" testNumber="1") using latest verapdf-1.13.11. (I'll send link to the document to @bdoubrov).
