### ISSUE TITLE
verapdf-1.0-GF-20170112.zip # Cannot build the source code offline.

### ISSUE THREAD

**Issue by beyo-ra** [veraPDF/veraPDF-library#681]
Attempt to build from source on ArchLinux in Virtualbox without Internet connection.
* http://preforma-project.eu/verapdf-download.html
  BUILD ENVIRONMENT (All releases) Linux
  Greenfield version (all platforms): source code

```
# mvn -v
# java -version
```
> Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
> Maven home: ~/verapdf_linux/buildenv/apache-maven-3.3.9
> Java version: 1.7.0_79, vendor: Oracle Corporation
> Java home: ~/verapdf_linux/buildenv/jdk1.7.0_79/jre
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "4.8.13-1-arch", arch: "amd64", family: "unix"

`#  cd ~/verapdf-1.0-GF-20170112 # containing: pom.xml src`

`# mvn clean install -P clone-test-resources`

Also tried

`# mvn compile`

The log (from `# mvn compile`)

> [INFO] Scanning for projects...
> Downloading: http://artifactory.openpreservation.org/artifactory/vera-dev/org/verapdf/verapdf-parent/1.0.17/verapdf-parent-1.0.17.pom
>
> Downloading: https://repo.maven.apache.org/maven2/org/verapdf/verapdf-parent/1.0.17/verapdf-parent-1.0.17.pom
> 
> [ERROR] [ERROR] Some problems were encountered while processing the POMs:
> [FATAL] Non-resolvable parent POM for org.verapdf:verapdf:1.0.0-SNAPSHOT: Could not transfer artifact org.verapdf:verapdf-parent:pom:1.0.17 from/to vera-dev (http://artifactory.openpreservation.org/artifactory/vera-dev): artifactory.openpreservation.org: Name or service not known and 'parent.relativePath' points at wrong local POM @ line 4, column 11
>  @ 
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]   
> [ERROR]   The project org.verapdf:verapdf:1.0.0-SNAPSHOT (~/verapdf_linux/verapdf-1.0-GF-20170112/pom.xml) has 1 error
> [ERROR]     Non-resolvable parent POM for org.verapdf:verapdf:1.0.0-SNAPSHOT: Could not transfer artifact org.verapdf:verapdf-parent:pom:1.0.17 from/to vera-dev (http://artifactory.openpreservation.org/artifactory/vera-dev): artifactory.openpreservation.org: Name or service not known and 'parent.relativePath' points at wrong local POM @ line 4, column 11: Unknown host artifactory.openpreservation.org: Name or service not known -> [Help 2]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
> [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by beyo-ra** [comment]
Tried the _PDFBox version (all platforms): source code_ with the same error.

**Comment by carlwilson** [comment]
Closing this as working now.

**Comment by phamels** [comment]
Doesn't work ... again. error 502 on http://artifactory.openpreservation.org/artifactory/vera-dev

**Comment by carlwilson** [comment]
Sorry our artifactory server has gone down, am looking at it now and should be back shortly.

**Comment by carlwilson** [comment]
Back now, all should be well.
