### ISSUE TITLE
veraPDF-core-functionality.tar.gz # feedback # Where is the Implementation and Policy Checker?

### ISSUE THREAD

**Issue by beyo-ra** [veraPDF/veraPDF-library#694]
Successfully built "veraPDF Complete Source Base" (20170125) with some warnings; see debug log.

**OracleJDK**
`[archlinux]# mvn -X -s "$build_DIR/maven.conf.xml" clean install >` [mavendbg_oraclejdk.txt](https://github.com/veraPDF/veraPDF-library/files/730570/mavendbg_oraclejdk.txt)

**Azul OpenJDK**
`[archlinux]# mvn -X -s "$build_DIR/maven.conf.xml" clean install >` [mavendbg_openjdk.txt](https://github.com/veraPDF/veraPDF-library/files/730571/mavendbg_openjdk.txt)

Where the content of `maven.conf.xml` changes
```
<settings ...>
  <localRepository>/root/verapdf/build/repository/</localRepository>
  <offline>true</offline>
</settings>
```

**Now,**

- where is the Implementation and Policy Checker? Or better yet, how do I run them?

`[archlinux]# java -jar veraPDF-core-functionality/veraPDF-library/core/target/core-1.0.0.jar`
(by core functionality I assume the core functionalities, that is, the Implementation and Policy Checker)

> no main manifest attribute, in ...

- and how would I go about to only compile the Implementation and Policy Checker?

**Comment by carlwilson** [comment]
Hi @beyo-ra , regarding the use of `core`. It's a little more complicated than that as the `veraPDF-library/core` project only defines the API for the parser, and it in turn references the validation model API that is defined in `veraPDF-model`. There are 2 implementations for these APIs, the `veraPDF-validation` is the greenfield version. The `core` project can never include these as it introduces a circular dependency between the API definitions and the implementation classes.

We've not considered the policy checker as a separate element before as it's so tightly tied to the results of the implementation checker. It can be invoked "stand alone" from the CLI but isn't a separate app. Would an alternative package that just presents the CLI as a single app with the appropriate scripts to run it satisfy this requirement? This would still be in the `veraPDF-apps` project as this is in line with the module architecture.

**Comment by beyo-ra** [comment]
1. The CDP (Core Distribution Package) request is primarily intended to ensure that the Implementation and Policy Checker, and all their  dependencies, are licensed as GPLv3++ and MPLv2++.  Of importance is the separation of core components from other subsidiary components, which can contain other open source licenses as long as they are compatible with GPLv3++ and MPLv2++.

By providing the source code only to the Implementation and Policy Checker, the licensing requirements could be more easily verified. Together with the build environment and compilation of the source code, a functioning program adherent to the licensing requirements could be confirmed.

In other words, a more "focused package" avoids any confusions or misunderstandings regarding other code present in the CDP.

2. In addition to the licensing requirements, in your case, a main concern has been the missing Policy Checker.

Regarding the code architecture/organization.
>  It can be invoked "stand alone" from the CLI but isn't a separate app. 

I interpret this as: the Implementation and Policy Checker are not independent executables.

I can only speak for myself, as long as it is according to the technical specifications then there should not be any problems.

What is currently important is the above stated point 1 and 2. 

So back to my question :)
How can I test the Implementation and Policy Checker in the build I have now? Which file do I invoke?

**Comment by beyo-ra** [comment]
I downloaded the 20170127 release and once again successfully built it with

**OracleJDK**
`[archlinux]# mvn -X -s "$build_DIR/maven.conf.xml" clean install >` [mavendbg_oraclejdk.txt](https://github.com/veraPDF/veraPDF-library/files/736207/mavendbg_oraclejdk.txt)

**Azul OpenJDK**
`[archlinux]# mvn -X -s "$build_DIR/maven.conf.xml" clean install >` [mavendbg_openjdk.txt](https://github.com/veraPDF/veraPDF-library/files/736208/mavendbg_openjdk.txt)

**Implementation Checker**
The Implementation Checker is successfully executed
`[archlinux]# java -jar veraPDF-core-functionality/veraPDF-apps/gui/target/gui-1.0.0.jar`

**Policy Checker**
While a policy can be provided by `--policyfile`, changing the features.xml file as described in http://docs.verapdf.org/policy/ is not possible.

According to the docs, the content of `features.xml` is to be replaced with
```
<featuresConfig>
  <enabledFeatures>
    <feature>FONT</feature>
  </enabledFeatures>
</featuresConfig>
```
`[archlinux]# find veraPDF-core-functionality -name "features.xml"` yields

> veraPDF-core-functionality/docs/vera-site/cli/policy/font/features.xml
> veraPDF-core-functionality/veraPDF-apps/installer/src/main/config/features.xml
> veraPDF-core-functionality/veraPDF-apps/installer/target/staging/config/features.xml

Where the content of config/features.xml 
```
<featuresConfig>
    <informationDict>true</informationDict>
    <metadata>false</metadata>
    <documentSecurity>false</documentSecurity>
    <signatures>false</signatures>
    <lowLevelInfo>false</lowLevelInfo>
    <embeddedFiles>false</embeddedFiles>
    <iccProfiles>false</iccProfiles>
    <outputIntents>false</outputIntents>
    <outlines>false</outlines>
    <annotations>false</annotations>
    <pages>false</pages>
    <graphicsStates>false</graphicsStates>
    <colorSpaces>false</colorSpaces>
    <patterns>false</patterns>
    <shadings>false</shadings>
    <xobjects>false</xobjects>
    <fonts>true</fonts>
    <propertiesDicts>false</propertiesDicts>
</featuresConfig>
```
Setting <font>true</font> or replacing the content with the suggested XML has no effect.
Needless to say that there is a discrepancy between the documentation and provided features.xml.

- Where is the features.xml the `veraPDF-core-functionality/veraPDF-apps/gui/target/gui-1.0.0.jar` applies?

The instructions for configuring feature extraction http://docs.verapdf.org/config#features.xml returns 404. Although the instructions are available in the offline documentation.

> Try running `verapdf --version` which should generate the missing files.

Has no effect.

Also tried to manually copy the config directory to `gui-1.0.0.jar`

Recommendation: provide arguments to assign custom config files, e.g., 

- `gui-1.0.0.jar --cf-features ~/verapdf/config/features.xml`
- `gui-1.0.0.jar --cf-app ~/verapdf/config/app.xml`
- `gui-1.0.0.jar --cf-validator ~/verapdf/config/validator.xml`
- `gui-1.0.0.jar --cf-fixer. ~/verapdf/config/fixer..xml`

**Comment by bdoubrov** [comment]
Broken links in the documentation have been fixed. 

The documentation provides the latest (correct) format of features.xml. This format was changed several releases ago, and what you found is probably some obsolete versions.

The file config/features.xml is located relative to the install folder, which is determined in the shell script and passed to the Java application as a property app.home (Java command line option -Dapp.home=…). This is also where config folder is created by executing `verapdf --version`, if it does not exist yet.

I guess the issue is that the launch script sets app.home property to an empty or remote folder. And thus it is not easy to find out where exactly this features.xm file is located. When veraPDF package is installed via the installer app, this folder is correctly set in the script during the installation.

The easiest workaround is indeed to start the application via the full Java command line specifying directly this app.home folder. We'll provide the documentation on the full set of parameters for this use case.

**Comment by carlwilson** [comment]
Hi @beyo-ra ,

@bdoubrov, his team and I have done a little investigation and we've discussed the problem a little. The issue is that you're running without the startup script that tells the app where the home directory is. A quick work-around is as follows:

1, Select a folder you want to use as home and create it, a good suggestion is `~/.verapdf` beneath your home directory, in my case `/home/cfw/.verapdf`.
2. Execute the following command: `java -Dapp.home="/home/cfw/.veratest" -jar gui-1.0.0.jar --version`
3. `ls ~/.verapdf/config`

and you should see

    -rw-rw-r-- 1 cfw cfw 375 Jan 28 20:36 app.xml
    -rw-rw-r-- 1 cfw cfw 186 Jan 28 20:36 features.xml
    -rw-rw-r-- 1 cfw cfw 109 Jan 28 20:36 fixer.xml
    -rw-rw-r-- 1 cfw cfw   0 Jan 28 20:36 plugins.xml
    -rw-rw-r-- 1 cfw cfw 131 Jan 28 20:36 validator.xml

Now proceed to use the config files in this directory, which will work as long as you use the `java -Dapp.home="/home/cfw/.veratest" -jar gui-1.0.0.jar --version` of the command. As Boris says we'll update the documentation site over the weekend to reflect this.

**Comment by beyo-ra** [comment]
Applying the suggestion https://github.com/veraPDF/veraPDF-library/issues/694#issuecomment-275873293,
I have now been able to create the config directory and successfully execute the policy checker.

Before the output report, two compiler errors are thrown,
> Compiler warnings:
>   line 534: Attribute 'version' outside of element.
>   line 557: Attribute 'version' outside of element.
> Compiler warnings:
>   line 16: Illegal attribute 'select'.

although it does not seem to impede the checker.

**Comment by carlwilson** [comment]
Hi @beyo-ra , the warnings you see are generated by the XSLT Java library and don't indicate any real problem. We'll suppress them if/when we work out the correct log config for the library. Can this issue be closed now?
