### ISSUE TITLE
Artifactory delivers broken incomplete binaries

### ISSUE THREAD

**Issue by kriegaex** [veraPDF/veraPDF-library#703]
Maven configuration:

```xml
      <dependency>
        <groupId>org.verapdf</groupId>
        <artifactId>validation-model</artifactId>
        <version>1.1.6</version>
        <scope>test</scope>
      </dependency>

(...)

    <repositories>
      <repository>
        <snapshots>
          <enabled>true</enabled>
        </snapshots>
        <id>vera-dev</id>
        <name>Vera development</name>
        <url>http://artifactory.openpreservation.org/artifactory/vera-dev</url>
      </repository>
    </repositories>
```

Build error:

```
[ERROR] Failed to execute goal on project threadsafe-classloader:
Could not resolve dependencies for project de.scrum-master:threadsafe-classloader:jar:1.0-SNAPSHOT:
Could not transfer artifact org.verapdf:validation-model:jar:1.1.6 from/to vera-dev
(http://artifactory.openpreservation.org/artifactory/vera-dev):
GET request of: org/verapdf/validation-model/1.1.6/validation-model-1.1.6.jar from vera-dev failed:
Premature end of Content-Length delimited message body (expected: 269563; received: 45580
-> [Help 1]
```

This also happens with other veraPDF binaries. I have tried since yesterday, but the Artifactory server or maybe a (caching?) Nginx web proxy in front of it seem to be broken. I cannot build anything related to veraPDF. Can you please fix the server and/or tell me an alternative download source for the binaries?

**Update:** This is what Curl says:

```
$ curl -o validation-model-1.1.6.jar -v http://artifactory.openpreservation.org/artifactory/vera-dev/org/verapdf/validation-model/1.1.6/validation-model-1.1.6.jar
* timeout on name lookup is not supported
*   Trying 176.58.124.154...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to artifactory.openpreservation.org (176.58.124.154) port 80 (#0)
> GET /artifactory/vera-dev/org/verapdf/validation-model/1.1.6/validation-model-1.1.6.jar HTTP/1.1
> Host: artifactory.openpreservation.org
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.10.2
< Date: Sun, 05 Feb 2017 22:52:28 GMT
< Content-Type: application/java-archive
< Content-Length: 269563
< Connection: keep-alive
< X-Artifactory-Id: 11b034544a2f03df:-4aa096f6:159d2c9e1ba:-8000
< Last-Modified: Fri, 27 Jan 2017 08:19:38 GMT
< ETag: 490f7b525f031cfd9024b351a5489309e42ecde2
< X-Checksum-Sha1: 490f7b525f031cfd9024b351a5489309e42ecde2
< Accept-Ranges: bytes
< X-Checksum-Md5: 75dc0e275abd7a07827f5d19282a6ffa
< X-Artifactory-Filename: validation-model-1.1.6.jar
< Content-Disposition: attachment; filename="validation-model-1.1.6.jar"; filename*=UTF-8''validation-model-1.1.6.jar
<
{ [828 bytes data]
 14  263k   14 38580    0     0   219k      0  0:00:01 --:--:--  0:00:01  219k* transfer closed with 223723 bytes remaining to read
* Curl_http_done: called premature == 1
* stopped the pause stream!
 17  263k   17 45840    0     0   260k      0  0:00:01 --:--:--  0:00:01  260k
* Closing connection 0
curl: (18) transfer closed with 223723 bytes remaining to read
```

**Comment by carlwilson** [comment]
Hi @kriegaex apologies as I'm in the US at the moment but am looking at this as a priority now.

**Comment by carlwilson** [comment]
Found and addressed the issue which was caused by a runaway log file due to a persistent hack attempt on the server. It's fine for now and will keep an eye on this to ensure that the hack probing has stopped.

**Comment by kriegaex** [comment]
Yes, it works again. Thanks a lot. :-)

**Comment by carlwilson** [comment]
No problem, sorry that travel and time zones meant that i couldn't respond sooner.

**Comment by kriegaex** [comment]
So here is a little goodie for you. This is what I needed the binaries for: parsing and validating multiple PDFs concurrently in a multi-threaded fashion, even though veraPDF is not thread-safe. See [original StackOverflow question](http://stackoverflow.com/questions/41936609) and [my answer](http://stackoverflow.com/a/42080592/1082681).

The full solution can be seen in my own GitHub repo as described in and linked off my answer on SO. Maybe you want to use my [`ThreadSafeClassLoader`](https://github.com/kriegaex/ThreadSafeClassLoader/blob/master/src/main/java/de/scrum_master/thread_safe/ThreadSafeClassLoader.java) and see how it can actually solve (or work around) the problem until someone refactory veraPDF. If you like it - please also check out the test classes and the integration test proving the concept - you may want to point your users to it as an FAQ. This is just an idea though.
