### ISSUE TITLE
XML report clarity and consistency

### ISSUE THREAD

**Issue by david-russo** [veraPDF/veraPDF-library#707]
Unpredictable report elements
----------------------------------
I find the error reporting in XML to be a bit unintuitive and unpredictable. When looking at a successful report there is little or no indication of which elements or attributes could be monitored for failures. `taskResult` elements only seem to appear when failures occur, and unexpectedly replace their associated `*Report` elements (e.g., `<taskResult task="VALIDATE" …` replaces `<validationReport …`).

The output might be made more predictable by migrating the information provided by `taskResult` into the existing `*Report` elements (e.g., by giving them a `completed`/`succeeded` attribute and/or an `errorMessage` element), guaranteeing that when a report is requested a report element always exist in the XML — failed or otherwise — and doing away with the `taskResult` element altogether. Or conversely, `taskResult` could be made an integral part of the report structure so that it always exists to indicate success or failure.

On a related note, I think `processingTime` and `duration` might also be consolidated for simpler processing (see issue #689).

Unclear attributes
--------------------
Many of the `summary` element's attributes seem unclear to me:
 - `failedJobs`: Failed to … complete/execute/validate/extract features/repair metadata? Does failing a validation task but completing feature extraction result in a failed job? What about if all tasks fail?
 - `valid`: Is this the same as the `compliant` attribute in `validationReport`? Perhaps the use of these terms should be standardized within the report.
 - `inValid`: Presumably "invalid" (or noncompliant), and not "in valid."
 - `validExcep`: Valid exceptions? Validation exceptions? I think this language is a bit too technical to mean much to most, and even as a Java developer it isn't particularly informative — there are many kinds of exceptions worth varying degrees of concern. So assuming these exceptions are fatal, causing validations to fail, how do these differ from `failedJobs`?
 - `features`: Sum of all features extracted? Number of feature reports generated?

Perhaps the `summary` element should be expanded to differentiate between the tasks, e.g:
```xml
<summary jobs="10">
    <validationReports valid="6" invalid="3" failed="1">10</validationReports>
    <featureReports failed="1">5</featureReports>
    <metadataRepairReports failed="0">2</metadataRepairReports>
    <duration start="1484679492455" finish="1484680513054">00:17:00:599</duration>
</summary>
```

**Comment by carlwilson** [comment]
I'm about to close this having dealt with most of the issues. One unresolved problem is the handling of the TaskResults. We'll be considering the handling of these for the 1.6 release. If you have any suggestions could we gather them in another issue please.
