### ISSUE TITLE
PDF/A-1 file gives font-related error in Acrobat Preflight, but is valid according to VeraPDF.

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-library#708]
I ran into the following PDF/1-A document (incidentally a how-to on creating PDF/A, oh the irony!):

<http://library.harvard.edu/sites/default/files/Converting%20to%20PDF_A.pdf>

In Acrobat Pro 11's Preflight, the file fails validation against the "PDF/A-1" profile with the following error message:

"CIDset in subset font is incomplete"

But according to VeraPDF it is valid PDF/A-1!

No idea whether the different results reflect any shortcoming of either VeraPDF or Acrobat Preflight, but I just thought I'd report it anyway.

**Comment by bdoubrov** [comment]
Thanks for reporting this issue. It is exactly one of those cases where the PDF/A specification is not clear and admits several interpretations. This is what ISO 19005-1 says about CIDSet:

> For all CIDFont subsets referenced within a conforming file, the font descriptor dictionary shall include a CIDSet stream identifying which CIDs are present in the embedded CIDFont file, as described in PDF Reference Table 5.20.

 It is not clear whether the last part of this clause starting with "identifying ..." is a requirement or merely a clarification.  At the moment veraPDF checks just the presence of this CIDSet stream, while Acrobat 11 Preflight is in addition checking that this CIDSet correctly identifies all glyphs present in the font subset.

The good news is that this is exactly one of the questions under discussion at the PDF Association Technical Working Group. And we hope to come to the common conclustion and adjust the implementation if required.

**Comment by bitsgalore** [comment]
Possibly related: I just created this PDF/A-1a in Acrobat 11:

<https://zenodo.org/record/292341/files/behoudOptischeDragersExtern.pdf>

It validates without errors in Preflight, but VeraPDF reports the following errors:

    Specification: ISO 19005-1:2005, Clause: 6.3.6, Test number: 1	
    For every font embedded in a conforming file and used for rendering, the glyph width information in the font dictionary and in the embedded font program shall be consistent.	Failed
    1 occurrences 	Hide
    Glyph	
    renderingMode == 3 || isWidthConsistent == null || isWidthConsistent == true	
    root/document[0]/pages[42](679 0 obj PDPage)/contentStream[0](711 0 obj PDContentStream)/operators[1422]/usedGlyphs[0](QUEZJX+Cambria 32 0)

        
    Specification: ISO 19005-1:2005, Clause: 6.3.5, Test number: 1	
    The font programs for all fonts used within a conforming file shall be embedded within that file, as defined in PDF Reference 5.8, except when the fonts are used exclusively with text rendering mode 3.	Failed
    1 occurrences 	Hide
    Glyph	
    renderingMode == 3 || isGlyphPresent == null || isGlyphPresent == true	
    root/document[0]/pages[42](679 0 obj PDPage)/contentStream[0](711 0 obj PDContentStream)/operators[1422]/usedGlyphs[0](QUEZJX+Cambria 32 0)

On the surface this looks like something that might be related.

**Comment by bdoubrov** [comment]
This one is not related the the abobe CIDSet issue and seems to be a veraPDF bug in TrueType font parsing. Going to fix it now.

**Comment by bitsgalore** [comment]
In that case you might also be interested in this PDF/A-2a version of the file, which gives similar (but not quite the same) errors. Here it is:

[behoudOptischeDragersExtern-pdfa2a.pdf](https://github.com/veraPDF/veraPDF-library/files/780495/behoudOptischeDragersExtern-pdfa2a.pdf)

VeraPDF errors in this case:

    Specification: ISO 19005-2:2011, Clause: 6.2.11.4, Test number: 4	
    If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream, then it shall identify all CIDs which are present in the font program, regardless of whether a CID in the font is referenced or used by the PDF or not.	Failed
    1 occurrences 	Show
        
    Specification: ISO 19005-2:2011, Clause: 6.2.11.4, Test number: 2	
    Embedded fonts shall define all glyphs referenced for rendering within the conforming file. A font referenced for use solely in rendering mode 3 is therefore not rendered and is thus exempt from the embedding requirement.	Failed
    1 occurrences 	Show
        
    Specification: ISO 19005-2:2011, Clause: 6.2.11.5, Test number: 1	
    For every font embedded in a conforming file and used for rendering, the glyph width information in the font dictionary and in the embedded font program shall be consistent.	Failed
    1 occurrences

**Comment by bdoubrov** [comment]
All issues were fixed and released in veraPDF 1.2

**Comment by DarrenHoffman** [comment]
> Acrobat 11 Preflight is in addition checking that this CIDSet correctly identifies all glyphs present in the font subset.
Except it seems that for TrueType CIDFonts that Acrobat XI is actually checking against only the glyphs actually used in content.
