### ISSUE TITLE
Windows installation observations

### ISSUE THREAD

**Issue by MircoBabin** [veraPDF/veraPDF-library#709]
## Dev Effort
3D

## Description
- OS: Windows/10

I choose the PDFBOX installation (why? I really don't know, it was a random choice, as there is no explanation anywhere what the difference is between PDFBOX and GREENFIELD).

Installing 1.0.12-PDFBOX, during the installing process the directory c:\users\mirco/verapdf is presented as installation directory. A little awkward to install in the USER directory, this is not normally done on Windows Systems. A better directory would be %programfiles%\verapdf.
During installation an annoying dosbox is shown with useless debug information.

After installation when I start the GUI using verapdf-gui.bat there is no way to choose a profile. Also an annoying dosbox is shown with useless debug information.

![image](https://cloud.githubusercontent.com/assets/8981285/23055999/6013b4d4-f4e9-11e6-9127-58a6cfe9baa1.png)

After validation, why is the HTML not automatically opened on Windows ?

It appears PDF/A-1B validation profile has been used (did not see that in the GUI).
![image](https://cloud.githubusercontent.com/assets/8981285/23056234/b9b5d2a0-f4ea-11e6-85e3-620020f3f417.png)

Regards,
Mirco Babin

**Comment by bdoubrov** [comment]
Thanks for the detailed review of the GUI version on Windows. We'll try to improve the user experience in the coming release.

And I see where the confusion with the choice of the validation profile comes from. Currently this is configured via the drop down list with value "Auto-detection" by default. This means that veraPDF tries to detect the PDF/A flavour by the information predent in the document metadata. You can manually set it up to any other flavour (1B, 1A, 2B, 2U, 2A, 3B, 3U 3A) or choose to specify a custom validation profile. In the latter case the button "Choose Profile" would be enabled and you'd be ableto choose any other custom validation profile. 

However, this drop down box is missing the label, which probaly caused your confusion.

**Comment by carlwilson** [comment]
Improved and no specific issue left
