### ISSUE TITLE
Infinite loop in SignatureParser

### ISSUE THREAD

**Issue by abysas** [veraPDF/veraPDF-library#713]
`org.apache.pdfbox.pdfparser.SignatureParser#getOffsetOfNextEOF` does not consider the fact that less bytes could be read than the size of read buffer. As `RandomAccessBufferedFileInputStream` is used as `RadndomAccessRead` implementation, it internally uses chunks (4096 bytes) to read the file. When the boundary of the chunk is close, it may not fill the read buffer if its size is bigger than the bytes left in the chunk. 

For example, if current position  within chunk is 4092, `pdfSource.read(buffer)` will fill only 4 bytes instead of the full buffer (5 bytes size). Thus with the rewind `pdfSource.rewind(buffer.length - 1)` occuring later we get an infinite loop (read 4 and rewind 4 indefinitely).

`getOffsetOfNextEOF` method should consider how many bytes were actually read when rewinding the file stream.

**Comment by abysas** [comment]
The proposed patch:
```
<+>UTF-8
===================================================================
--- pdfbox/src/main/java/org/apache/pdfbox/pdfparser/SignatureParser.java	(revision b7dfa69778a0dff4c18d5ab202a51ae1b8ce1cca)
+++ pdfbox/src/main/java/org/apache/pdfbox/pdfparser/SignatureParser.java	(revision )
@@ -166,12 +166,12 @@
         pdfSource.read(buffer);
         pdfSource.rewind(buffer.length - 1);
         while (!Arrays.equals(buffer, EOF_STRING)) {    //TODO: does it need to be optimized?
-            pdfSource.read(buffer);
+            int bytesRead = pdfSource.read(buffer);
             if (pdfSource.isEOF()) {
                 pdfSource.seek(currentOffset + document.getHeaderOffset());
                 return pdfSource.length();
             }
-            pdfSource.rewind(buffer.length - 1);
+            pdfSource.rewind(bytesRead - 1);
         }
         long result = pdfSource.getPosition() + buffer.length - 1;
         pdfSource.seek(currentOffset + document.getHeaderOffset());
```

**Comment by bdoubrov** [comment]
Thanks for reporting the issue. Would you please clarify which version of the tool you are using. I wonder if it would be possible to attach the test file. If forsecurity reasons it can't be uploaded to GitHub, you can forward it directly by me to boris.doubrov@duallab.com

**Comment by abysas** [comment]
I've sent to your email the  PDF file which revealed the issue. For privacy reasons I didn't attached to the test case.
I tried both the latest release version 1.2.1 and dev version 1.3.3 (both were downloaded today) and both hang during validation.
