### ISSUE TITLE
VeraPDF states 'Lbl' structure type is not standard

### ISSUE THREAD

**Issue by 2econd** [veraPDF/veraPDF-library#738]
[TestList.pdf](https://github.com/veraPDF/veraPDF-library/files/949628/TestList.pdf)
[TestListReport.zip](https://github.com/veraPDF/veraPDF-library/files/949630/TestListReport.zip)

VeraPDF PDF/A-1a validation shows "Specification: ISO 19005-1:2005, Clause: 6.8.3, Test number: 2" for each 'Lbl' in the document. Acrobat Pro 11's Preflight don't show any errors on this document. In PDF Reference 1.4 Section 9.7 Table 9.21 'Lbl' tag is present.

**Comment by BezrukovM** [comment]
fixed
GF version fix: https://github.com/veraPDF/veraPDF-validation/pull/167
PB version fix: https://github.com/veraPDF/veraPDF-pdfbox-validation/pull/148

**Comment by bdoubrov** [comment]
Released in version 1.4.5 as a hotfix for veraPDF 1.4
