### ISSUE TITLE
demo.verapdf.org PDF/A-1a check fails but standalone app do not

### ISSUE THREAD

**Issue by 2econd** [veraPDF/veraPDF-library#739]
[TestToUnicode.pdf](https://github.com/veraPDF/veraPDF-library/files/949652/TestToUnicode.pdf)

demo.verapdf.org PDF/A-1a check fails with "Clause: 6.3.8, Test number: 1" because descendant CIDFonts do not have /ToUnicode cmap. Standalone app do not fails this check. Acrobat Pro 11's Preflight also do not shows any errors.

**Comment by bdoubrov** [comment]
Yes, demo.verapdf.org still uses 1.0 veraPDF release (this can be seen in the report). The latest stable release is 1.4.1. We'll update the demo.verapdf.org version shortly.

**Comment by carlwilson** [comment]
Hi @2econd and @bdoubrov I've updated the REST demonstrator to latest 1.4 build.
