### ISSUE TITLE
International characters in filenames

### ISSUE THREAD

**Issue by muddenhed** [veraPDF/veraPDF-library#741]
Hi

One of the organization i work for would love to use your software for validating PDF files.

There is just one problem and that is that many of our PDF files have characters from our specific language in the file name and VeraPDF cannot validate those files until they are renamed to something without these characters.

Is it possible to make VeraPDF to support these characters in the file name?

Our language are Swedish (sv-SE) and it is the last 3 characters in our alphabet that is needed support for.

![image](https://cloud.githubusercontent.com/assets/8309791/25798449/7d40220e-33e1-11e7-8c6d-c1df263f5ae8.png)

Regards

Marcus Uddenhed

**Comment by carlwilson** [comment]
Hi @muddenhed 

I'd need to know a little more about your environment before looking at this. In no particular order:

* which version of Java are your using, to find out type `java -version`?
* what operating system are you running?
* what's your default locale on the machine, see [here for Windows](https://www.java.com/en/download/help/locale.xml), System Preference->Language for Mac or System Settings->Language Settings or similar for Linux.

Armed with that information I'll be able to run a few tests and get back to you.

**Comment by muddenhed** [comment]
Hi @carlwilson 

The java version i'm trying with is a portable version of java 8 update 131 from [jPortable](https://sourceforge.net/projects/portableapps/files/Java%20Portable/), this is due to all the different java versions we need to support.

The operating system is Windows 10 with Swedish(Sverige) locale.

**Comment by muddenhed** [comment]
Hi @carlwilson 

Any updates on this issue?

**Comment by carlwilson** [comment]
Hi @muddenhed. Right now We're a little busy with a few other things but we will definitely look to close this for the next release which will probably be for the 31/5 or 1/6. There'll certainly be a status update and hopefully a PR merged into the dev build before then.

**Comment by muddenhed** [comment]
Hi @carlwilson, that sound great. :-)

Thanks. :-)

**Comment by bdoubrov** [comment]
Just tried to reproduce it onmy Win10 machine with Russian locale. No issues at all using cyrillic characters in the file names. Both CLI and GUI happily accept them and do the job.

The only difference I see is that I have an Oracle Java 1.7 on my machine instead of Java 8. 

@muddenhed could you check if your problemis reproduced with Oracle Java 1.7 installation on the same Win10 machine and the same Swedish locale?

**Comment by carlwilson** [comment]
I've tried to reproduce this using a Windows 7 VM and the appropriate JPortable Java version and to no avail. Am just returning my VM to UK settings now. I'd like to see your Java settings also please, i.e. the output of `java -version`. It'd also be good if you could capture the output produced if you use the CLI to validate one of the offending files please. Without further details we'll consider closing this as not reproducible later this month.

**Comment by muddenhed** [comment]
I will check this again as son as possible, will get back to you.

**Comment by bdoubrov** [comment]
I think this issue is related to the known JVM limitation on Windows with encodings of command line arguments. 

The simplest workaround is to place your file(s) into the folder with the name that does not include any international characters and pass this folder name as an argument to veraPDF. It will then run a batch job picking up all file names inside this folder correctly.

**Comment by muddenhed** [comment]
Thanks for your response. :-)

I think it has to do with the command line parameters for VeraPDF, when do my tests i simply ran it like this.
`C:\ProgramData\VeraPDF\jPortable\bin\java.exe -jar "c:\Program Files\VeraPDF\bin\greenfield-apps-1.8.4.jar"`

I Think i'm simply missing some pieces of the puzzle, because when i tried on a machine with full java i could use the verapdf-gui.bat without problem.

@carlwilson, did you use any parameters when you tried it?

Thanks again for your support.

**Comment by muddenhed** [comment]
Hi, just wanted you to know that i got it working, so you can close this issue, it is not a bug. :-)

**Comment by bdoubrov** [comment]
Thanks!
