### ISSUE TITLE
Two cases of VeraPDF failure

### ISSUE THREAD

**Issue by gollux** [veraPDF/veraPDF-library#744]
Hello!

We recently started using VeraPDF to validate student theses at our university and we got several cases of VeraPDF failing with an exception. Here are two such cases, which fail in both VeraPDF 1.4.5 and in the current snapshot. Could you please take a look on what happens?

http://mj.ucw.cz/priv/thesis_verca.pdf
http://mj.ucw.cz/priv/thesis_karel.pdf

**Comment by BezrukovM** [comment]
Exception throws in this line of code:
https://github.com/veraPDF/veraPDF-parser/blob/integration/src/main/java/org/verapdf/pd/font/type1/Type1FontProgram.java#L153
Occurs when key value less than 0 in both files. @shem-sergey, take a look, please.

**Comment by shem-sergey** [comment]
Was fixed in https://github.com/veraPDF/veraPDF-parser/pull/220.
