### ISSUE TITLE
Our FontValidator Plugin do not produce result from version veraPdf-1.4.6

### ISSUE THREAD

**Issue by ilcapitanomark** [veraPDF/veraPDF-library#746]
I have installed the newer veraPDF-1.4.6 from 15 May and I configured our plugin (removing file::///) and run. Didn't get the expected output with <customFeatures><pluginFeatures>...

The same plugin version tested with the verapdf-1.1.1-22-gf create the expected output.

Then I enabled the provided "Font Sample" plugin and also didn't work, while was working in the previous version.

**Comment by BezrukovM** [comment]
fixed in https://github.com/veraPDF/veraPDF-library/issues/746
@ilcapitanomark check new version (1.5.17), please. This version works as expected on my machine.

**Comment by ilcapitanomark** [comment]
Perfect with 1.5.17. Thanks and have a nice weekend
