### ISSUE TITLE
Improved identification/reporting of truncated files

### ISSUE THREAD

**Issue by prwheatley** [veraPDF/veraPDF-library#749]
A reasonably common issue encountered by digital preservation practitioners is where one or more files have become accidentally truncated (perhaps in transmission to an archive). Without a checksum, detection of this issue can be difficult. But detection on ingest to an archive might enable the practitioner to request a new (hopefully intact) copy from source, or at least flag possible problems with a bad file. Manually opening files and inspecting them is often too time consuming. So I wonder if veraPDF could be adapted to provide an indication of when a file appears to be truncated (or indeed superficially damaged in some other way)?

Obviously this depends on how much of the file is surviving, and also on some of the ins and outs of the PDF spec and how it is realised in typical files. At the very least it would be particularly useful for veraPDF to report that a file that has a complete PDF header actually purports to be a PDF file, but is incomplete or damaged in some way. In summary, my assumption is that veraPDF can distiguish (most of the time) between a file of a different format to PDF and a PDF file that is damaged (particularly truncated) in some way, and if that could be reflected in the validation output, in addition to the usual failure message, that would be very helpful.

From some limited testing I've done with some truncated files, it appears that veraPDF simply reports that the file appears not to be a PDF, even if a significant amount of the file was available and veraPDF presumably managed to parse quite a bit of it.

**Comment by DuffJohnson** [comment]
Hi Paul,

That’s an interesting idea.

Is truncation the specific problem, or 99% of the cases, or something similar? As opposed to (say) garbled (but not truncated per-se) files?

…and what proportion of a given institution’s document corpora might, would you guess, suffer this problem?

Thanks,

Duff.

**Comment by prwheatley** [comment]
Hi Duff,

It's very difficult to collect stats on this sort of thing and of course I'm sure it varies tremendously from institution to institution depending on the kinds of data they collect, how they acquire it and where it's been stored prior to collection.

I've come across truncated files on several occasions but, yes, there are examples of bit rot as well. Truncation seems to be a pretty common artefact of everyday file operations - disks get full, downloads time out, etc. If you're operating at scale, these things happen now and again...

Cheers

Paul

**Comment by prwheatley** [comment]
The reporting on encrypted PDFs is a little confusing from a user perspective and this seems to relate to the wider issue mentioned above about reporting on exceptions in parsing PDFs.

According to [(http://docs.verapdf.org/cli/config/#features.xml)] The DOCUMENT_SECURITY section of the feature reporting: "Requests information about document security including encryption, password protection and permissions" but this doesn't appear to be the case. It reports on constrained user permissions ok, but if a PDF is encrypted, it will cause an exception when veraPDF parses it. In this case this is (helpfully) caught and reported as:

"Exception: The PDF stream appears to be encrypted. caused by exception: Reader::init(...)encrypted pdf is not supported"

However, no DOCUMENT_SECURITY, or features report for that matter, is generated. So DOCUMENT_SECURITY doesn't really seem to report on encryption. This is implied but not directly mentioned in Johan's excellent blog post on policy checking with veraPDF, where policy checking for encryption requires a two step policy check relating to the DOCUMENT_SECURITY part of the feature report as well as catching mention of "encryption" in any exception report::
[http://openpreservation.org/blog/2017/06/01/policy-based-assessment-with-verapdf-a-first-impression/]

If you're aware of this, its an easy catch, as Johan's policy illustrates, but if not, it's very easy to assume that encryption will always be reported in DOCUMENT_SECURITY.

Speaking to Carl, it sounds like some of the ideas above this comment will be taken forward, possibly in relation to JHOVE, but perhaps it would be useful for veraPDF to generate a short features report in the event of a parsing exception, and report on what was able to be parsed and understood about the file: Header, cross reference table present, elements of cross-reference table that are present and if they could be parsed, trailer, and so on. In addition to also reporting on encryption for the DOCUMENT_SECURITY report if it appears to be present.

From a digital preservation perspective getting the most out of veraPDFs parsing (or failed parsing) would be really useful. Regardless of wider PDF/A conformance, knowing, or at least having an educated guess at when there may be substantial obstacles to rendering a PDF file (the top ones being: it's encrypted or it's damaged in some way) would be really valuable.

**Comment by prwheatley** [comment]
Having just spotted this...
https://github.com/veraPDF/veraPDF-library/issues/886
...it might be worth noting that a number of the encrypted files I came across appear also to exhibit what Boris describes as a "severe PDF syntax error". Where this leaves us on this issue I'm not exactly sure, but the above possibly still needs consideration.

**Comment by bdoubrov** [comment]
There are three different cases we have to distinguish here:

1) PDF document contains corrupted Encrypt dictionary: this is the case of #886. There is simply no way to further parse the document, and veraPDF throws a runtime exception in this case. It is not much different from any other severe syntax errors like missing trailer or corrput cross-reference table

2) The document complies to ISO 32000-1 and is Encrypted with a non-empty user password. In this case we can parse only trailer, but nothing else. Not even the info dictionary, which would also be encrypted. At the moment we also treat this as a severe error preventing the document from further analysis. We'll check if we can still create a valid feature report in such case. This case can be differentiated from the previos one by the error message. In case of (correctly) encrypted documents the error would be:
```
 Exception: The PDF stream appears to be encrypted. caused by exception: Reader::init(...)encrypted pdf is not supported
```

3) The document complies to ISO 32000-1 and is Encrypted with an empty user password. In this case veraPDF is able to parse the file and will generate the correct features and validation reports.
