### ISSUE TITLE
CIDs greater than 65535

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#757]
ISO 19005-2:2011 6.1.13 says:
"A conforming file shall not contain a CID value greater than 65535."
However, veraPDF 1.4.7 checks CMaps only for **referenced** characters being mapped to CIDs greater than 65535.

**Comment by bdoubrov** [comment]
Accepted. Will be implemented in the next release

**Comment by bdoubrov** [comment]
Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/pull/161
