### ISSUE TITLE
PDF/A-2 6.2.4.3

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#758]
Section 6.2.4.3 of ISO 19005-2:2011 requires these tests to fail:

veraPDF-corpus/PDF_A-2b/6.2 Graphics/6.2.4.3 Uncalibrated -Device colour spaces/veraPDF test suite 6-2-4-3-t01-pass-d.pdf
veraPDF-corpus/PDF_A-2b/6.2 Graphics/6.2.4.3 Uncalibrated -Device colour spaces/veraPDF test suite 6-2-4-3-t01-pass-e.pdf

However, they succeed with veraPDF 1.4.7. That is, they need to be renamed from pass to fail and veraPDF should detect the violation of section 6.2.4.3.

**Comment by a20god** [comment]
This one should also fail:

veraPDF-corpus/PDF_A-2b/6.2 Graphics/6.2.4.3 Uncalibrated -Device colour spaces/veraPDF test suite 6-2-4-3-t02-pass-e.pdf

You cannot use DeviceCMYK with an RGB output intent (or vice versa).

**Comment by bdoubrov** [comment]
I don't see violations of PDF/A device colour requirements in these files. They the mechansim of DefaultRGB (first two tests) and DefaultCMYK (the third test) to remap device colour spaces to the device-independent ones.

**Comment by a20god** [comment]
True.
