### ISSUE TITLE
Comment containing binary data after header line

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#759]
Section 6.1.2 of ISO 19005-2:2011 says:

"The aforementioned EOL marker shall be immediately followed by a % (25h) character followed by at least four bytes, each of whose encoded byte values shall have a decimal value greater than 127."

I interpret that clause as requiring **all** bytes (not just the first four bytes) up to the EOL terminating the comment to have a value greater than 127.

That is, veraPDF should report a violation of section 6.1.2 for this document:
[6.1.2-fail-7.pdf](https://github.com/veraPDF/veraPDF-library/files/1049649/6.1.2-fail-7.pdf)

**Comment by a20god** [comment]
I hope that my interpretation of 6.1.9 is wrong as (if 6.1.9 is read strictly) it would require the **entire** rest of the PDF file to be made up by bytes with value greater than 127. Unfortunately, the wording doesn't leave much room for interpretation. Perhaps a clarification from those in charge of ISO 19005 is needed. For instance, removing "at least" would result in what veraPDF (and pretty much everyone else) implements.

**Comment by bdoubrov** [comment]
Accoring to the Validation TWG the condition "to have a value greater than 127" applies only to "four bytes", not to "at least four bytes". There is no mention of EOL in this clause, which would potentially imply that all characters in the comment line shall "have a value greater than 127".

**Comment by a20god** [comment]
So, this document is compliant?

[6.1.2-03-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1115822/6.1.2-03-fail-2.pdf)

According to veraPDF 1.7.37, it isn't.

**Comment by bdoubrov** [comment]
No, it is not compliant, because the first byte after a % (25h) character has value <= 128.

As far as I can see veraPDF correctly reports this.
