### ISSUE TITLE
PDF/A-2 6.2.11.7.3

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#760]
veraPDF 1.4.7 does not have a rule for clause 6.2.11.7.3 of ISO 19005-2:2011.

**Comment by bdoubrov** [comment]
Thanks for reporting this.

Indeed, this is not implemented yet. Adding this to the next release plans.

**Comment by a20god** [comment]
I think there is yet another ambiguity or misprint or bad wording:

> that is mapped to a code or codes in the Unicode Private Use Area (PUA)

This wording means that if a character is mapped to two Unicode codes, only one of which is in the PUA, ActualText is not needed! Example:

`1 beginbfchar <1234> <0041E000> endbfchar`

I don't think this is what was intended, but the wording doesn't leave much choice, unfortunately.

**Comment by a20god** [comment]
> in **the** Unicode Private Use Area

is also unfortunate wording, there are three Unicode Private Use Areas!

**Comment by a20god** [comment]
When you implement this, you'll probably (like me) come up with another question for the Validation TWG, this time about ISO 32000-1:2008, 14.9.4 (referenced by 6.2.11.7.3 of ISO 19005-2:2011):

> through an ActualText entry in a property list attached to the marked-content sequence with a Span tag

Must this be an explicit Span tag or can it be any tag mapped to Span via RoleMap?

**Comment by shem-sergey** [comment]
Unicode Private Use Area check was added in version 1.7.35.

**Comment by a20god** [comment]
veraPDF 1.7.37 does not detect that a character is mapped to a PUA in this document:

[6.2.11.7.3-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1108894/6.2.11.7.3-fail-2.pdf)

Note that since PDF 1.5, ToUnicode maps to UTF-16.

**Comment by a20god** [comment]
Another one:

[6.2.11.7.3-fail-6.pdf](https://github.com/veraPDF/veraPDF-library/files/1108899/6.2.11.7.3-fail-6.pdf)

**Comment by a20god** [comment]
Have you asked the Validation TWG about the weird wording I mentioned in my first comment?

**Comment by bdoubrov** [comment]
No, the intention seems to be absolutely clear here. The wording might indeed look a bit ambiguous,  but reading in the context I don't see any problems here.

**Comment by a20god** [comment]
Stll, veraPDF should treat 6.2.11.7.3-unknown-3.pdf and 6.2.11.7.3-unknown-4.pdf the same way!

**Comment by shem-sergey** [comment]
We have checked file 6.2.11.7.3-fail-2.pdf and veraPDF determines the following toUnicode sequence for character a: \uDBC0 \uDC61, both of which doesn't lie in Unicode private use area.
How do you think Unicode sequence look like in this case?

**Comment by a20god** [comment]
Since PDF 1.5, ToUnicode maps to UTF-16. That is, &lt;DBC0 DC61&gt; is U+100061.

**Comment by BezrukovM** [comment]
Still needs double check for two "unknown" files
