### ISSUE TITLE
Acrobat Pro XI PDF/A-1b convert PDF through the errors in VeraPDF

### ISSUE THREAD

**Issue by abcd0123** [veraPDF/veraPDF-library#762]
Hi,

We are using PDF/A-1b conversion for Acrobat XI Pro and we are getting "No issues" message while validate the VeraPDF throw these below errors. Don't know why this showing like this and don't know how to fix these errors.

Note: Acrobat is one of the biggest PDF editor. Please suggest which PDF editor supports for VeraPDF.

Could you please advise, it would be very helpful to us.

Errors:
=====
1. Glyph
2. CMYK color space

**Comment by shem-sergey** [comment]
Hello!
It's not much we can do without files you are talking about, so if it is possible we would ask you to provide us with any. You can send it to our e-mail if they are not for public access.
Generally speaking, veraPDF and Adobe Acrobat should give the same results on PDF/A validation. So there is no any particular reason why errors as you described should happen.

**Comment by bdoubrov** [comment]
If you can't share the files on github, maybe you can still forward them to my persional address boris.doubrov@duallab.com (of course, the will be used for debug purposes only).

**Comment by bdoubrov** [comment]
We've reproduced the issue. Looks like veraPDF can't parse one of the embedded fonts, and this results in a number of glyph issues. Will check further what's so special with thisproblematic font and wil try to fix veraPDF font parser.
