### ISSUE TITLE
Spot colours

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#771]
## Dev Effort
3D

## Description
I think this document conforms to ISO 19005-2:2011:
[6.2.4.4-pass-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1054276/6.2.4.4-pass-2.pdf)
veraPDF 1.5.49 reports "For any spot colour used in a DeviceN or NChannel colour space, an entry in the Colorants dictionary shall be present."

However, ISO 32000-1:2008, 8.6.6.5 says:
"Any component not specified in the process dictionary shall be considered to be a spot colorant."
That's the best definition of "spot colorant" I could find. However, it applies only to NChannel colour spaces.

Note that ISO 19005-2:2011 does not define "spot colour". ISO 32000-2:2008 doesn't either as it uses "spot colorant". Probably "spot colour" is a typo for "spot colorant".

**Comment by a20god** [comment]
I changed the Subtype from DeviceN to NChannel but that doesn't make a difference for veraPDF:
[6.2.4.4-pass-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1054883/6.2.4.4-pass-2.pdf)

**Comment by bdoubrov** [comment]
I think you are fully correct here. We misread "spot colors" for any colorants in the NChannel color space.

So,accepted and will be fixed in the coming release.

**Comment by a20god** [comment]
But what colorants shall be considered "spot colours" in the DeviceN case (see the first document)?
Everything but None? That would make the term "spot colour" (and "spot colorant") pretty much useless. There must be some definition somewhere...

**Comment by bdoubrov** [comment]
I see this as all DeviceN colorants except:
- /All and /None
- those that are listed in /Components entry of the DeviceN Process Dictionary (ISO 32000-1, Table  72)

**Comment by a20god** [comment]
Your second item applies to NChannel only.

I found this in ISO 19005-1:2008, 8.6.6.5:
"The reserved names Cyan, Magenta, Yellow, and Black shall always be considered to be process colours". This applies to NChannel only, again. And it applies only to CMYK colour spaces, which raises a new question: when is a NChannel colour space considered to be a CMYK colour space?
The text I quoted above begins with "For a CMYK colour space, a subset of the components may be present". So, is an NChannel colour space having only a Black colorant a CMYK colour space?
Is an NChannel colour space having Cyan, Magenta, Yellow, Black, and Silver colorants a CMYK colour space?

**Comment by a20god** [comment]
BTW, 8.6.6.5 of ISO 19005-2:2008 says:
"The special name All, used by Separation colour spaces, shall not be used."

**Comment by a20god** [comment]
Here are test cases for "The reserved names Cyan, Magenta, Yellow, and Black shall always be considered to be process colours":
[6.2.4.4-pass-5.pdf](https://github.com/veraPDF/veraPDF-library/files/1085393/6.2.4.4-pass-5.pdf)
[6.2.4.4-fail-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1085422/6.2.4.4-fail-3.pdf)
It tests with DeviceN/NChannel colour space that has Cyan, Magenta, Yellow, and Black colorants.
It's still not clear, how "CMYK colour space" is defined: subset or supeset?

**Comment by a20god** [comment]
Another one:
[6.2.4.4-pass-6.pdf](https://github.com/veraPDF/veraPDF-library/files/1085471/6.2.4.4-pass-6.pdf)
This uses a colorant in addition to CMYK.

BTW, 3-Heights complaints about an invalid function in all these documents. I'll try to fix the documents.

**Comment by a20god** [comment]
Here are documents with fixed functions:
[6.2.4.4-fail-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1086440/6.2.4.4-fail-3.pdf)
[6.2.4.4-pass-5.pdf](https://github.com/veraPDF/veraPDF-library/files/1086441/6.2.4.4-pass-5.pdf)
[6.2.4.4-pass-6.pdf](https://github.com/veraPDF/veraPDF-library/files/1086442/6.2.4.4-pass-6.pdf)
Here's a new one:
[6.2.4.4-fail-4.pdf](https://github.com/veraPDF/veraPDF-library/files/1086446/6.2.4.4-fail-4.pdf)

For the 3-Heights online validator  and for callas pdfToolbox 9.2, all these documents are compliant.

This more and more looks like the spot colour busines of 6.2.4.4 applies to NChannel colour spaces only, not to DeviceN colour spaces.

**Comment by carlwilson** [comment]
@bdoubrov I'm just checking if this has been addressed?

**Comment by bdoubrov** [comment]
Yes, this issue was retested and can be closed now. No additional changes required.
