### ISSUE TITLE
Separation arrays having the same name

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#772]
Clause 6.2.4.4 of ISO 19005-2:2011 says:
"All Separation arrays within a single PDF/A-2 file (including those in Colorants dictionaries) that have the same name shall have the same tintTransform and alternateSpace."
This wording does not exclude unreferenced Separation arrays. Therefore, validation of this document should fail:
[fail.pdf](https://github.com/veraPDF/veraPDF-library/files/1054354/fail.pdf)
and validation of this one should succeed:
[pass.pdf](https://github.com/veraPDF/veraPDF-library/files/1054355/pass.pdf)
("Separation array" is nowhere defined.)

**Comment by bdoubrov** [comment]
Thanks for reporting this very tricky case. Still, I believe unreferenced Separation arrays are excempt from the requirements of 6.2.4.4 for the following reason:
- color arrays are only defined in the context of Resource dictionaries and other cases, where they are explicitly mentioned in the PDF specification. This is not a common data structure. 
- unreferenced color arrays are even less relevant for the visal appearance of PDF documents, than the resources not referenced from the content stream. And the latter are excluded from the requirememnts of PDF/A-2, 6.2.
