### ISSUE TITLE
Alternate in ICC stream dictionary and PDF/A-1b

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#773]
## Dev Effort
1D

## Description
verarPDF 1.7.2 claims that this document conforms to ISO-19005-1:2005:
[ICC-Alternate-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1057734/ICC-Alternate-1.pdf)
However, the Alternate entry of the output intent's DestOutputProfile (which is not to be ignored in PDF/A-1, in contrast to PDF/A-2)
- is a device color space which violates 6.2.3.3 (DeviceCMYK vs. RGB output intent)
- does not have the same number of components as the ICC profile (4 vs. 3), see PDF Reference 1.4 Table 4.16.

**Comment by bdoubrov** [comment]
Well, strictly speaking this is a violation of the PDF specification. This is a bit similar to the invalid N entry. This has also been discussed already at the Validation Technical Working Group. But I'll double check this again.

**Comment by a20god** [comment]
The document clearly violates 6.2.3.3 (DeviceCMYK vs. RGB output intent).

**Comment by THausherr** [comment]
Related? Attached PDF validates with VeraPDF (1.14.7-RC) despite a flaw: the /Alternate of the ICC colorspace (at Root/Pages/Kids/[0]/Resources/XObject/Im1/ColorSpace/[1]/Alternate) is /DeviceRGB while the colorspace is a grey one and N=1.
[16bit-transparent.pdf](https://github.com/veraPDF/veraPDF-library/files/3432514/16bit-transparent.pdf)

**Comment by bdoubrov** [comment]
Yes, indeed the document does not comply to PDF 1.7 specification, and veraPDF does not perform the full PDF validation, just PDF/A. 

We catch some of the critical syntax errors and report them to the stderr, but not that one. We'll add this check, as having an alternate with a different number of color components is a quite severe error.
