### ISSUE TITLE
Overprint mode (PDF/A-2b)

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#774]
According to veraPDF 1.7.2 this document complies with ISO 19005-2:2011:

[6.2.4.2-fail-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1058600/6.2.4.2-fail-3.pdf)

However, I believe it violates clause 6.2.4.2. Here's why:
- 6.2.4.2 says: Overprint mode (as set by the OPM value in an ExtGState dictionary) shall not be one (1) when an ICCBased CMYK colour space is used and when overprinting for stroke or fill or both is set to true.
- Overprint mode for fill is set to true
- OPM is 1
- an ICCBased CMYK colour space is used for stroke
That is, all conditions after "one (1)" are satisfied, though nothing is filled.

veraPDF-corpus/PDF_A-2b/6.2 Graphics/6.2.4.2 ICCBased colour spaces/veraPDF test suite 6-2-4-2-t02-pass-b.pdf
and
veraPDF-corpus/PDF_A-2b/6.2 Graphics/6.2.4.2 ICCBased colour spaces/veraPDF test suite 6-2-4-2-t02-pass-c.pdf
should fail, not pass.

Apparently, veraPDF behaves as if
"when overprinting for stroke or fill or both is set to true"
were
"when overprinting for stroke and fill is set to true".

**Comment by bdoubrov** [comment]
Having ICCBased CMYK set for stroke has no effect for the fill operations, and vice versa. Again, thiswhat has been disucssed at Validation TWG with the resulution that it actually means the following:

>Overprint mode (as set by the OPM value in an ExtGState dictionary) shall not be one (1) when an ICCBased CMYK colour space is used for stroke and overprinting for stroke is set to true, or when ICCBased CMYK colour space is used for fill and overprinting for fill is set to true, or both.

**Comment by a20god** [comment]
The description element in verapdf-profile-6-2-4-2-t02.xml still contains the original wording and therefore does not reflect the test performed by veraPDF.

**Comment by a20god** [comment]
This document should fail validation under the new rules:
[6.2.4.2-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1071358/6.2.4.2-fail-2.pdf)
But it doesn't with veraPDF 1.7.2. Note that if an ExtGState provides OP but not op, OP will set overprinting for both stroking and filling.

**Comment by bdoubrov** [comment]
Thanks, we'll double check this with the latest dev version and fix, if confirmed.

The descriptionof the rule has been updated in https://github.com/veraPDF/veraPDF-validation-profiles/pull/156

**Comment by a20god** [comment]
Here's another test:
[6.2.4.2-fail-7.pdf](https://github.com/veraPDF/veraPDF-library/files/1071449/6.2.4.2-fail-7.pdf)
veraPDF 1.7.2 thinks this document is compliant. However, even the new wording doesn't require the colour space to be actually used for painting to make OPM=1 with OP/op=true forbidden.
