### ISSUE TITLE
veraPDF test suite 6-2-10-t04-fail-*.pdf

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#775]
Those tests could be improved: the page ContentStream of all those tests reference a CharString using transparency. There should be at least one case of all referenced CharStrings using no transparency and at least one unreferenced CharString using transparency. According to A.5 unreferenced CharStrings do contribute to transparency.

For instance, just use an empty show string for all those tests (except test g).

**Comment by bdoubrov** [comment]
Thanks for the feedback. We'll indeed add a few more test files as you suggest

**Comment by DmitryRemezow** [comment]
@a20god thank you for feedback.

New test file was added in our test suite - https://github.com/veraPDF/veraPDF-corpus/pull/109
