### ISSUE TITLE
Invalid ToUnicode streams

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#778]
## Dev Effort
3D

## Description
One of the major problem (if not **the** major problem) with PDF documents in the real world is broken ToUnicode streams. About 90% of the PDF documents  I deal with have broken ToUnicode streams. It would be very helpful for forcing PDF writers to create valid ToUnicode streams if veraPDF checked all ToUnicode streams.

For instance, the ToUnicode stream in
veraPDF-corpus/PDF_A-2b/6.2 Graphics/6.2.11 Fonts/6.2.11.4 Embedding/6.2.11.4.2 Subset embedding/veraPDF test suite 6-2-11-4-2-t01-fail-a.pdf
is invalid. (The test fails for a different reason.)

**Comment by bdoubrov** [comment]
Strictly speaking, validation of ToUnicode streams is a part of full ISO 32000-1 validation. As far as I understand, the broken /ToUnicode stream would also lead to PDF/A Level U validation errors as well. So, implicitly, one can already detect them.

In addition to strict PDF/A validation, veraPDF also provides feasture extraction functionality with the possibility to run additional policy checks on the extracted features: http://docs.verapdf.org/policy/

So, we can probably add some info on /ToUnicode map as one of the font features (eg., whether /ToUnicode map is present and if it is correct). But it wiil be then up to the institution to set up this as an extrapolicy requirement in the workflow, as this is formally beyound the socpe of PDF/A validation.

**Comment by a20god** [comment]
BTW, verapdf-corpus does not contain any test for PDF/A-2U that actually uses a ToUnicode stream.

**Comment by a20god** [comment]
Well, an invalid ToUnicode stream does not map character codes for at least all referenced glyphs to Unicode values, as required by ISO 19005-2:2011 6.2.11.7.2.

**Comment by bdoubrov** [comment]
There are indeed different options for a PDF parser to handle invalid ToUnicode streams. 

Ignoring such stream completely is one of them. But this question is not a part of PDF/A validation, similar to invalid embedded fonts or ICC profiles according to the current scope of veraPDF. 

We deal with such questions via a "plug-in" mechanism that can do extra checks on top of PDF/A.

**Comment by a20god** [comment]
6.2.11.7.2 of ISO 19005-2:2011 does not allow you to ignore ToUnicode streams in PDF/A-2a and /PDF/A-2u documents for certain fonts!

**Comment by carlwilson** [comment]
@bdoubrov what's the current status of this issue?

**Comment by bdoubrov** [comment]
This one is still open. I suggest we move it to the next release. What needs to be done:
- add log warnings in case of errors in ToUnicode streams
- add more tests (PDF/A-2U level) with ToUnicode streams
