### ISSUE TITLE
Overprint mode and Pattern (PDF/A-2b)

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#780]
veraPDF 1.7.2 does not detect that this document violates 6.2.4.2:
[6.2.4.2-fail-6.pdf](https://github.com/veraPDF/veraPDF-library/files/1064001/6.2.4.2-fail-6.pdf)

If I understand ISO 32000-1:2008 correctly, this one complies with 6.2.4.2:
[6.2.4.2-pass-6.pdf](https://github.com/veraPDF/veraPDF-library/files/1064009/6.2.4.2-pass-6.pdf)
(callas pdfToolbox 9.2 disagrees with me here.)

The difference between the two documents is that in the first one, the pattern is defined in a Form XObject (which is invoked after setting overprint mode), whereas in the second one is it is defined in the page's content stream (therefore overprint mode is not in effect for the pattern even though it is enabled before using the pattern).

**Comment by bdoubrov** [comment]
Apparently, the difference between patterns on the page and inside Form XObjects is not yet fully implemented. Reopen the issue till we fix it.
