### ISSUE TITLE
Count in outline dictionary

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#781]
All(?) PDF documents in veraPDF-corpus share the same violation of the underlying PDF standard (PDF Reference 1.4 or ISO 32000-1:2008). At least the "pass" documents should be valid PDF. The current state makes comparing veraPDF results against the results of PDF/A validators which take "Conforming PDF/A-2 files shall adhere to all requirements of ISO 32000-1 as modified by this part of ISO 19005" (see ISO 19005-2:2005 5.1) seriously more difficult than necessary.

The problem is this: the value of the Count entry in the outline dictionary (/Root/Outlines) is wrong. It is always 1 for the veraPDF corpus documents, but it shall be the "Total number of visible outline items at **all** levels of the outline" (emphasis mine).

**Comment by bdoubrov** [comment]
Well, actually this is inherited from Isartor test suite, that has the same issue with /Count. 

We'll fix this in veraPDF test corpus. Doesn't make sense to make test files not compliant with ISO 32000-1.

**Comment by bdoubrov** [comment]
Fixed in https://github.com/veraPDF/veraPDF-corpus/pull/94
