### ISSUE TITLE
ID in trailer (PDF/A-2b)

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#782]
I think

veraPDF-corpus/PDF_A-2b/6.1 File structure/6.1.3 File trailer/veraPDF test suite 6-1-3-t01-fail-b.pdf

should not fail. Neither ISO 19005-2:2011 (6.1.3) nor ISO 32000-1:2008 (14.4) specify a minimum length for the two byte strings in ID. ISO 32000-2 will, but that doesn't matter here.

**Comment by bdoubrov** [comment]
This has been discussed at TWG, and based on ISO 32000-1: 
>ID  shall be a permanent identifier based on the contents of the file 

and 
> the calculation of the file identifier need not be reproducible; all that matters is that the identifier is likely to be unique.

it was decided that an empty ID violates the core meaning of the ID and shall not be allowed.
