### ISSUE TITLE
Colour spaces in unused Type 3 font char strings

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#783]
## Dev Effort
3D

## Description
veraPDF 1.7.2 claims that this document does not conform to ISO 19005-1:
[v6.pdf](https://github.com/veraPDF/veraPDF-library/files/1067334/v6.pdf)
I disagree. So do other PDF/A validators. I believe the checks for overprint mode (for PDF/A-2, see https://github.com/veraPDF/veraPDF-library/issues/777) and colour spaces should be done on used char strings only, whereas the checks for transparency (PDF/A-2, see https://github.com/veraPDF/veraPDF-library/issues/775) should include all char strings. Yes, that's weird, but I didn't make the rules.

The attached document document is
veraPDF-corpus/PDF_A-1b/6.2 Graphics/6.2.3.3 Uncalibrated color space/veraPDF test suite 6-2-3-3-t03-fail-b.pdf
with the k operator removed from the char strings for b and c, but not for a.

**Comment by carlwilson** [comment]
I've tested against 1.14 and this is now a valid document so closing this issue.
