### ISSUE TITLE
ISO 19005-1:2005 TC2 vs. 1a/6.8 Logical Strucure/6.8.2 Tagged PDF/verapdf-profile-6-8-2-t01.xml

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#784]
The description element of 1a/6.8 Logical Strucure/6.8.2 Tagged PDF/verapdf-profile-6-8-2-t01.xml uses the wording of ISO 19005-1:2005, but the implementation implements the revised wording of TC2.
Please update the description.

**Comment by bdoubrov** [comment]
Thanks for the amasing verification efforts!

Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/pull/154
