### ISSUE TITLE
Hexadecimal strings in CMap

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#787]
This document:
[TWG test suite A025-pdfa2-pass-a-patched.pdf](https://github.com/veraPDF/veraPDF-library/files/1070831/TWG.test.suite.A025-pdfa2-pass-a-patched.pdf)
contains a hexadecimal string with an odd number of digits in a CMap, but veraPDF 1.7.2 does not detect that violation of ISO 19005-2:2011, clause 6.1.6.

(It is probably controversial if 6.1.6 and 6.1.13 apply to CMaps. However, there is no wording exempting CMaps from the requirements of 6.1.)

**Comment by a20god** [comment]
Note that veraPDF **does** check hexadecimal strings for an odd number of digits in content streams. Why chould CMaps be treated differently?

**Comment by bdoubrov** [comment]
It's an interesting question. Formally, CMap iformat is not defined in PDF Specification. It refers to Adobe Technical Note #5014, which in its turn refers to PostScript when it comes to lexical convensions. They are basically identical to PDF in case of hexadecimal strings, but formally these are objects coming from different specifications.

Yet, I agree that makes a lot of sense to apply this PDF/A clause also to hexadecimal strings in CMaps.

**Comment by a20god** [comment]
Here's a related document. It has a ToUnicode stream that contains an integer which is outside the implementation limits:

[6.1.13-01-fail-4.pdf](https://github.com/veraPDF/veraPDF-library/files/1111347/6.1.13-01-fail-4.pdf)

**Comment by bdoubrov** [comment]
Thanks for providing a new text file. The issue with large CIDs in CMaps has just been fixed by https://github.com/veraPDF/veraPDF-validation-profiles/pull/161 .

Not sure if the same implementation limit applies to ToUnicode streams. Unicode values may well exceed 65535

**Comment by bdoubrov** [comment]
Just doublke checked the file. I see you refer to a different issue: an integer in the CMap exceeding the implementation limit. Indeed, this is the same kind of question: whether PDF/A file requirements apply to CMaps and ToUnicode maps. 

Integesting question. Will ask for an opinion at TWG.

**Comment by bdoubrov** [comment]
Validation TWG confirms that CMap syntax belongs to PostScript, rather than PDF. Thus, CMaps are not subject to any File structure requirements of PDF/A specifications. In this way they are analogous, for example, to embedded Type1 fonts.
