### ISSUE TITLE
ISO 19005-1 and composite fonts

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#788]
Clause 6.3.2 of ISO 19005-1:2005 says:
"All fonts used in a conforming file shall conform to the font specifications defined in PDF Reference 5.5."
PDF Reference 5.5 defines simple fonts only (composite fonts are defined in 5.6).
Ergo, composite fonts are not allowed documents conforming to ISO 19005-1:2005.
Yet, veraPDF 1.7.2 accepts this document as compliant:
[composite-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1071756/composite-1.pdf)

**Comment by bdoubrov** [comment]
I rather consider this as an unfortunate misprint in the specification. Clause 6.3.3.1 starts with:

> For any given composite (Type 0) font referenced within a conforming file...

So, I believe composite fonts are allowed in PDF/A-1 documents.

**Comment by a20god** [comment]
Misprint or not, it's normative :-(

**Comment by bdoubrov** [comment]
Git the confirmation from Validation TWG that composite fonts have been allowed in PDF/A-1 from the very first version.
