### ISSUE TITLE
veraPDF incorrectly reports violation of ISO 19005-2:2005 clause 6.2.11.8

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#789]
veraPDF 1.7.14 claims that this document:
[a-4.pdf](https://github.com/veraPDF/veraPDF-library/files/1071795/a-4.pdf)
contains a reference to the .notdef glyph. I don't there is such a reference.

**Comment by bdoubrov** [comment]
Looks like a bug. Might be related to some issues when parsing the embedded CID font in the CFF format. We'll double checkand fixit in one of the coming releases.
