### ISSUE TITLE
fsType

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#790]
veraPDF 1.7.12 does not detect that these documents:
[6.2.11.4.1-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1073876/6.2.11.4.1-fail-1.pdf)
[6.2.11.4.1-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1073875/6.2.11.4.1-fail-2.pdf)
violate clause 6.2.11.4.1 of ISO 19005-2:2011.
(I'm too lazy to test the other bits of fsType.)

**Comment by bdoubrov** [comment]
Do you mean this requirement: 

> Only font programs that are legally embeddable in a file for unlimited, universal rendering shall be used.

This also has been discussed a number of times, and the resolution is that this is not a machine verifiable condition, as it requires not just understanding of the fsType property, but also a legal notice in the copyright message and, potentially, deeper legal analysis.

**Comment by a20god** [comment]
See NOTE 3 following your quote. That note implies that fsType 0x0002 is not allowed.

0x0100 is machine verifiable (you already check for XXXXXX+... to find out whether CIDSet is needed for PDF/A-1).

0x0200 certainly is machine verifiable.

**Comment by bdoubrov** [comment]
Well, I think this clause does not refer to any other font specifications and does not mention fsType exactly for the reason that things might be more complicated than just checking fsType. And NOTE 3 does not add any clarity here. 

Please let me know if there is any PDF/A validator that performs this check. In this case I'll try to raise this question again at the Validation TWG.

**Comment by a20god** [comment]
Mine does ;-)

**Comment by bdoubrov** [comment]
Great! Would it be able to get access to it exactly for this kind of cross-checks?

**Comment by a20god** [comment]
Unfortunately, that's not possible (yet).
