### ISSUE TITLE
CalCMYK and DefaultCMYK

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#793]
8.6.5.1 of ISO 32000-1:2008 says:
"A conforming reader should ignore CalCMYK colour space attributes and render colours specified in this family as if they had been specified using DeviceCMYK."
veraPDF 7.1.12 thinks this document is compliant:
[6.2.4.3-fail-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1074828/6.2.4.3-fail-3.pdf)
However, DefaultCMYK is an RGB color space and therefore the number of components is wrong.

Well, I admit that it is not clear whether DefaultCMYK shall be used for CalCMYK or not.

(Yes, CalCMYK is deprecated, but ISO 19005-2:2011 does not prohibit usage of CalCMYK.)

**Comment by bdoubrov** [comment]
I would say this test violates ISO 32000-1 because DefaultCMYK refers to an RGB colour space. 

I do however accept https://github.com/veraPDF/veraPDF-library/issues/794, which is a very interesting test case.

**Comment by a20god** [comment]
OK, here's a variation that violates ISO 19005-2:2011 more directly:
[6.2.4.3-fail-3b.pdf](https://github.com/veraPDF/veraPDF-library/files/1081409/6.2.4.3-fail-3b.pdf)

**Comment by shem-sergey** [comment]
Was fixed in https://github.com/veraPDF/veraPDF-validation/pull/192.
