### ISSUE TITLE
Implementation limits and Type 4 functions

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#795]
## Dev Effort
5D

## Description
veraPDF 1.7.12 does not detect that this document contains a Type 4 function that uses an integer that is outside the range allowed by ISO 19005-1:2005, clause 6.1.12:
[veraPDF test suite 6-2-3-4-t01-pass-a-patched.pdf](https://github.com/veraPDF/veraPDF-library/files/1079982/veraPDF.test.suite.6-2-3-4-t01-pass-a-patched.pdf)

**Comment by carlwilson** [comment]
This still appears to be an issue, removing 1.14 milestone.
