### ISSUE TITLE
Invalid colour spaces

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#796]
veraPDF 1.7.12 does not complain about the invalid colour space (/Invalid) used by this document:
[x.pdf](https://github.com/veraPDF/veraPDF-library/files/1079985/x.pdf)
Apparently, it uses the default DeviceGray colour space.

**Comment by a20god** [comment]
Here are more invalid colour spaces ignored by veraPDF:
[x2.pdf](https://github.com/veraPDF/veraPDF-library/files/1080837/x2.pdf)

**Comment by shem-sergey** [comment]
Fixed in PR https://github.com/veraPDF/veraPDF-validation/pull/192.
