### ISSUE TITLE
Default colour spaces

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#797]
## Dev Effort
1D

## Description
veraPDF 1.7.19 claims that this document is compliant:
[DefaultCS-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1082469/DefaultCS-3.pdf)
I can imagine no interpretation of the standards that supports that result. Even ignoring invalid coloour spaces (which is what I suspect veraPDF to do) would not work as the default colour space (DeviceGray) isn't allowed.

This one is questionable (callas pdfToolbox 9.2 claims that it does not comply):
[DefaultCS-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1082470/DefaultCS-2.pdf)

This one is questionable (callas pdfToolbox 9.2 claims that it does not comply, veraPDF 1.7.19 thinks it does comply, but probably for the wrong reasons as shown by the documents above):
[DefaultCS-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1082477/DefaultCS-1.pdf)

**Comment by BezrukovM** [comment]
veraPDF 1.7.57 claims that all these three files are not compliant.
Additional checks required to be sure that it failed on right rules.
