### ISSUE TITLE
hasDuplicateName of PDOCConfig set unexpectedly

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#801]
veraPDF 1.7.19 reports a violation of clause 6.9 of ISO 19005-2:2011 for this document, apparently triggered by hasDuplicateName:
[6.9-pass-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1087989/6.9-pass-1.pdf)
However, there are no duplicate names.

**Comment by bdoubrov** [comment]
Accepted. Looks indeed very strange.  Will check and fix it now.
