### ISSUE TITLE
Invoking verapdf without arguments

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#803]
## Dev Effort
1D

## Description
Perhaps verapdf should not try to read from stdin if stdin is a terminal. In the shell script, you can check this with [ -t 0].

**Comment by carlwilson** [comment]
Test Linux and Mac versions

**Comment by dschulten** [comment]
and please get rid of the help message which tells the user how to send eof.

**Comment by carlwilson** [comment]
Terminal test to be added to start script as suggested....
