### ISSUE TITLE
EmbeddedFiles and PDF/A-1

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#805]
This document violates clause 6.1.11 of ISO 19005-1:2005, but veraPDF 1.7.19 does not detect that violation:
[6.1.11-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1091420/6.1.11-fail-1.pdf)

**Comment by bdoubrov** [comment]
Indeed, we do check at the moment that EmbeddedFiles name tree, if existsat all, has zero size. Logically, this is equivalent to the requirement of 6.1.11, but I agree it is not the same as having to EmbeddedFiles key at all. 

Will fix this in one of the coming releases.

**Comment by bdoubrov** [comment]
This duplicates #827

**Comment by bdoubrov** [comment]
Fixed in the recent refactoring of the model. Available in 1.7.102

**Comment by bdoubrov** [comment]
Fixed in the recent refactoring of the model. Available in 1.7.102
