### ISSUE TITLE
Embedded files and PDF/A-2

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#806]
ISO 19005-2:2011 requires embedded files to conform to ISO 19005-1 or to ISO 19005-2:2011. Apparently, veraPDF 1.7.19 does not check that requirement:
[6.8-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1091455/6.8-fail-1.pdf)

**Comment by a20god** [comment]
Note that this document conforms to ISO 19005-2:2011:

[6.8-pass-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1091467/6.8-pass-2.pdf)

EF: "A dictionary containing a subset of the keys F, UF, DOS, Mac, and Unix, corresponding to the entries by those names in the file specification dictionary. The value of each such key shall be an embedded file stream [...] containing the corresponding file."

**Comment by bdoubrov** [comment]
Accepted. Thanks for reporting this. We do have a rule to check this: https://github.com/veraPDF/veraPDF-validation-profiles/blob/integration/PDF_A/2b/6.8%20Embedded%20files/verapdf-profile-6-8-t01.xml

So, there should be something wrong with the parser.
