### ISSUE TITLE
MIME type

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#807]
veraPDF 1.7.22 thinks this document is non-compliant due to a missing MIME type:

[6.8-pass-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1094467/6.8-pass-1.pdf)

This is problably due to veraPDF implementing a misprint: A file specification dictionary does not have a Subtype entry, but an embedded file stream dictionary has. That is,

"The MIME type of an embedded file, or a subset of a file, shall be specified using the Subtype key of the file specification dictionary."

of  ISO 19005-3:2012 should read

"The MIME type of an embedded file, or a subset of a file, shall be specified using the Subtype key of the embedded file stream dictionary."

This is what callas and 3-Heights implement and what all the examples in chapter E of ISO 19005-3:2012 demonstrate.

(See also https://github.com/veraPDF/veraPDF-library/issues/788, you have to accept either that issue or this one.)

**Comment by bdoubrov** [comment]
Accepted. The intention of theis requirement is absolutely clear.

**Comment by a20god** [comment]
Your change seems to check only one of the entries of the EF dictionary. However, Table 44 of ISO 32000-1:2008 says:

> The value of **each** such key shall be an embedded file stream

**Comment by a20god** [comment]
And there are DOS, Mac, and Unix keys.
