### ISSUE TITLE
AF BDC  in pattern stream

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#808]
veraPDF 1.7.22 claims that this document violates clause 6.8 of ISO 19005-3:2012:

[6.8-pass-6.pdf](https://github.com/veraPDF/veraPDF-library/files/1094647/6.8-pass-6.pdf)

However, the file specification dictionary is referenced from the properties of a BDC operator with AF tag in a pattern.

**Comment by BezrukovM** [comment]
The same issue as in https://github.com/veraPDF/veraPDF-library/issues/809

**Comment by bdoubrov** [comment]
Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/pull/169
