### ISSUE TITLE
AF BDC in Type 3 font's content stream

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#809]
veraPDF 1.7.22 claims that this document violates clause 6.8 of ISO 19005-3:2012:

[6.8-pass-11.pdf](https://github.com/veraPDF/veraPDF-library/files/1094710/6.8-pass-11.pdf)

However, the file specification dictionary is referenced from the properties of a BDC operator with AF tag in a content stream of a Type 3 font. The character having that BDC operator is rendered.

**Comment by a20god** [comment]
BTW, 3-Height's online validator ignores the BDC operator in CharProc streams that are not referenced by text showing operators. (I haven't tried if text rendering mode 3 has the same effect.)

**Comment by BezrukovM** [comment]
This problem has been already discussed with @bdoubrov previously.
Parsing association using BDC operator has been added in GF version of veraPDF already, but for correct validation we have to add "deferred" attribute into the rule for that check (6.8-t04 rule of 3b profiles) which has not been added yet.
@bdoubrov can you look at it, please?

**Comment by bdoubrov** [comment]
Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/pull/169
