### ISSUE TITLE
Clause 6.2.11.3.2 of ISO 19005-2:2011

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#810]
Clause 6.2.11.3.2 of ISO 19005-2:2011 doesn't specify any requirement, it just misquotes ISO 32000-1:2008 (it leaves out the default value). Yet, veraPDF 1.7.22 checks something for that clause and reports a violation for this document:

[6.2.11.3.2-unknown-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1094795/6.2.11.3.2-unknown-1.pdf)

You claimed that veraPDF checks only requirements explicitly stated by ISO 19005.

This is probably a misprint in ISO 19005-2:2011, but what was intended? Was the intention to remove the default value? Or was the intention to require the CIDToGIDMap entry conform to ISO 32000-1:2008 (which allows it to default to Identity)?

**Comment by bdoubrov** [comment]
One can argue, that the intent of this clause of ISO 19005-2:2011 is to make sure this entry is always present and aviod any problems with implementations that forget to handle the deafult value of this entry.

But I see your point as well. So, I'd better doubel check this with experts of Validation TWG.

**Comment by bdoubrov** [comment]
Validation TWG confirms that the intend of this clause in ISO 19005-2 (and 3) is no ensure that CIDToGIDMap entry is always present for CIDFontType2 fonts, even if it is just optional in ISO 32000-1. so, this is an additionaal requirement on top of ISO 32000-1.

**Comment by a20god** [comment]
Thanks!
