### ISSUE TITLE
Broken logical structure

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#814]
The content stream of page 1 of
`veraPDF-corpus/PDF_A-2u/6.2 Graphics/6.2.11 Fonts/6.2.11.7 Unicode character maps/6.2.11.7.2 Level A and Level U conformance/veraPDF test suite 6-2-11-7-2-t01-pass-a.pdf`
uses an MCID but the page does not have a StructParents entry.

**Comment by DmitryRemezow** [comment]
MCID entry was removed from the following test files:
1. 6-2-11-7-2-t01-pass-a.pdf
2. 6-2-11-7-2-t01-pass-h.pdf

https://github.com/veraPDF/veraPDF-corpus/pull/97

**Comment by bdoubrov** [comment]
Fixed in https://github.com/veraPDF/veraPDF-corpus/pull/97
