### ISSUE TITLE
Missing ToUnicode stream

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#815]
I believe the font in this PDF/A-2U document needs a ToUnicode stream according to 6.2.11.7.2:

[6.2.11.7.2-fail-16.pdf](https://github.com/veraPDF/veraPDF-library/files/1102024/6.2.11.7.2-fail-16.pdf)

It uses a Type 1 font with a non-standard glyph name (test.test). veraPDF 1.7.22 indeed detects a problem with 6.2.11.7, but claims that the isue is related to
> The Unicode values specified in the ToUnicode CMap shall all be greater than zero (0), but not equal to either U+FEFF or U+FFFE
rather than
> The font dictionary of all fonts, regardless of their rendering mode usage, shall include a ToUnicode entry [...]

This is probably the same issue as https://github.com/veraPDF/veraPDF-library/issues/812.

**Comment by a20god** [comment]
Here's the same document with a proper ToUnicode stream:

[6.2.11.7.2-pass-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1102056/6.2.11.7.2-pass-3.pdf)

**Comment by bdoubrov** [comment]
Indeed, the issue here is that Unicode value of one of the glyps is not defined. I see that the rror message is a bit confusing, becuase the rule itself is:

```
toUnicode != null && toUnicode.indexOf("\u0000") == -1 
&& toUnicode.indexOf("\uFFFE") == -1 && toUnicode.indexOf("\uFEFF") == -1
```
Which means that the Unicode value shall be defined and shall not be one of U+0000, U+FEFF, U+FFFF. This is not fully reflected in the error message (but is explained in a bit more detail in the wiki).

**Comment by bdoubrov** [comment]
Fixed rule descriptions in
https://github.com/veraPDF/veraPDF-validation-profiles/pull/157

**Comment by a20god** [comment]
Splitting that rule into two might be useful: one for not being able to map a referenced glyph to Unicode and one for **any** glyph mapped to U+FFFE etc.

**Comment by bdoubrov** [comment]
Sounds indeed like a good idea. I reopen this issue till we implement this

**Comment by bdoubrov** [comment]
Split the rule into two in https://github.com/veraPDF/veraPDF-validation-profiles/pull/158
