### ISSUE TITLE
Invalid MIME type

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#816]
veraPDF 1.7.28 does not detect that the MIME type of the embedded file in the following PDF/A-3b documents is invalid:

[6.8-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1102152/6.8-fail-2.pdf)
[6.8-fail-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1102153/6.8-fail-3.pdf)
[6.8-fail-8.pdf](https://github.com/veraPDF/veraPDF-library/files/1102157/6.8-fail-8.pdf)

**Comment by bdoubrov** [comment]
Well, I agree all these files have subtype that does not conform to MIME type specification. However, ISO 32000-1, Table 45 leaves a door for other "registered" names here:

> The value of this entry shall be a first-class name, as defined in Annex E. Names without a registered prefix shall conform to the MIME media type names defined in Internet RFC 2046, Multipurpose Internet Mail Extensions (MIME)...

As there is no way to actually verify that certain name is a registered first-class name, we don't check the MIME type compliance. 

On the other hand, ISO 19005-3 clearly mentions MIME type:
> The MIME type of an embedded file, or a subset of a file, shall be specified using the Subtype key of the file specification dictionary. If the MIME type is not known, the “application/octet-stream” shall be used.

I also see that different validators behave differently here. So, we'd better double check this at the Validation TWG.

**Comment by a20god** [comment]
The door doesn't apply to 6.8-fail-2.pdf as there's no name in the MIME type there.

**Comment by a20god** [comment]
BTW, multipart MIME types are clearly allowed, but they don't make any sense at all.

**Comment by bdoubrov** [comment]
Validation TWG confirms that the value of Subtype shall be a valid MIME type.  However, as RFC 2046 is somewhat open-ended, it is recommended to validate MIME type via a certian generic regular expression.

**Comment by bdoubrov** [comment]
Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/pull/164
