### ISSUE TITLE
AFRelationship

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#817]
veraPDF 1.7.28 fails to detect the invalid AFRelationship value in this document:

[6.8-fail-7.pdf](https://github.com/veraPDF/veraPDF-library/files/1102167/6.8-fail-7.pdf)

**Comment by a20god** [comment]
And here's one that should pass validation:

[6.8-pass-10.pdf](https://github.com/veraPDF/veraPDF-library/files/1102194/6.8-pass-10.pdf)

**Comment by a20god** [comment]
Well, looks like it's only a "should" that is violated. Sorry.

**Comment by a20god** [comment]
BTW, the 3-Heights online PDF/A validator think that 6.8-fail-7.pdf does not conform to PDF/A-3:
> The value of the key AFRelationship is error but must be one of the predefined values or a second class name.

**Comment by bdoubrov** [comment]
Indeed, I see different validators produce different results here. But I think the specification here is quite unambigous. 

> Predefined values are Source, Data, Alternative, Supplement or Unspecified. Other values may
be used to represent other types of relationships, but should follow the rules for second-class names (ISO 32000‑1, Annex E).

It is indeed a "should" requirement, and we don't check them.

**Comment by bdoubrov** [comment]
Got the confirmation from the Validation TWG on this. So, I'm closing this issue as invalid.
