### ISSUE TITLE
GoToR, EF, and PDF/A-1

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#819]
veraPDF 1.7.28 does not detect that this document violates 6.1.11 of ISO 19005-1:2005:

[6.1.11-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1107997/6.1.11-fail-2.pdf)

**Comment by bdoubrov** [comment]
I think the test file does not comply to the PDF 1.4. The value of the EF key is a stream, while by the PDF 1.4 Specification it is supposted to be a dictionary:

> PDF 1.4 Reference, Table 3.32: A dictionary containing a subset of the keys F, DOS, Mac, and Unix, corresponding to the entries by those names in the file specification dictionary. The value of each such key is an embedded file stream (see Section 3.10.3, “Embedded File Streams”) containing the corresponding file.

**Comment by a20god** [comment]
6.1.11 of ISO 19005-1:2005 says:

> A file specification dictionary, as defined in PDF 3.10.2, shall not contain the EF **key**.

See also https://github.com/veraPDF/veraPDF-library/issues/800.

**Comment by bdoubrov** [comment]
Yes, certainly, we can (and will) fix this by checking the key, but thest fileis still not fully correct and wouldnot stand as a proper PDF/A test case.

**Comment by a20god** [comment]
It's a test case for a document that should not pass as conforming. But veraPDF claims it is conforming.

**Comment by a20god** [comment]
Note that veraPDF already correctly checks the presence of keys (rather than the presence of entries of the type required by PDF) in other cases. Here's an example for 6.2.5:

[6.2.5-01-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1112128/6.2.5-01-fail-1.pdf)

**Comment by a20god** [comment]
In at least one case, ISO 19005-2:2011 requires the absence of a key which is not even defined in ISO 32000-1:2008:

[6.2.5-01-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1112139/6.2.5-01-fail-2.pdf)

That is, the HTP entry never has the correct type in PDF 1.7! In other words, the presence or
absence of the keys is to be checked without respect to the type required by ISO 32000-1:2008.

(That key made a very short-lived appearance in PDF Reference 1.3.)

**Comment by BezrukovM** [comment]
_size issue

**Comment by bdoubrov** [comment]
Fixed in the recent refactoring of the model. Available in 1.7.102
