### ISSUE TITLE
Field tree

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#820]
veraPDF does not detect violations caused by field dictionaries that are in the field tree, but don't have annotations that are reachable from the Annots entries of the page objects:

[field-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1108465/field-1.pdf)

The field in this  document contains at least two violations of ISO 19005-2:2011:
- the field dictionary has an AA key (6.4.1)
- there's no annotation dictionary (which is to be used for rendering according to 6.4.1)

Apparently, veraPDF does not use Annots of page objects rather than the field tree rooted at AcroForm/Fields for locating field dictionaries.

**Comment by bdoubrov** [comment]
veraPDF does iterate through all fields in the field tree, as specifed in the veraPDF object model: https://github.com/veraPDF/veraPDF-model/blob/integration/src/main/java/PDLayer.mdl

We'll check what might go wrong on your test file.

**Comment by BezrukovM** [comment]
_size issue

**Comment by bdoubrov** [comment]
Fixed in the recent refactoring of the model. Available in 1.7.102
