### ISSUE TITLE
Implementation limit off by one

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#822]
According to veraPDF 1.7.37, this document has a string that is too long:

[6.1.13-pass-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1111130/6.1.13-pass-2.pdf)

The string has 32767 bytes, which is allowed.

**Comment by bdoubrov** [comment]
Good catch, thanks!

Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/pull/160
