### ISSUE TITLE
Big integers

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#823]
I guess veraPDF treats big integers (not fitting into a Java long) as real numbers and therefore fails to detect that this document violates the implementation limits for integers:

[6.1.13-01-fail-5.pdf](https://github.com/veraPDF/veraPDF-library/files/1111554/6.1.13-01-fail-5.pdf)

However, according to ISO 32000:1-2008, that number is an integer, not a real number as it lacks a U+002E character.

**Comment by bdoubrov** [comment]
Thanks for an interesting test case. Have to think how to handle it properly.

**Comment by BezrukovM** [comment]
Fixed for GF version in https://github.com/veraPDF/veraPDF-parser/pull/254
veraPDF 1.7.54 and later versions
