### ISSUE TITLE
HT Default

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#824]
This document has an ExtGState dictionary with an HT entry whose value is the name Default.

[6.2.5-03-pass-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1112207/6.2.5-03-pass-1.pdf)

veraPDF 1.7.37 thinks that this document violates this constraint:

> All halftones in a conforming PDF/A-2 file shall have the value 1 or 5 for the HalftoneType key.

I think the document is compliant because no halftone is used at all. Or rather, according to Table 53:

> a conforming reader shall initialize this to a suitable device dependent value.

That is, veraPDF behaves as if it initialized the halftone screen to a non-conforming one!

**Comment by a20god** [comment]
BTW, there's another problem with "conforming reader" in 6.2.5 (see also https://github.com/veraPDF/veraPDF-library/issues/813 and https://github.com/veraPDF/veraPDF-library/issues/812):

If (I quote 6.2.5)

> A conforming reader may ignore any instance of the HT key in an ExtGState dictionary

and a PDF/A validator is a conforming reader (which I doubt, see the two issues above), a PDF/A validator need not check the 3 requirements for halftone dictionaries of 6.2.5.

**Comment by bdoubrov** [comment]
Accepted. Will fix it in the coming release
