### ISSUE TITLE
TransferFunction

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#825]
I'm sorry, here's yet another case of bad wording in ISO 19005-2:2011 (6.2.5):

> The TransferFunction key in a halftone dictionary shall be used only as required by ISO 32000-1.

If this means

> ... shall be used only **if** required by ...

then this document is non-compliant:

[6.2.5-03-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1112357/6.2.5-03-fail-1.pdf)

but veraPDF 1.7.37 doesn't detect any issue. I can think of only one other reading:

> ...shall be used as specified by ...

But why did they choose the longer and ambiguous wording if this is what was intended?

**Comment by a20god** [comment]
To put it differently:
- it's clear that TransferFunction must be present if required by ISO 32000-1:2008 Table 130
- it's not clear whether TransferFunction must be absent if TransferFunction is not required by ISO 32000-1:2008 Table 130

**Comment by a20god** [comment]
6.2.5 forbids transfer functions in ExtGState (TR, TR2). If TransferFunction were allowed in a type 1 halftone dictionary, that would open a backdoor for using a transfer function. But there's explicitely a backdoor for type 5 halftone dictionaries. (There's no requirement for TransferFunction being the identity for type 1 halftones used by type 5 halftones.) So, there's no point in prohibiting TR and TR2.

Something's wrong in 6.2.5. But what?

**Comment by a20god** [comment]
Whether TransferFunction is required or not depends on the current colour space
(see the comments of https://github.com/veraPDF/veraPDF-library/issues/826)!

**Comment by bdoubrov** [comment]
I lso find this PDF/A clause on transfer functions very confusing. By its nature PDF/A requires that all colors are specified in a device-independent manner.  On the other hand, ISO 32000-1, 10.4 says:

> Transfer functions shall always operate in the native colour space of the output device...

So, in a way, transter functions are not in the scope of PDF/A validation at all. On the other hand, not permitting them completely would be a violation of ISO 32000-1 exactly because of this requirement in ISO 32000-1, Table 130:

> A transfer function, which overrides the current transfer function in the graphics state for the same component. This entry shall be present if the dictionary is a component of a type 5 halftone (see “Type 5 Halftones” in 10.5.5.6) and represents either a nonprimary or nonstandard primary colour component (see 10.4, "Transfer Functions"). The name Identity may be used to specify the identity function.

My guess is that ISO 19005-2 tries to say that TransferFunction shall not be used, unless its presence is required by ISO 32000-1, Table 130. Another question is how this requirement can be validated, if there is no information on the output color space available.

**Comment by a20god** [comment]
I think I'll implement this for now (until the Validate TWG or someone else comes up with a better solution):

- Top-level Type 1 halftone: TransferFunction can be absent or /Identity
- Type 1 halftone referenced from Type 5 halftone: TransferFunction can be absent or /Identity, TransferFunction must be present (and it must be /Identity) unless the component is Red, Green, Blue, Cyan, Magenta, Yellow, or Black (no matter what colour space is active)
- Type 5 half tone: all entries that are dictionaries or streams with a HalftoneType entry (even if the value of HalftoneType is not an integer) will be validated, no matter what colour space is active

The outcome will be clearly wrong for some cases (both false negatives and false positives), but it should reflect the intent of ISO 19005 for real-world documents.

**Comment by bdoubrov** [comment]
We've checked this at the validatiion TWG, and it lookslike your approach is fully correct. We'll fix veraPDF implementation accordingly.

**Comment by bdoubrov** [comment]
Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/pull/165

**Comment by a20god** [comment]
There's still the special case of the Default entry in a type 5 halftone dictionary to be researched. The rules I proposed above do not cover that case. Table 134 of ISO 32000-1:2008 says about the Default entry:

> If there are any nonprimary colorants, the default halftone shall have a transfer function.

Applying the "if there are" condition to the halftone dictionary doesn't make sense as the Default entry is used for the colorants **not** defined in the type 5 halftone dictionary. I think it rather refers to the colorants of the current colour space. That is, we have to look at the current color space to validate the Default entry.
