### ISSUE TITLE
HalftoneName

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#826]
veraPDF 1.7.37 does not detect the prohibited HalftoneName key in this document:

[6.2.5-05-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1112429/6.2.5-05-fail-1.pdf)

**Comment by a20god** [comment]
That's the simple case. In general, the keys to be checked in the type 5 halftone dictionary depend on the current colour space.

**Comment by a20god** [comment]
This also means that type 5 halftone dictionaries can be checked for validity only when rendering something as we need to know what colour space is used:

[6.2.5-05-pass-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1112475/6.2.5-05-pass-1.pdf)
[6.2.5-05-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1112476/6.2.5-05-fail-2.pdf)

Note that the Red entry in the type 5 halftone dictionary is ignored if CalGray is in effect. Note that the colour space is selected **after** setting the halftone.

**Comment by bdoubrov** [comment]
Accepted. Our current model does not process halftones referenced from Type5 Halftone dictionaries. Will fix it in the coming release.

**Comment by BezrukovM** [comment]
Added new properties and link into halftone (for type 5 halftone logic).
All that left is to add validation profiles for that logic

**Comment by bdoubrov** [comment]
There is already a rule to check that HalftoneName is not used:
https://github.com/veraPDF/veraPDF-validation-profiles/blob/integration/PDF_A/2b/6.2%20Graphics/6.2.5%20Extended%20graphics%20state/verapdf-profile-6-2-5-t05.xml

To the issue is fixed by the changes in the model: https://github.com/veraPDF/veraPDF-model/pull/150
