### ISSUE TITLE
Thumbnail images

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#828]
veraPDF 1.7.37 behaves inconsistently w.r.t. thumbnail images:

Device colour space:

[6.2.8.2-todo-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1115155/6.2.8.2-todo-1.pdf)

Device colour space and LZWDecode:

[6.2.8.2-todo-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1115156/6.2.8.2-todo-2.pdf)

According to 6.2.8.2 of ISO 19005-2:2011, thumbnail images are to be ignored by conforming readers. If veraPDF behaves like a conforming reader, both documents should be accepted as valid. If veraPDF doesn't behave like a conforming reader, both documents should be rejected as invalid.

**Comment by a20god** [comment]
See also https://github.com/veraPDF/veraPDF-library/issues/824 and https://github.com/veraPDF/veraPDF-library/issues/813, and https://github.com/veraPDF/veraPDF-library/issues/812 for issues with "conforming reader".

**Comment by a20god** [comment]
Also note the typo "Thumbs" for "Thumb" in ISO 19005-2:2011.

**Comment by a20god** [comment]
Well, 6.2.8.2 does not really say that thumbnail images are to be ignored. The requirement is much weaker and 6.2.1 does allow page thumbnails. Sorry.

**Comment by a20god** [comment]
Unlike ISO 19005-1:2005, ISO 19005-2:2011 does not have an exception that allows usage of device colour spaces by thumbnail images. On the oher hand, ISO 32000-1:2008 requires usage of device colour spaces for thumbnail images. Conclusion: In PDF/A-2, thumbnail images are not allowed as they either violate 6.2.4 of ISO 19005-2:2011 or 12.3.4 of ISO 32000-1:2008 (and therefore 5.1 of ISO 19005-2:2011). Validation for both documents above should fail.

**Comment by bdoubrov** [comment]
TWG resolution is that Device color spaces in thumbnails and ICC alternates are never used for rendering of PDF/A files and shall be ignored and exempt from all requirements of ISO 19005 except File structure requirements (like, eg., the the use of LZW). This is similar to the resources not referenced from the content stream.

**Comment by a20god** [comment]
There *is* an exemption for thumbnail images in clause 6.2.1 of ISO 19005-2:2011. Sorry.

**Comment by bdoubrov** [comment]
Thanks for the update! I also missed this initially.
