### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by nlibpreserv** [veraPDF/veraPDF-library#829]
At the National Library of Estonia we tested some PDF print files that are sent to us by publishers. We converted them into PDF/A-1b and checked for validation with veraPDF 1.6.

When checking for validation with veraPDF 1.6 the files were claimed to be compliant with Validation Profile requirements. We also checked the same files with the PDF-Tools online validator and the files were validated successfully.

Unfortunately we currently don't have the necessary expertise to check if the validation is actually correct.

**Comment by bdoubrov** [comment]
Thanks for the feedback. Very much appreciated.
