### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#830]
veraPDF 1.7.48 gets a NullPointerException for behoudOptischeDragersExtern-pdfa2a.pdf of
https://github.com/veraPDF/veraPDF-library/issues/708.

**Comment by BezrukovM** [comment]
I can not reproduce that problem on my machine now with latest version.
@a20god, can you check it again with latest version of veraPDF (1.7.50)?
And if the issue will reproduce, then send here terminal output, please.

**Comment by a20god** [comment]
The problem seems to have disappeared in 1.7.51. Anyany, the output is here:
[1.7.44.txt](https://github.com/veraPDF/veraPDF-library/files/1122233/1.7.44.txt)
[1.7.51.txt](https://github.com/veraPDF/veraPDF-library/files/1122234/1.7.51.txt)

**Comment by BezrukovM** [comment]
Protection for this case of possibility for null pointer exception has been added in PRs:
https://github.com/veraPDF/veraPDF-pdfbox-validation/pull/167
https://github.com/veraPDF/veraPDF-validation/pull/207
