### ISSUE TITLE
Pdf-Document not properly closed

### ISSUE THREAD

**Issue by kuronashi** [veraPDF/veraPDF-library#840]
I have the following code:
```
File file = new File("Example.pdf");
VeraGreenfieldFoundryProvider.initialise();
try {
	PDFAParser parser = Foundries.defaultInstance().createParser(file, PDFAFlavour.NO_FLAVOUR);
	parser.close();
} catch (IOException | ModelParsingException | EncryptedPdfException e) {
	e.printStackTrace();
}
file.delete(); // returns false, not possible
```
It is not possible to delete that file after closing the parser. 
In class InteralInputStream numOfFileUsers is not 0 when closing the resource (method closeResource() )

**Comment by BezrukovM** [comment]
I could not reproduce that issue on my machine (Debian Linux, open-jdk 1.7, veraPDF: validation-model-1.7.62).
@kuronashi, can you double check this and if it will reproduce, then give us more detailed information about yours OS, java version and veraPDF maven dependencies versions.

**Comment by kuronashi** [comment]
Sorry i forgot to mention those information. I could reproduce that problem in a testclass. My specs: Windows 7, oracle java 1.8 (same with java 1.7), dependencies:
<dependency>
<artifactId>pdfbox</artifactId>
<groupId>org.verapdf.pdfbox</groupId>
<version>2.0.19</version>
</dependency>
<dependency>
<artifactId>validation-model</artifactId>
<groupId>org.verapdf</groupId>
<version>1.7.9</version>
</dependency>
If you need the pdf-document, let me know.

**Comment by shem-sergey** [comment]
We were having a closer look at your issue and we could not reproduce it neither with validation-model version 1.7.9 nor in a testclass. Could you provide us with file causing troubles?
If it can't be posted in public, you can send it to my email sergey.shemyakov@duallab.com

**Comment by kuronashi** [comment]
I tried with diffrent pdfs - the problem occurs not always. Must be file-specific. I attached the file.

[Muster 10A_D 7_2017 Modell.pdf](https://github.com/veraPDF/veraPDF-library/files/1176512/Muster.10A_D.7_2017.Modell.pdf)

**Comment by a20god** [comment]
I guess this is caused by the code concatenating content streams if Contents of a page object is an array: `COSStream.concatenateStreams()`. It doesn't  close the input streams. Your sample document is also affected by https://github.com/veraPDF/veraPDF-library/issues/883.

**Comment by BezrukovM** [comment]
@kuronashi I have checked your issues again with file you have attached (Debian Linux, open-jdk 1.7) with two versions of veraPDF validation model (1.7.9 as you have specified and the latest one 1.9.9). Still can not reproduce that issue.
Maybe this can be related to reading/writing access for the folder with your file...
Can you try to reproduce it again, please? We have made a lot of improvements in working with files already.
If this won't help, then we will try to investigate it further. 
Thanks.

**Comment by a20god** [comment]
Note that Unix systems allow deleting files that are open, Windows doesn't. Therefore, you can see the problem only with Windows.

**Comment by kuronashi** [comment]
I tried with 1.10.5 and now it works. Thank you for your Support.
