### ISSUE TITLE
Status code

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#841]
## Dev Effort
1D

## Description
Currently, scripts calling veraPDF have to parse the output to find out the validation result. It would be nice if verapdf could (optionally?) terminate with one of at least 3 different status codes, for instance:

- 0: document comply / all documents comply
- 1: document does not comply / at least one document does not comply
- 2: other (error)

See System.exit().

**Comment by carlwilson** [comment]
Looking at the code the easiest to implement would be codes for the following:
In single threaded mode only:
- 0: document comply / all documents comply
- 1: document does not comply / at least one document does not comply
In any mode:
2+
 - parameter parsing problems, currently `System.exit(1)`
 - out of memory error, currently `System.exit(1)`

Curious on thoughts about edge cases, what if a PDF in a batch fails to parse?

**Comment by carlwilson** [comment]
@a20god and @bdoubrov, please see VeraPDF/VeraPDF-apps#255 for a prototypical implementation. If this is good I'll get it into the upcoming 1.14 release
