### ISSUE TITLE
Things to be ignored according to ISO 32000-1:2008 ("conforming reader", again)

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#844]
According to 11.6.5.3 of ISO 32000-1:2008, the OPI entry of a soft-mask dictionary shall be ignored.
According to 6.2.8.1 of ISO 19005-2:2011, the OPI key shall not be present and that standard says in 5.5 about conforming readers:

> The rendering and other processing of conforming files shall be performed as defined in ISO 32000-1

That is, a conforming reader shall ignore the OPI entry of a soft-mask dictionary. Yet, veraPDF complains about the OPI entry in the soft-mask dictionary of this document:

[6.2.8.1-01-unknown-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1151994/6.2.8.1-01-unknown-1.pdf)

callasPDF thinks the document is a valid PDF/A-2 document, 3-Heights sides with veraPDF and thinks the document violates 6.2.8.1 of PDF/A-2.

This is yet another instance of the "shall a PDF/A validator be a conforming reader" problem.

**Comment by bdoubrov** [comment]
I think that a validator and a conforming reader are two different things. For example, as mentioned before,
> A conforming reader may ignore any instance of the HT key in an ExtGState dictionary.

But a validator shall process HTkey to validate the requirements on the Halftone dictionaries.

**Comment by a20god** [comment]
But see your comment in https://github.com/veraPDF/veraPDF-library/issues/812!

**Comment by bdoubrov** [comment]
Just to repeat the comment here:
> Alternates of ICCBased color spaces should not be checked, as they are ignored by PDF/A compliant viewers. Otherwise there would be no way to use any ICCBased CMYK colors without a CMYK-based output intent.

It refers to just one particular case of Alternates in colour spaces. Which I'd be happy to investigate further.

**Comment by a20god** [comment]
What I tried to say with the reference to that comment is this:
- if using ICCBased CMYK colour spaces without CMYK-based output intent shall be possible, veraPDF must be a conforming reader (as Alternates needs to be ignored)
- if veraPDF is a conforming reader, it must ignore the OPI entry of a soft-mask dictionary.

In other words: if veraPDF flags the OPI entry of a soft-mask dictionary as violating PDF/A, it must also flag ICCBased CMYK colour spaces without CMYK-based output intent as violating PDF/A. veraPDF should not be a conforming reader for some rules and a non-conforming reader for other rules.

I guess that there's something wrong with ISO 19005 that puts veraPDF into this dilemma.

**Comment by bdoubrov** [comment]
Personally, I would avoid the reference to conforming readers. Validators and conforming readers are two different things. 

This leaves open the question whether validators (and veraPDF in particular) shall verify alternates of ICCBased colour spaces against all colour space requirements of PDF/A. We'll explore this question in a bit more detail, but I don't think validating ICC alternates makes any sense in scope of PDF/A.

**Comment by a20god** [comment]
I fully agree, but the wording of ISO 19005-2:2011 doesn't leave much room.

There's another problem with ISO 19005-2:2011 which cannot be "fixed" by playing the "conforming reader" card: the ColorSpace entry of a soft-mask image must be /DeviceGray (apparently, [/DeviceGray] is not allowed), but ISO 19005-2:2011 does not exempt soft-mask images from 6.2.4.3. See also https://github.com/veraPDF/veraPDF-library/issues/828. One way out would be to interpret "use" in 6.2.4.3 as "use for rendering" but that would make the content stream "0 g" (without further operators) compliant even if DefaultGray and OutputIntent are absent. Interpreting "use" as "select into a graphics state of a content stream used for rendering" might be better.

**Comment by a20god** [comment]
"slect into a graphics state ..." wouldn't be enough, Images etc. would need to be considered too.

**Comment by bdoubrov** [comment]
BTW, the TechNote with a number of clarifications from the Validation TWG is finally publsihed: https://www.pdfa.org/publication/technote-0010-clarifications-of-iso-19005-parts-1-3-for-developers-of-pdfa-creators-and-validators/

The question of DeviceGray in soft masks is addressed here (A026).

**Comment by a20god** [comment]
Thanks!
