### ISSUE TITLE
description of PDF_A/1b/6.3 Fonts/6.3.5 Font subsets/verapdf-profile-6-3-5-t01.xml

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#845]
The description of PDF_A/1b/6.3 Fonts/6.3.5 Font subsets/verapdf-profile-6-3-5-t01.xml  is from 6.3.4 rather than 6.3.5.

[6.3.5-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1152631/6.3.5-fail-1.pdf)

**Comment by bdoubrov** [comment]
Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/pull/166
