### ISSUE TITLE
PDF/A-1: Missing glyphs in fonts that are not font subsets

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#846]
According to veraPDF 1.7.63, this document is not PDF/A-1-compliant because the embedded font does not contain all referenced glyphs (the message is wrong, see  https://github.com/veraPDF/veraPDF-library/issues/845):

[6.3.4-unknown-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1152666/6.3.4-unknown-1.pdf)

However, 6.3.4 of ISO 19005-1:2005 does not specify that fonts that are **not** font subsets have to contain all referenced glyphs (NOTE 4 applies to font subsets only).

Note that this differs from PDF/A-2 which indeed requires all embedded fonts (subset or not) to contain all referenced glyphs.

**Comment by bdoubrov** [comment]
The first sentence of 6.3.5:
> As stated in 6.3.4, embedded font programs shall define all font glyphs referenced for rendering with a
conforming file.

clearly states that any embedded font program (notjust a subset) shall define all glyphs referenced for rendering (i.e. used in content streams in rendering mode other than 3).

**Comment by a20god** [comment]
Well, you're right if we ignore "As stated in 6.3.4". However, those words are there and 6.3.4 doesn't state what 6.3.5 claims 6.3.4 would state.
