### ISSUE TITLE
CharSet

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#848]
veraPDF 1.7.66 apparently does not implement A016 of TechNote 0010:

[tmp16.pdf](https://github.com/veraPDF/veraPDF-library/files/1155499/tmp16.pdf)

**Comment by a20god** [comment]
tmp16.pdf above uses an xref stream which isn't allowed for PDF/A-1. Here's a fixed version:
[tmp16b.pdf](https://github.com/veraPDF/veraPDF-library/files/1155567/tmp16b.pdf)

**Comment by shem-sergey** [comment]
There is an error in CharSet check in PDFA-1b validation profile, that is why the check is not triggered.
Mistake is here: https://github.com/veraPDF/veraPDF-validation-profiles/blob/integration/PDF_A/PDFA-1B.xml#L708

**Comment by bdoubrov** [comment]
I'm totally confused. The test file tmp16.pdf seems to be a valid PDF/A-1 file.  It contains a Type1 font subset, and its font descriptor dictionary does have the /CharSet entry as required by ISO 19005-1. 

veraPDF (1.7.87) also reports the file is valid.

The relevant rule from veraPDF PDF/A-1 validation profile says:
```
fontName.search(/[A-Z]{6}\+/) != 0 || CharSet != null
```
Which is the font is either not a subset or it shall have a CharSet entry. 

What's wrong here?

**Comment by a20god** [comment]
Probably a duplicate of https://github.com/veraPDF/veraPDF-library/issues/854, but for PDF/A-1.

**Comment by shem-sergey** [comment]
The requirements of A016 in Tech note are used only for PDF/A-2 - ISO 19005-2, 6.2.11.4.2 and PDF/A-3 – 19005-3, 6.2.11.4.2, as it said in the Tech note itself.
As I understood, the decision for PDF/A-1 was as follows: CharSet needs to be present, checking of glyph subset is not required.

**Comment by bdoubrov** [comment]
Closing this issue as invalid
