### ISSUE TITLE
Comments in embedded CMap streams and form-feed characters

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#850]
According to ISO 32000-1:2008 (9.7.5.3), the syntax of embedded CMap streams is defined by Adobe Technical Note 5014.

Adobe Technical Note 5014 (1.1) says:

> CID-keyed fonts can be read and executed
> by PostScript interpreters, but not all PostScript language usage is
> acceptable in CID-keyed fonts. These restrictions will be noted wherever
> necessary in this document, particularly in Appendices A and B.

Adobe Technical Note 5014 (B.3) says:

> ATM-J (and other simplified PostScript language parsers) generally separate
> the text of a CID-keyed font program into tokens according to PostScript
> language rules as defined in PostScript Language Reference Manual, Second
> Edition. Comments are ignored when looking for tokens.

PostScript Language Reference Manual 2nd ed (3.2.2) says:

> Any occurrence of the character % outside a string introduces a comment.
> The comment consists of all characters between the % and the
> next newline or form-feed, including regular, delimiter, space, and tab
> characters.

Note that a form-feed character terminates comments in PostScript (unlike those in PDF)!
Therefore, this document conforms to ISO 19005-2:2011:

[6.2.11.7.2-pass-5.pdf](https://github.com/veraPDF/veraPDF-library/files/1161888/6.2.11.7.2-pass-5.pdf)

**Comment by bdoubrov** [comment]
The latest version of veraPDF still reports a validation error on this document. Reopening this issue for further investigation

**Comment by bdoubrov** [comment]
Fixed in the latest dev version 1.17.45
