### ISSUE TITLE
Custom rules are not shown in the report

### ISSUE THREAD

**Issue by BezrukovM** [veraPDF/veraPDF-library#853]
Custom rules from custom validation profiles are not shown in the validation report. The problem is that all information of a rule for generating validation report takes from built in validation profile. 
I.e. if there is a custom rule with clause and test number which are not contains in built in validation profile, then we will not see that rule in the list of rules (in validation report). In case when custom rule has the same clause and test number as built in one, but its test/description/else differs from the built in one, then we will see information from the built in one.

**Comment by carlwilson** [comment]
Hi @BezrukovM this PR #870 provides a means to supply a custom profile. This won't fix the applications until the processor is tweaked also so I'll keep this open for now.
