### ISSUE TITLE
CharSet for Type 1 font

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#854]
This document:

[6.2.11.4.2-01-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1182519/6.2.11.4.2-01-fail-2.pdf)

has a (non-compact) Type 1 font with a CharSet entry that lists a character that is not defined in the font. veraPDF 1.7.91 does not detect that this violates clause 6.2.11.4.2 of ISO 19005-2:2011.

**Comment by shem-sergey** [comment]
Font in this document contains two non-.notdef glyphs, /copyright and /space. These names are correctly listed in CharSet.
6.2.11.4.2 of ISO 19005-2:2011 says the following:
> If the FontDescriptor dictionary of an embedded Type 1 font contains a CharSet string, then it shall list the character names of all glyphs present in the font program, regardless of whether a glyph in the font is referenced or used by the PDF or not.
So CharSet shall contain all glyphs from font but font not necessary shall contain all glyphs mentioned in CharSet. That is how we see this question and this is what veraPDF does.

**Comment by a20god** [comment]
I don't think that's as clear as TechNote 0010 claims.

Note that veraPDF requires CIDSet to not have a 1 for a CID that is not present in the font.
Why should CharSet be different?

(BTW, callas pdfToolbox 9.1 claims that a name is **missing** in CharSet, that's probably a bug.)

**Comment by bdoubrov** [comment]
I agree with a20god - in case of PDF/A-2 and 3 the CharSet shall identify exactly all glyphs from the font subset. That is all glyph names present in the subset. Not less, not more.
