### ISSUE TITLE
veraPDF test suite 6-1-13-t08-pass-a.pdf

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#856]
This file in veraPDF-corpus/PDF_A-2b should be renamed to fail as it is now categorized as non-compliant as of veraPDF 1.7.94 (as required by A007). There are probably other test cases that need to be updated.

**Comment by a20god** [comment]
The description in the outline also needs an update.

**Comment by bdoubrov** [comment]
Thanks for reporting this. Fixed in https://github.com/veraPDF/veraPDF-corpus/commit/fb2918fe0ce0b5fa7301f1b8c9206cd22a85a238
