### ISSUE TITLE
Character widths of Type 3 fonts

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#857]
veraPDF 1.7.94 doesn't report the incorrect character width in this document:

[6.2.11.5-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1187963/6.2.11.5-fail-1.pdf)

**Comment by bdoubrov** [comment]
Confirmed. We don't check widths consistence of Type3 fonts at the moment. Will fix it in one of the coming releases
