### ISSUE TITLE
U+FFFE in ToUnicode, again

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#858]
veraPDF 1.7.94 does not detect the mapping of <0061> to U+FFFE (forbidden by 6.2.11.7.2) in this PDF/A-2u document:

[6.2.11.7.2-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1188817/6.2.11.7.2-fail-2.pdf)

**Comment by shem-sergey** [comment]
The problem here is that rule 6.2.11.7.3 is checked only on conformance level A and this file is validated against 2u.

**Comment by a20god** [comment]
6.2.11.7.2 applies to both A and U.

**Comment by a20god** [comment]
I think your fix is incomplete, as demonstrated by this document, which maps to a sequence of Unicode code points ending in U+FFFE:
[notfixed-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1197569/notfixed-1.pdf)

**Comment by a20god** [comment]
Please do not forget to look at my previous comment...

**Comment by shem-sergey** [comment]
The solution is incomplete indeed.

**Comment by a20god** [comment]
The issue can also occur for U+FEFF (incremented from U+FEFE):
[notfixed-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1208632/notfixed-2.pdf)

**Comment by a20god** [comment]
I think this issue can be closed as veraPDF 1.11.11 reports a violation of 6.2.11.7 for notfixed-2.pdf.
