### ISSUE TITLE
Missing ToUnicode not reported if there is a CIDSystemInfo mismatch

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#859]
## Dev Effort
1D

## Description
veraPDF 1.7.94.
[6.2.11.7.2-fail-20.pdf](https://github.com/veraPDF/veraPDF-library/files/1189904/6.2.11.7.2-fail-20.pdf)
Well, it probably depends on which CIDSystemInfo is used for determining if ToUnicode is required or not.

**Comment by a20god** [comment]
I guess it's not possible to construct a document which tests the implementation of

> Type 0 fonts whose descendant CIDFont uses the Adobe-GB1, Adobe-CNS1, Adobe-Japan1 or Adobe-Korea1 character collections;

of 6.2.11.7.2 without violating other clauses of ISO 19005-2:2011. In other words, that condition is redundant.

This one:

> fonts that use the predefined encodings MacRomanEncoding, MacExpertEncoding or WinAnsiEncoding;

is also redunant, as all fonts satisfying that condition also satisfy

> Type 1 and Type 3 fonts where the glyph names of the glyphs referenced are all contained in the Adobe Glyph List or the set of named characters in the Symbol font, as defined in ISO 32000-1:2008, Annex D;

or

> non-symbolic TrueType fonts.

Did you manage to create a document for atomically testing the first two conditions ("categories") in 6.2.11.7.2?

**Comment by bdoubrov** [comment]
Good question! No, I don't think we have test files on these two cases. It is indeed not clear, whether the CMap with incorrect CIDSystemInfo shall be ignored and not used for Uncode maps. Moving this also for discussion to TWG

**Comment by carlwilson** [comment]
@bdoubrov can you confirm the status of this issue please?

**Comment by bdoubrov** [comment]
Still open at the TWG level. Please move it to the next release

**Comment by bdoubrov** [comment]
If the PDF does not comply the ISO 32k, its PDF/A status is not defined. The behavior in this case is implementation dependent.

**Comment by bdoubrov** [comment]
To fix this issue, I suggest that we report this issue as a log warning so that the user is aware of potential ISO 32000-1 issues in the document.

**Comment by bdoubrov** [comment]
Following the discussion at https://github.com/pdf-association/pdf-issues/issues/77 , we need to adjust validation of the Supplement numbers in CIDSystemInfo and in the CMap

**Comment by bdoubrov** [comment]
For the purpose of PDF/A-4 validation we fix supplement numbers for the predefined CMaps according to the minimal versions of the predefined collections defined in ISO 32000-2: Adobe-CNS1-7, Adobe-GB1-5, Adobe-Japan1-7 and Adobe-KR-9.
