### ISSUE TITLE
.notdef

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#864]
## Dev Effort
1D

## Description
veraPDF 1.7.99 reports that this document:

[notdef-T3.pdf](https://github.com/veraPDF/veraPDF-library/files/1194013/notdef-T3.pdf)

violates 6.2.11.8 of ISO 19005-2:2011 (so do 3-Heights and callas). However, ".notdef" does not have a special meaning for Type 3 fonts. If you think that just naming a glyph ".notdef" makes it the .notdef glyph, then why is this document reported as valid?

[notdef-T1c.pdf](https://github.com/veraPDF/veraPDF-library/files/1194027/notdef-T1c.pdf)

Both documents use Differences to map a character code to a glyph named ".notdef".

**Comment by a20god** [comment]
Oops, I misspelt "Differences" in notdef-T1c.pdf. Sorry.

**Comment by a20god** [comment]
Still, does a CharProc named ".notdef" really violate 6.2.11.8?

**Comment by bdoubrov** [comment]
This is an interesting question. I'll forward it to TWG

**Comment by a20god** [comment]
For Adobe Reader, .notdef **is** special for Type 3 fonts: it maps characters not listed in Differences of a Type 3 font to .notdef. However, I could find not wording in ISO 32000-1:2008 requiring that behavior for Type 3 fonts.

**Comment by a20god** [comment]
ISO 32000-1:2008 says in 9.6.5:

> Look up the glyph name in the font’s CharProcs dictionary to obtain a stream object containing a glyph description. If the name is not present as a key in CharProcs, no glyph shall be painted.

Adobe Reader paints the glyph named .notdef instead. That's wrong.

**Comment by carlwilson** [comment]
@bdoubrov what's the current status of this issue / conversation

**Comment by bdoubrov** [comment]
According to TWG, handing of .notdef is identical for Type1 and Type3 fonts. In particular, the reference to .notdef CharProc in Type3 fonts is forbidden in PDF/A compliant documents as well.
