### ISSUE TITLE
.notdef and symbolic TrueType font

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#865]
## Dev Effort
3D

## Description
Unlike other PDF/A validators, verapDF 1.7.99 reports that this document conforms to ISO 19005-2:2011:

[notdef-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1194116/notdef-3.pdf)

However, the embedded font lacks the referenced glyph, that is, the document violates 6.2.11.4.1 (and 6.2.11.7.2 because the character code is not in cmap(3,1)).

**Comment by shem-sergey** [comment]
We use the algorithm from 9.6.6.4 Encodings for TrueType Fonts, ISO 32000:2008 to determine if glyph is present in font program. According to it, we firstly check (3, 0) subtable as described, then lookup (1, 0) subtable. 
The code 101 from the document is not present in cmap (3, 0), but present in (1, 0), therefore we conclude that it is present.
Is it not a correct way of performing this check from your point of view?

**Comment by a20god** [comment]
I interpret 9.6.6.4 a bit differently: If cmap (3,0) is present, cmap (1,0) is not used, even if cmap(3,0) does not map the character code.

However, that doesn't matter for the document at hand, as cmap (3,0) doesn't map 0xf065 and cmap (1,0) doesn't map 0x65.

**Comment by shem-sergey** [comment]
Why, cmap (1, 0) maps 0x65 into 0. Isn't it enough for considering glyph to be present?

**Comment by a20god** [comment]
cmap (1,0) maps 0xe7 to GID 3 and 0xf8 to GID 4, nothing else. (It does not map 0x65.) But that doesn't matter as cmap (3,0) is present which takes precedence over cmap (1,0). cmap (3,0) maps 0xf0e7 to GID 3 and 0xf0f8 to GID 4., nothing else. (It does not map 0xf065.) There's no standard mapping for character code 101. Ergo,
> without the use of a non-standard mapping chosen by the conforming reader.

of ISO 19005-2:2011, 6.2.11.6 is violated.

The OpenType specification says:
> Regardless of the encoding scheme, character codes that do not correspond to any glyph in the font should be mapped to glyph index 0. The glyph at this location must be a special glyph representing a missing character, commonly known as .notdef. 

But that's only a should. If character code 101 is mapped to GID 0 (as suggested by the last quote), we have a violation of ISO 19005-1:2011, 6.2.11.8 (.notdef). If character code 101 is mapped to some other GID we have a non-standard mapping, violating ISO 19005-2:2011, 6.2.11.6. If character code 101 is not mapped at all, ISO 19005-2:2011, 6.2.11.4.1 is violated (glyph not defined by embedded font) . In all cases, the document does not conform to ISO 19005-2:2011.

**Comment by carlwilson** [comment]
@bdoubrov please provide an update of the current status of this question / issue.

**Comment by bdoubrov** [comment]
This one is still open. Please move it to the next release
