### ISSUE TITLE
.notdef and Type 1 font

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#866]
veraPDF 1.7.99 reports that this document conforms to ISO 19005-2:2011:

[6.2.11.8-fail-04.pdf](https://github.com/veraPDF/veraPDF-library/files/1194190/6.2.11.8-fail-04.pdf)

I think that document violates 6.2.11.8.

**Comment by shem-sergey** [comment]
As I see Type 1 font program in this file is ASCII85 encoded and data stream is corrupted. Is it the case?

**Comment by a20god** [comment]
What do you think is corrupted?
The Type 1 font of that document has an Encoding array which maps 65 (A) to .notdef.

**Comment by a20god** [comment]
Was my A85-encoded data corrupt (ie, you made your A85 decoder accept malformed data) or was there a bug in your A85 decoder?
