### ISSUE TITLE
GBK2K-H

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#869]
I think GBK2K-H and GBK2K-V are misspelt GBK2K-EUC-H and GBK2K-EUC-V, respectively, in veraPDF 1.7.109:
[6.2.11.5-pass-12.pdf](https://github.com/veraPDF/veraPDF-library/files/1200784/6.2.11.5-pass-12.pdf)
There may be other misspelt encodings.

**Comment by bdoubrov** [comment]
Thanks a lot for reporting this!

Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/pull/173
