### ISSUE TITLE
OutputConditionIdentifier in PDF/A-1

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#871]
## Dev Effort
1D

## Description
According to veraPDF 1.7.117 , this document conforms to ISO 19005-1:2005:
[OutputIntent-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1204126/OutputIntent-1.pdf)
It has an PDF/A OutputIntent that lacks an **OutputConditionIdentifier**.

Indeed, ISO 19005-1:2005 does not mention **OutputConditionIdentifier** and PDF Reference 1.4 defines only PDF/X output intent dictionaries, leaving PDF/A output intent dictionaries undefined. However, 3-Height's PDF/A validator complains about a missing **OutputConditionIdentifier** (but it also complains about a missing Document information dictionary, which is wrong) and TechNote 0002 says:

> An OutputConditionIdentifier is required for each output intent regardless of its subtype; this is a string which identifies the intended output device or production condition.

**Comment by bdoubrov** [comment]
Well, **OutputConditionIdentifier** is indeed a reqiured entry both in PDF Reference 1.4 and in ISO 32000-1. And PDF Reference 1.4, 9.10 .4 serves as a normative reference for PDF/A-1. It does mention explicitly only PDF/X output intents, but it also says:

> Other subtypes may be added in the future

The only question wheather checking the presence and validity of this entry is a part of PDF/A validation.

**Comment by carlwilson** [comment]
@bdoubrov what's the current status of this issue / question

**Comment by bdoubrov** [comment]
Still open at TWG level. Please move it to the next release

**Comment by bdoubrov** [comment]
We'll implement the warning in the logs (not a PDF/A validation error!) to cover this case

**Comment by bdoubrov** [comment]
Fix released in v1.20
