### ISSUE TITLE
DestOutputProfileRef in PDF/A output intent

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#872]
6.2.3 of ISO 19005-2:2011 says:

> In addition, the **DestOutputProfileRef** key, as defined in ISO 15930-7:2010, Annex A, shall not be present in any PDF/X OutputIntent.

veraPDF 1.7.117 categorizes this document as non-compliant due to that rule, but the document doesn't have a PDF/X output intent. The **DestOutputProfileRef** entry is in the PDF/A output intent where it is not forbidden as far as I can tell:

[6.2.3-02-pass-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1204192/6.2.3-02-pass-1.pdf)

**Comment by bdoubrov** [comment]
Yes, I think you are right. This entry in PDF/A output intent is not defined and would mean nothing, if present.

**Comment by bdoubrov** [comment]
Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/pull/174
