### ISSUE TITLE
CIDSystemInfo can be an array in some cases

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#874]
In the dictionary of a CMap stream (but nowhere else) in PDF 1.4 (and earlier) documents (which includes all PDF/A-1 documents, no matter what PDF version they claim), the CIDSystemInfo entry can be a one-element array containing the CIDSystemInfo dictionary. veraPDF 1.7.117 throws an exception for this document (which I think conforms to ISO 19005-1:2005):
[6.3.3.1-pass-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1207353/6.3.3.1-pass-3.pdf)
(3-Height's validator also claims that CIDSystemInfo must be a dictionary.)

**Comment by a20god** [comment]
Do you really want to accept an array for CIDSystemInfo for PDF/A-2 and for CIDFont dictionaries?

**Comment by bdoubrov** [comment]
I think it makes sense to accept the array of CIDSystemInfo's in case of CMaps and all PDF/A parts. We may report a warning in case of PDF/A-2 and 3. 

In case of CIDFont dictionaries, I think, the array of CIDSystemInfo's was never specified and should be considered as an ISO 32000-1 error.
