### ISSUE TITLE
CharSet of fonts which are no font subsets

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#876]
Sorry, yet another CharSet issue. The sentence about CharSet in 6.2.11.4.2 of ISO 19005-2:2011 does not mention that it applies to font subsets only, but the title of 6.2.11.4.2 makes that clear. veraPDF seems to be the only PDF/A validator that thinks this document is non-compliant due to an incomplete CharSet:
[6.2.11.4.2-01-pass-10.pdf](https://github.com/veraPDF/veraPDF-library/files/1208221/6.2.11.4.2-01-pass-10.pdf)
(Well, 3-Heights seems to ignore CharSet for PDF/A-2.)

**Comment by a20god** [comment]
This is somewhat related to https://github.com/veraPDF/veraPDF-library/issues/846.

**Comment by bdoubrov** [comment]
Agree with the issue. Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/pull/175

**Comment by a20god** [comment]
On the other hand, it could be argued that the presence of CharSet or CIDSet turns any font into a font subset (see table 124 of ISO 32000-1:2008). In that case, the two documents above would violate the XXXXXX+ prefix requirement as well as the constraints on CharSet/CIDSet.
