### ISSUE TITLE
Exception if Differences is not an array

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#877]
veraPDF 1.7.133 throws an exception for this document:
[6.3.7-02-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1210722/6.3.7-02-fail-2.pdf)
(This is an example for "X shall not contain a Y entry".)

**Comment by bdoubrov** [comment]
I agree we should not throw an exception in such case. For the moment we'll log a warning about the PDF syntax error and ignore this array. In the future we'll also make sure such PDF syntax errors also result in a PDF/A validation error. 

This will be done in the scope of issue #827
