### ISSUE TITLE
Type 3 font and ToUnicode for PDF/A-1a

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#880]
veraPDF 1.7.133 does not detect that this document violates 6.3.8 of ISO 19005-1:2005:

[6.3.8-fail-03.pdf](https://github.com/veraPDF/veraPDF-library/files/1211241/6.3.8-fail-03.pdf)

Unlike PDF/A-2a, PDF/A-1a needs ToUnicode for Type 3 fonts (as far as I can tell).

**Comment by bdoubrov** [comment]
Yes, I agree.We'll fix this. ISO 19005-1 Level A does not allow the use of Type3 fonts without ToUnicode maps, even if their glyph names belong to the known encodings.
