### ISSUE TITLE
Adobe Glyph List vs. Adobe standard Latin character set + Symbol font

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#881]
This document uses a Type 1 CFF font without ToUnicode stream:
[6.3.8-fail-04.pdf](https://github.com/veraPDF/veraPDF-library/files/1211392/6.3.8-fail-04.pdf)
Only a glyph named Deicoptic is referenced. That glyph name is in the Adobe Glyph List but neither in the Adobe standard Latin set nor in the set of named characters in the Symbol font. Therefore, the document violates clause 6.3.8 of ISO 19005-1:2005. Apparently, veraPDF checks against the Adobe Glyph List rather than the Adobe standard Latin character set (+ Symbol font). 3-Heights and callas make the same error (unless my interpretation of 6.3.8 is wrong).

**Comment by bdoubrov** [comment]
Interesting question. Indeed we check against Adobe Glyph List in PDF/A-1 as well, which might be wrong as you are saying. Will double checkand fix this in the coming release.

**Comment by bdoubrov** [comment]
Just confirmed this at TWG. So, yes, PDF/A-1 should use Adobe standard Latin character set + Symbol for mapping Type1 glyphs to Unicode (of course, provided that toUnicode map is not available).
