### ISSUE TITLE
Exception for integer in ID

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#884]
veraPDF 1.7.133.
[6.1.3-01-fail-5.pdf](https://github.com/veraPDF/veraPDF-library/files/1214005/6.1.3-01-fail-5.pdf)

**Comment by shem-sergey** [comment]
Exception is fixed in PR https://github.com/veraPDF/veraPDF-validation/pull/237/files.
For fixing handling of 3 element ID array see https://github.com/veraPDF/veraPDF-library/issues/885.
