### ISSUE TITLE
ID with three elements

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#885]
## Dev Effort
1D

## Description
ISO 19005-2:2011 (6.1.3) says about ID:

> The file trailer dictionary shall contain the ID keyword whose value shall be File Identifiers as defined in ISO 32000-1:2008, 14.4.

ISO 32000-1:2008 (14.4) says about ID:

> The value of this entry shall be an array of two byte strings

That is, a document with an ID having 3 elements cannot conform to ISO 19005-2:2011. Yet, veraPDF 1.7.137 reports that this document does:
[6.1.3-01-fail-4.pdf](https://github.com/veraPDF/veraPDF-library/files/1214009/6.1.3-01-fail-4.pdf)

**Comment by shem-sergey** [comment]
The change to be made is in this line:
https://github.com/veraPDF/veraPDF-validation-profiles/blob/integration/PDF_A/2b/6.1%20File%20structure/6.1.3%20File%20trailer/verapdf-profile-6-1-3-t01.xml#L12
lastID.length() should be equal exactly 2.

**Comment by carlwilson** [comment]
@bdoubrov this still appears to be an issue unless a TWG conversation suggests otherwise?

**Comment by carlwilson** [comment]
@bdoubrov this still appears to be an issue unless a TWG conversation suggests otherwise?

**Comment by bdoubrov** [comment]
Yes, this one is still open. We can schedule it for the next release

**Comment by bdoubrov** [comment]
Since verifying the ID array is not in the scope of PDF/A validation, the attached file will still be considered as conforming to PDF/A, but we'll report in the stderr the warning that ID array is invalid
