### ISSUE TITLE
ID in linearized PDF/A-1 document

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#889]
ISO 19005-1:2005 says:

> The file trailer referred to is either the last trailer dictionary in a PDF file, as described in PDF Reference 3.4.4 and 3.4.5, or the first page trailer in a linearized PDF file, as described in PDF Reference F.2.

That is, ID may be missing in the last trailer of the document if ID is present ino the first page trailer.

Note that the wording requiring both ID entries to be present has been replaced by TC2.

That is, this document conforms to ISO 19005-1:2005 with TC2:
[6.1.3-04-pass-5.pdf](https://github.com/veraPDF/veraPDF-library/files/1214402/6.1.3-04-pass-5.pdf)
However, veraPDF 1.7.137 reports that ID is missing.

**Comment by bdoubrov** [comment]
I think the test file indeed does not conform to ISO 19005-1:2005/Cor 2:2011. It is a Linearized PDF, and its first page trailer does not have an ID. So, I don't see what's wrong here.

**Comment by a20god** [comment]
TC2 says:

> In a linearized PDF, **if** the ID keyword is present in both the first page trailer dictionary and the last trailer dictionary, the value to both instances of the ID keyword shall be identical.

(Emphasis mine.BTW, there's a typo, "to" should be replaced by "of".) The document has only one ID entry, therefore there cannot be a difference between that ID and the other (non-existing) one.
Perhaps veraPDF implements the wording before TC2:

> In a linearized file the ID keyword shall be present in both the first page trailer and the last trailer dictionaries and the value of both instances of the keyword shall be identical.

**Comment by bdoubrov** [comment]
The file is non-conforming based on the following requirement:
> The file trailer dictionary shall contain the ID keyword.

I see veraPDF reports two validation errors on this file, which is indeed too much. But I thinkthe file still does not conform PDF/A-1 (including TC2).

**Comment by a20god** [comment]
But see the text following your quote:

> The file trailer referred to is either the last trailer dictionary in a PDF file [...] or the first page trailer in a linearized PDF file [...]

**Comment by bdoubrov** [comment]
I see what causes the misunderstanding. We were always interpreting this as follows:

If the document is linearized, then the trailer means the first page trailer of the linearized document. Otherwise it means the last trailer (by offset) in the document. In other words, this sentence unambiguously defines the term **trailer** used in the first paragraph of this clause.

This seems to be consistent with other implementations. But again I can double check at the TWG.

**Comment by a20god** [comment]
Thanks! The sentence I quoted could be interpreted either this way:

`getID () { return linearized ? first_page_trailer.id : last_trailer.id; }`

or

`getID () { if (!linearized) return last_trailer.id; else return last_trailer.id_exists ? last_trailer.id : first_page_trailer.id; }`

**Comment by a20god** [comment]
The point is that a linearized PDF document is both a PDF document and a linearized PDF document, that is, both alternatives of that sentence apply.
