### ISSUE TITLE
veraPDF sees a violation of 6.2.2 (PDF/A-2) where I see none

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#893]
veraPDF 1.9.3 also reports a questionable violation of 6.2.4.3:
[6.2.4.3-pass-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1219899/6.2.4.3-pass-3.pdf)

**Comment by bdoubrov** [comment]
Looks like veraPDF does not support [/DeviceRGB] syntax, that is a device copour space (or just /Pattern], wrapped into an array.

**Comment by a20god** [comment]
That explains the 6.2.4.3 violation but what about 6.2.2?

**Comment by bdoubrov** [comment]
I guess, veraPDF can't interpret [/DeviceRGB] and replaces it by null. Which implies that /cs is not defined at all.

**Comment by a20god** [comment]
You forgot to update this error message:
`ColorSpace array can not contain less than two elements`

**Comment by shem-sergey** [comment]
Thank you for the logging remark.
