### ISSUE TITLE
6.2.4 of PDF/A-1 and inline images

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#895]
## Dev Effort
1D

## Description
Here's a PDF/A-1 document which contains an inline image that has a key-value pair with key Interpolate and value true:
[inline-image-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1222648/inline-image-1.pdf)
According to veraPDF 1.9.3, this document violates clause 6.2.4 of ISO 19005-1:2005, but inline images are nowhere mentioned in that standard. 6.2.4 talks about image dictionaries, but inline images don't have an image dictionary (the wording in PDF Reference 1.4 quite carefully avoids the word "dictionary" for inline images). On the other hand, the restriction for "Interpolate" does not mention "dictionary".

**Comment by bdoubrov** [comment]
We've got a test file on this case in our test corpus: https://github.com/veraPDF/veraPDF-corpus/blob/staging/PDF_A-1b/6.2%20Graphics/6.2.4%20Images/veraPDF%20test%20suite%206-2-4-t03-fail-a.pdf

So far nobody complained about it. I can double check think, but I believe that the intention of PDF/A-1 was to forbid the use of interpolation for inline images as well. This just has not been expressed very precisely and had to be imrpoved in ISO 19005-2. But even ISO 19005-2 says just:

> For an inline image, the I key shall have a value of false.

omitting the case when Interpolate key is used in the inline image without the abbreviation.

**Comment by a20god** [comment]
Yes, that was the inhtention. However, it was also the intention of ISO 19005-1 to prohibit AA in page objects, see non-normative table A.2, but they forgot to add wording to that effect. veraPDF follows the existing wording (there's no normative wording prohibiting AA in page objects) and allows AA in page objects...

**Comment by carlwilson** [comment]
@bdoubrov could you confirm the status of this issue please.

**Comment by bdoubrov** [comment]
Still open and not discussed at TWG level. I suggest we also handle this in the next release

**Comment by bdoubrov** [comment]
The part between BI and ID operators does define the image dictionary for the inline image. So, the PDF/A-2 requirement:
> If an Image dictionary contains the Interpolate key, its value shall be false
is also applicable to inline images.
