### ISSUE TITLE
Question to performance optimization

### ISSUE THREAD

**Issue by dborck** [veraPDF/veraPDF-library#896]
Hi,
I do want to give the new version 1.8.1 of veraPDF a try and integrated the validation-model into my project.

Now I have a **question concerning the performance of PDF/A validation**. Is there a posibility to configure a faster validation?

With very complex PDFs I will get into problem with the performance in my application, thus I am searching for a way to parallelize some part of the validation process.
The 'FailFastValidator' will not be my first choice because in most of the usecases the PDFs to validate will not fail. 

Kind regards,
Daniela

**Comment by bdoubrov** [comment]
We are working on making veraPDF thread-safe, but at the moment we can only suggest process-based parallelization. 

We are also constrantly working on improving the performance optimizing the implementation. So, it wouldreally help us if you could provide us those files, where you think the performance is not acceptable for you. If you can't share the fileshere, feel free to send them to me directly at boris.doubrov@duallab.com

**Comment by dborck** [comment]
Here is a sample PDF/A-2B file with 979 pages containing 'Lorem Ipsum' text. The file size is about 1MB.
The validation process takes more time than I hoped it would. 
[document.pdf](https://github.com/veraPDF/veraPDF-library/files/1234643/document.pdf)

**Comment by bdoubrov** [comment]
We've implemented caching all font-related data structures, which increases performance considerably in case of large text documents with a small number of fonts. 

Would you please check if the latest veraPDF dev version works better for you? 

In particular, the validation time of the above document.pdf was reduced from 50 sec to just 10 sec the development machine.
