### ISSUE TITLE
Empty C array in annotation

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#899]
veraPDF 1.9.14 does not detect the C array in an annotation of this document without RGB output intent:
[6.5.3-04-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1230618/6.5.3-04-fail-1.pdf)
The array is empty, that is, this is at least a violation of PDF Reference 1.4.

**Comment by bdoubrov** [comment]
This is a duplicate of #827
