### ISSUE TITLE
Empty annotation dictionary for widget annotation

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#900]
## Dev Effort
1D

## Description
Having read TN 0010, I'm still confused. 6.9 of ISO 19005-1:2005 says:
> The intent of the requirements of this subclause is to ensure that there is no ambiguity about the rendering of form fields.

Yet, ISO 19005-1:2005 has only requirements for the presence of appearance **dictionaries**, not for the presence of appearance **streams**. For instance, veraPDF 1.9.14 does not report a violation of 6.5.3 or 6.9 for this document:
[6.5.3-05-unknown-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1230745/6.5.3-05-unknown-1.pdf)
For rendering, an empty appearance dictionary is exactly as good or bad as a missing appearance dictionary.

**Comment by a20god** [comment]
6.3.3 of ISO 19005-2:2011 is a bit better:
> [...] otherwise the value of the N key shall be an appearance stream.

Still, there's no requirement for the presence of appearance streams in the  case of non-button widgets, they only need an appearance subdirectory. I haven't found wording in ISO 19005-2:2001 that requires suitable appearance streams to be in the appearance subdirectory.

**Comment by carlwilson** [comment]
Again @bdoubrov could we just confirm the current status of this question

**Comment by bdoubrov** [comment]
Still to be discussed at TWG. Please keep it open

**Comment by bdoubrov** [comment]
Just to confirm that empty appearance streams are not permitted, even if this is badly worded in the PDF/A specification. The intention is, of course, to be sure that all Widget annotations (of non-zero width / height) have well-defined appearance

**Comment by bdoubrov** [comment]
Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/commit/69af28647dd5bb6f09b77fa44b69cb44baf3d8e8
