### ISSUE TITLE
A in field dictionary

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#901]
## Dev Effort
1D

## Description
This is probably a mistake in ISO 19005-1:2005. 6.9 says:

> A Widget annotation dictionary or Field dictionary shall not contain the A or AA
keys.

However, A is not defined for a field dictionary unless it is merged with an annotation dictionary, in which case the first part ("A widget annotation dictionary...") applies. Anyway, the requirement for field dictionaries is there.

Here's a document which has a field dictionary which is not merged with an annotation dictionary. It has an A entry, but veraPDF 1.9.14 reports the document conforms to ISO 19005-1:
[6.6.1-04-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1231330/6.6.1-04-fail-1.pdf)

**Comment by carlwilson** [comment]
This document still passes validation so keeping open for now, unassigned current milestone.

**Comment by bdoubrov** [comment]
Fixed in 1.18 RC
