### ISSUE TITLE
F in text annotation (PDF/A-2)

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#903]
veraPDF 1.9.14 reports a violation of this part of clause 6.3.2 of ISO 19005-2:2011:
> Text annotations should set the NoZoom and NoRotate flag bits of the F key to 1.

for this document:
[text-annot.pdf](https://github.com/veraPDF/veraPDF-library/files/1238350/text-annot.pdf)

However, that's a **should**, not a **shall**!

**Comment by bdoubrov** [comment]
Fixed in https://github.com/veraPDF/veraPDF-validation-profiles/pull/176
