### ISSUE TITLE
NeedAppearances

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#904]
Probably another duplicate of https://github.com/veraPDF/veraPDF-library/issues/827:
[6.4.1-02-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1238741/6.4.1-02-fail-2.pdf)
NeedAppearances is present and not false (it is 37), yet the document is conforming according to veraPDF 1.9.14.

**Comment by bdoubrov** [comment]
Invalid key values are still not properly reported by veraPDF
