### ISSUE TITLE
XMP Metadata in PDF documents has to be UTF-8-encoded

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#906]
## Dev Effort
1D

## Description
XMP Metadata in PDF documents has to be UTF-8-encoded according to "XMP: Extensible Metadata Platform, (September 2005), Adobe Systems Incorporated", a normative reference of ISO 32000-2:2008. See page 100.

The Metadata of "veraPDF test suite 6-7-9-t04-pass-s.pdf" is UTF-32-encoded and therefore should fail rather than pass. I guess there are other test files for other encodings, all of which shall fail unless the encoding is UTF-8.

That is, the test files need to be renamed and veraPDF should accept only UTF-8 as valid encoding for XMP metadata.

See also 6.6.2.1 of ISO 19005:2011:
> In addition, all metadata streams present in the PDF shall conform to the XMP Specification.

**Comment by a20god** [comment]
Oops, there's no such requirement in the January 2004 XMP specification referenced by ISO 19005-1:2005. The test file I mentioned above is for PDF/A-1.

**Comment by a20god** [comment]
However, veraPDF 1.9.14 accepts this document as compliant:
[2.pdf](https://github.com/veraPDF/veraPDF-library/files/1248831/2.pdf)
That's "veraPDF test suite 6-7-9-t04-pass-s.pdf" with the PDF version in the header patched to 1.7 and the conformance claimed by Metadata patched to PDF/A-2b.

**Comment by bdoubrov** [comment]
Validation of XMP packages is a bit controvercial, as XMP specifications themselves are not very strict. 

veraPDF implements the following approach for XMP validation:
- low-level parsing is done by Adobe XMP Library. And whatever low-level syntax is accepted by this library is good enough for veraPDF
- properties of predefined schemas are checked for basic types as clarified in TC0010
- whatever is explicitly stated in ISO 19005 is validated to a point (yet with a few clarifications from TC0010)

In particular, UTF32 encoding is indeed accepted by veraPDF for XMP packages and all PDF/A parts.

**Comment by a20god** [comment]
The September 2005 XMP specification is quite strict:
> The XMP must be encoded as UTF-8.

**Comment by bdoubrov** [comment]
Just to confirm that we'll add the validation for the UTF-8 encoding in the next release.

**Comment by BezrukovM** [comment]
The rules has to be added into PDF/A profiles

**Comment by bdoubrov** [comment]
Added the required validation rule: https://github.com/veraPDF/veraPDF-validation-profiles/commit/b38793bd967ea4ace9412c03222cc2fa361a5e63
