### ISSUE TITLE
Subset font question

### ISSUE THREAD

**Issue by eruiz0** [veraPDF/veraPDF-library#907]
Maybe I'm missunderstanding something, but I get the following when validating a PDF/A-2b pdf: 
```
Specification: ISO 19005-2:2011, Clause: 6.2.11.4, Test number: 4 
If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream, then it shall identify all CIDs which are present in the font program, regardless of whether a CID in the font is referenced or used by the PDF or not.

PDCIDFont
fontFile_size == 0 || fontName.search(/[A-Z]{6}\+/) != 0 || CIDSet_size == 0 || cidSetListsAllGlyphs == true   
root/document[0]/pages[0](7 0 obj PDPage)/contentStream[0](11 0 obj PDContentStream)/operators[2450]/font[0](AAAUOH+OpenSans)/DescendantFonts[0](AAAUOH+OpenSans)
root/document[0]/pages[0](7 0 obj PDPage)/contentStream[0](11 0 obj PDContentStream)/operators[2439]/font[0](AAAJCG+BitstreamVeraSansMono-Roman)/DescendantFonts[0](AAAJCG+BitstreamVeraSansMono-Roman)
```

Given that the fonts are subset fonts, shouldn't  them pass the test (fontName.search(/[A-Z]{6}\+/) != 0 ) ?

I'm using VeraPDF version 1.8.1

**Comment by bdoubrov** [comment]
The call fontName.search(/[A-Z]{6}+/) will return 0 is and only if the font name starts with XXXXXX+ prefix, where X is anycharater in the range A-Z. This is the only way to identify that the font is a subset.

In yourcase the font names are "AAAUOH+OpenSans" and "AAAJCG+BitstreamVeraSansMono-Roman", meaning they are font subsets. 

Most likely the error is related to this condition: cidSetListsAllGlyphs == true

It means that the glyph collection define dby CIDSet has to be identical to the actual glyph collection of the embedded font subset.

**Comment by eruiz0** [comment]
> Most likely the error is related to this condition: cidSetListsAllGlyphs == true

But... the rule seems to be a logical OR (||) not AND (&&). So, if fontName.search(/[A-Z]{6}+/) is true then the result should be true regardless of the other conditions . Again, maybe I'm missing something.

**Comment by eruiz0** [comment]
Sorry, my fault. Forget my last post. I didn't notice that search returns the index (so, I undestood the condition in the other sense).

Thanks @bdoubrov!

**Comment by eruiz0** [comment]
[singlepage-pdfa-2b.pdf](https://github.com/veraPDF/veraPDF-library/files/1259001/singlepage-pdfa-2b.pdf)
I have attached a sample pdf/A-2b. How can I know what is wrong? I'm a bit confused with the font-related data structures but the CIDSet seems to contain two CIDs and the font seems to have two glyphs (the CIDToGIDMap seems to be ok too). I use pdfdebug from pdfbox and ttfdump.

**Comment by a20god** [comment]
CIDToGIDMap maps CIDs 0 through 35 to GID 0 and CID 36 to GID 1.
The embedded font contains GIDs 0 and 1.
CIDSet contains CIDs 0 and 36.
It should contain CIDs 0 through 36.

**Comment by eruiz0** [comment]
Thanks @a20god ! 
It is clear for me now. 
I have fixed the CIDSet (to contain CIDs 0 through 36) and now VeraPDF is happy.
