### ISSUE TITLE
.notdef (CMap?) regression

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#908]
This document looks compliant to me:
[tmp14.pdf](https://github.com/veraPDF/veraPDF-library/files/1262733/tmp14.pdf)
However, veraPDF 1.9.30 reports that .notdef is referenced. I think this is caused by a change between 1.9.14 and 1.9.25. The only special feature of that document is the ETenms-B5-H CMap.

**Comment by shem-sergey** [comment]
The problem with the document is that CMap doesn't contain code space range information. And this is not a regression, earlier versions of veraPDF throw exception on this file if I'm not mistaken.
What is your idea of reading from stream when no code space range information is present? Are you trying to readout single bytes?

**Comment by a20god** [comment]
The document contains one font. That font uses encoding ETenms-B5-H which includes ETen-B5-H via usecmap. ETen-B5-H does declare code space ranges:

`2 begincodespacerange
  <00>   <80>
  <A140> <FEFE>
endcodespacerange`
