### ISSUE TITLE
Issues with TWG test files

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#909]
The TWG test files in veraPDF-corpus have various issues:

(a) embedded font streams with wrong Length1
(b) Tj without Tf
(c) bfchar code lengths do not match codespacerange in ToUnicode stream
(d) MCID used without StructParents
(e) CIDToGIDMap for OpenType font with CFF outlines
(f) codespacerange clash caused by usecmap
(g) corrupt data for FlateDecode, cannot decode
(h) inline image data size does not match width/height/colorspace

TWG test suite A001-pdfa1-fail-a.pdf: (a)
TWG test suite A001-pdfa1-fail-b.pdf: (a) (b)
TWG test suite A001-pdfa1-fail-c.pdf: (a)
TWG test suite A001-pdfa1-fail-d.pdf: (a) (b)
TWG test suite A001-pdfa1-pass-a.pdf: (a)
TWG test suite A001-pdfa1-pass-b.pdf: (a) (b)
TWG test suite A001-pdfa1-pass-c.pdf: (a)
TWG test suite A001-pdfa1-pass-d.pdf: (a) (b)
TWG test suite A006-pdfa1-pass-a.pdf: (c)
TWG test suite A007-pdfa2-fail-b.pdf: (d)
TWG test suite A009-pdfa1-fail-a.pdf: (c)
TWG test suite A014-pdfa1-fail-a.pdf: (e)
TWG test suite A016-pdfa2-fail-a.pdf: (c)
TWG test suite A016-pdfa2-pass-a.pdf: (c)
TWG test suite A016-pdfa2-pass-b.pdf: (d)
TWG test suite A025-pdfa2-fail-a.pdf: (f)
TWG test suite A025-pdfa2-fail-a.pdf: (d)
TWG test suite A025-pdfa2-pass-a.pdf: (f)
TWG test suite A027-pdfa3-fail-b.pdf: (c)
TWG test suite A027-pdfa3-pass-b.pdf: (c)
TWG test suite A027-pdfa3-pass-f.pdf: (c)
TWG test suite A028-pdfa2-pass-b.pdf: (g) for stream 7, (h)

**Comment by a20god** [comment]
For "verapdf TWG test suite A007-pdfa2-fail-a.pdf" it might be better to not reference the CID from a content stream as 6.1.13 also applies to CIDs that are not referenced.

**Comment by DmitryRemezow** [comment]
@a20god thank you for feedback
First part of TWG files is ready - [https://github.com/veraPDF/veraPDF-corpus/pull/104](url)
