### ISSUE TITLE
A003 and Type 3 fonts

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#910]
## Dev Effort
1D

## Description
A003 of TechNote 0010 says:
> ISO 19005-2 and 19005-3 use the term “explicitly associated Resources dictionary” exclusively for Resources entry in a Page dictionary, a Tiling Pattern dictionary, a Form XObject dictionary (including Annotation appearance streams), or a Type3 font dictionary.

veraPDF seems to use the Resources dictionary in the CharProcs content stream, if present, otherwise it would complain about undefined resource /a for character square1:
[Type3-res-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1267070/Type3-res-3.pdf)
I think this document violates 6.2.2 of ISO 19005-2:2011. The document should rather look like this:
[Type3-res-4.pdf](https://github.com/veraPDF/veraPDF-library/files/1267071/Type3-res-4.pdf)
(but callas pdfToolbox complains about inherited resources for both documents).

**Comment by a20god** [comment]
And for this document (resources for Type 3 font inherited from page), veraPDF 1.9.14 throws an exception:
[Type3-res-5.pdf](https://github.com/veraPDF/veraPDF-library/files/1269600/Type3-res-5.pdf)

**Comment by BezrukovM** [comment]
For file Type3-res-5.pdf exception has been fixed (veraPDF 1.9.60)

**Comment by carlwilson** [comment]
@bdoubrov what's the current status of the discussion here?

**Comment by bdoubrov** [comment]
This is still in discussion. Please keep it open

**Comment by bdoubrov** [comment]
veraPDF accepts Resources dictionaries both in the Type3 font dictionary and in the CharProc stream itself, as PDF 1.7 specification is somewhat unclear about this (ISO 3200-1, 7.8.3):
> For other content streams, a conforming writer shall include a Resources entry in the stream's dictionary specifying the resource dictionary which contains all the resources used by that content stream. This shall apply to content streams that define form XObjects, patterns, Type 3 fonts, and annotation.

However, PDF 2.0 fixes this ambiguity saying (ISO 32000-2, 7.8.3):
> Content streams that define the glyph descriptions of a Type 3 font shall include a Resources entry in the Type 3 font dictionary specifying all the resources used by all the content streams in the CharProcs dictionary of a Type 3 font.

So, PDF/A-4 validation should no longer accept Resource dictionaries specified in the individual CharProc stream dictionaries. To be fixed.

**Comment by bdoubrov** [comment]
Fix released in v1.20
