### ISSUE TITLE
Glyph width regression

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#913]
Somewhere between veraPDF 1.9.25 and 1.9.30, the validation result for this document switched from compliant to non-compliant due to a wrong glyph width:
[a-6.pdf](https://github.com/veraPDF/veraPDF-library/files/1280901/a-6.pdf)
The document has two annotations. Removing the Tj operator from either one changes the outcome for veraPDF 1.9.30 and later: veraPDF thinks the document is non-compliant only if both Tj operators are there, therefore I think there's something wrong with veraPDF (rather than the document).

The two annotations use two different font dictionaries having different CIDToGIDMap entries but sharing the same embedded font stream. Perhaps that confuses veraPDF.

**Comment by shem-sergey** [comment]
The key change in veraPDF that enabled this bug is font program caching.
There is a problem in CIDFontType2, namely it contains an associated CidToGidMapping. So what happens is that the same CidToGidMapping is used for both fonts.

**Comment by BezrukovM** [comment]
Fixed in https://github.com/veraPDF/veraPDF-parser/pull/322 and https://github.com/veraPDF/veraPDF-validation/pull/254 (veraPDF GF 1.9.57)
