### ISSUE TITLE
A010 and PDF/A-2 6.1.8

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#915]
## Dev Effort
2D

## Description
This document has an unreferenced font resource which violates the UTF-8 requirement of ISO 19005-2:2011, 6.1.8:
[A010-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1284668/A010-1.pdf)
According to A010 in TechNote 0010, unreferenced resources
> shall be exempt from all requirements of this part of ISO 19005 except for clauses 6.1.2 to 6.1.13

veraPDF doesn't report that violation. 3-Heights and callas pdfToolbox do.

**Comment by carlwilson** [comment]
This document is still compliant according to veraPDF 1.14, @bdoubrov could you provide a status update please.

**Comment by bdoubrov** [comment]
This issue is indeed still open. Please move it to the next release

**Comment by bdoubrov** [comment]
Fix released in v1.20
