### ISSUE TITLE
veraPDF test suite 6-1-12-t02-pass-a.pdf and literal string for Contents 

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#918]
ISO 32000-1:2008, Table 252 says about Contents in signature dictionaries:
> When ByteRange is present, the value shall be a hexadecimal string

"veraPDF test suite 6-1-12-t02-pass-a.pdf" contains a signature dictionary with a ByteRange entry. However, the Contents entry is a literal string.

Ditto for "test/PDFA-2/veraPDF test suite 6-1-12-t02-fail-a.pdf" etc.

**Comment by DmitryRemezow** [comment]
@a20god thank you for feedback
Test files were updated and added in PR - https://github.com/veraPDF/veraPDF-corpus/pull/105
