### ISSUE TITLE
multiple compressed streams issue?

### ISSUE THREAD

**Issue by eruiz0** [veraPDF/veraPDF-library#920]
Hello. I get the following error when validating twostreams_encoded.pdf : 

`Specification: ISO 19005-1:2005, Clause: 6.2.10, Test number: 1`
`A content stream shall not contain any operators not defined in PDF Reference even if such operators are bracketed by the BX/EX compatibility operators`

The error disappears if I process the file with the unencoded streams: twostreams_unencoded.pdf (generated with pdfbox cmdline: WriteDecodedDoc).

I don't understand what's happening. I use pdfbox's PDFDebugger to view the streams and everything seems to be ok.

Is there something wrong with twostreams_encoded.pdf or there is something wrong in VeraPDF?

[twostreams_unencoded.pdf](https://github.com/veraPDF/veraPDF-library/files/1328051/twostreams_unencoded.pdf)
[twostreams_encoded.pdf](https://github.com/veraPDF/veraPDF-library/files/1328052/twostreams_encoded.pdf)

I'm using VeraPDF 1.8.1

**Comment by bdoubrov** [comment]
This issue was fixed in the update 1.8.4, which is a hotfix for 1.8 release. Would you please upgrade to the latest stable version at:  http://software.verapdf.org/
