### ISSUE TITLE
veraPDF-1.8-cbp #  Offline build: "Non-resolvable parent POM for org.verapdf: ... "

### ISSUE THREAD

**Issue by beyo-ra** [veraPDF/veraPDF-library#921]
Java
> openjdk version "1.8.0_102"
> OpenJDK Runtime Environment (Zulu 8.17.0.3-linux64) (build 1.8.0_102-b14)
> OpenJDK 64-Bit Server VM (Zulu 8.17.0.3-linux64) (build 25.102-b14, mixed mode)

Maven
> Apache Maven 3.3.9
> Maven home: /usr/share/maven
> Java version: 1.8.0_102, vendor: Azul Systems, Inc.
> Java home: /usr/lib/jvm/zulu-8-amd64/jre
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "4.4.0-31-generic", arch: "amd64", family: "unix"

diff content of `/mnt/verapdf/veraPDF-1.8-cbp/maven.conf.xml`

    <localRepository>/mnt/verapdf/veraPDF-1.8-cbp/dependencies/</localRepository>
    <offline>true</offline>

ERROR #A1
`[]# sudo /opt/apache-maven-3.3.9/bin/mvn -s "/mnt/verapdf/veraPDF-1.8-cbp/maven.conf.xml" clean install > ` [dbg.out.txt](https://github.com/veraPDF/veraPDF-library/files/1349587/dbg.out.txt)

ERROR #A2
`[]# sudo mvn -s "/mnt/verapdf/veraPDF-1.8-cbp/maven.conf.xml" clean install` > [dbg2.out.txt](https://github.com/veraPDF/veraPDF-library/files/1352007/dbg2.out.txt)

ERROR #A3
`[]# debian-install-oracle-jdk.sh`
`[]# debian-install-maven.sh`
`[]# update-maven-repo.sh`
`[]# sudo mvn -s clean install` > [dbg3.out.txt](https://github.com/veraPDF/veraPDF-library/files/1352099/dbg3.out.txt)

I will retry with a completely fresh VM.

RESOLVED #A3
**Build confirmed**

ERROR #B1
`veraPDF-1.8-cbp$ java -jar veraPDF-apps/gui/target/gui-1.8.0.jar`
returns `no main manifest attribute, in ./veraPDF-apps/gui/target/gui-1.8.0.jar`

ALTERNATIVE SOLUTION #B1
Installation: `java -jar veraPDF-apps/installer/target/verapdf-izpack-installer-1.0.0.jar`
The CLI (./verapdf) is successfully executed.

ERROR #B2
`veraPDF-1.8-cbp$ ./verapdf-gui`
returns `Error: Could not find or load main class @verapdf.wrapper.gui@`

**Comment by carlwilson** [comment]
Have you refreshed your Maven repo as to per the setup instructions?

**Comment by carlwilson** [comment]
OK, this is a problem in the Maven POM as it defaults to a now stripped GUI. Have fixed and am uploading a new package.
