### ISSUE TITLE
wrong detection of embedded PostScript font

### ISSUE THREAD

**Issue by haching** [veraPDF/veraPDF-library#930]
When I validate the attached PDF, I get an unexpected error regarding font embedding:

>           <rule specification="ISO 19005-2:2011" clause="6.2.11.4" testNumber="1" status="failed" passedChecks="0" failedChecks="1">
>             <description>The font programs for all fonts used for rendering within a conforming file shall be embedded within that file, as defined in ISO 32000-1:2008, 9.9.</description>
>             <object>PDFont</object>
>             <test>Subtype == "Type3" || Subtype == "Type0" || renderingMode == 3 || fontFile_size == 1</test>
>             <check status="failed">
>               <context>root/document[0]/pages[0](4 0 obj PDPage)/contentStream[0](6 0 obj PDContentStream)/operators[19]/font[0](TheSansMonoCondensed-Plain)</context>
>             </check>
>           </rule>

However the font in question is embedded, so I guess this is a wrong detection. I prepare a simple PDF/A-2b testcase, which illustrate the problem:
[hello_pdfa2.pdf](https://github.com/veraPDF/veraPDF-library/files/1495573/hello_pdfa2.pdf) 
For testing I use the latest available Linux release package:

>  ~/products/verapdf/verapdf --version
> veraPDF 1.8.4
> Built: Mon Aug 21 14:49:00 CEST 2017

Thanks for checking this issue and thanks for proving a such good testing tool.
Rainer

**Comment by a20god** [comment]
The font is not embedded as defined in ISO 32000-1:2008, 9.9, as (I think) both Length2 and Length3 in the embedded font stream dictionary are off by two. (I don't know whether that's what veraPDF is complaining aobut.)

**Comment by haching** [comment]
I don't think, it's a problem with the Length entries. The PDF Reference defines the Length* entries as follows:

> Length1: "The length in bytes of the clear-text portion of the Type 1 font
> program"
> 
> Length2: "The length in bytes of the encrypted portion of the Type 1 font
> program after it has been decoded using the filters specified by the stream’s
> Filter entry."
> 
> Length3: "The length in bytes of the fixed-content portion of the Type 1 font
> program after it has been decoded using the filters specified by the stream’s
> Filter entry."

VeraPDF seems to count the intervening 0x0D and 0x0A characters incorrectly:

The three font sections are as follows:

"stream" keyword with separator: stream<0A>   [not counted in any section]

Section 1: %!PS...eexec<0D>             [trailing CR included; length=1140]
Section 2: <D8>...<31><D8>              [raw binary; length=29137]  
Section 3: <0D>0000...if<0D>            [leading and trailing CR included;
                                         length=544]
Final stream separator: <0A>            [not counted in any section]

The final stream separator is created according to ISO 32000-1, 7.3.8.1:
"There should be an end-of-line marker after the data and before endstream;
this marker shall not be included in the stream length."

Therefore the Length entries in the PDF are correct.

Might it be the reason, that you count the leading and trailing Carriage Return characters <0D>?

**Comment by BezrukovM** [comment]
The problem was in skip comments logic which causes parser to loose some bytes of stream and hence obtained wrong behavior. This has been fixed in https://github.com/veraPDF/veraPDF-parser/pull/330

**Comment by a20god** [comment]
@haching, eexec-decrypting the font stream data following the eexec operator results in data ending with
> closefile

followed by 0x0d, 0xe4, 0xeb, ...The 0x0d is at offset 30272 in the file and terminates the closefile token, Length1 is 1140. Therefore, Length2 must be 29133 (30272+1-1140). However, Length2 is 29137. The first unencrypted character after closefile is a 0x0d (encrypted as 0xe4, at offset 30273).

**Comment by a20god** [comment]
@haching: oops, I didn't factor in the 4 bytes removed by eexec-decryption. Length2 and Length3 of your file are correct.

**Comment by haching** [comment]
> Length2 and Length3 of your file are correct.

Thanks for the confirmation, and improving the veraPDF parser.
