### ISSUE TITLE
GUI doesn't present whether it is a GreenField- or PDF-Box-Implementation

### ISSUE THREAD

**Issue by r-pf** [veraPDF/veraPDF-library#937]
The GUI doesn't present the Infomation whether it is a GreenField- or PDF-Box-Implementation.

Also the resulting HTML-Page doesn't provides this information.

This is sometimes important, because for some PDF-Files the result differs for these two implementations.

Is it possible to add this information to the HTML-Output and the About-Dialog?

**Comment by BezrukovM** [comment]
fixed in last dev build (1.11.4)
Added parser information into About dialog and HTML reports.
