### ISSUE TITLE
GreenField: java.util.EmptyStackException in MultiThread-Context

### ISSUE THREAD

**Issue by r-pf** [veraPDF/veraPDF-library#939]
When validating multiple PDFs in multiple Threads with **GreenField 1.11.1** EmptyStackException's occurs:

	... 3 more
	Caused by: java.util.EmptyStackException
		at java.util.Stack.peek(Stack.java:102)
		at java.util.Stack.pop(Stack.java:84)
		at org.verapdf.gf.model.impl.pd.GFPDContentStream.parseOperators(GFPDContentStream.java:125)
		at org.verapdf.gf.model.impl.pd.GFPDContentStream.isContainsTransparency(GFPDContentStream.java:140)
		at org.verapdf.gf.model.impl.pd.GFPDPage.parseContentStream(GFPDPage.java:201)
		at org.verapdf.gf.model.impl.pd.GFPDPage.getcontainsTransparency(GFPDPage.java:251)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
		... 17 more

An analog exception occur when using **GreenField 1.10.5**.

**Comment by BezrukovM** [comment]
@r-pf what do you mean by multiple Threads? 
Does it mean that you start multiple threads in java code with using veraPDF API? Within the single jvm process?
And does that exception occurs during the regular veraPDF validation on the same set of files (without multiple threads)?

**Comment by r-pf** [comment]
Yes, within a single JVM we start multiple threads to validate PDFs with veraPDF.
No, the exception doesn't occur when using only one thread.

**Comment by bdoubrov** [comment]
The solution we work on, will not yet support multithreading. Instead it will provide a simple interface to run butch jobs in several parallel processes. We'll provide the CLI and the API documentation shortly

**Comment by r-pf** [comment]
I think we will need/prefer a mutli-thread solution in the API, instead of an CLI.

We intend to use veraPDF within a server which provides several services, e.g.
- inject/enrich XMP-MetaData into a PDF
- **validate PDF**

The users are some colleagues of different departments (e.g. marketing, software developer, insurance cleaks, ...).
All of them creates some PDFs and needed the services mentioned above to be performed on the PDFs.
The colleagues should be provided with a Web-Interface in which they can fill the required data and send a request to the server which performs the service and returns a modified PDF and/or an validation result.

**Comment by r-pf** [comment]
If I get it right the weak point is based on the class `org.verapdf.gf.model.impl.containers.StaticContainers` which acts as a global **static** container for some stuff for **one** PDF.
So validating of an other PDF in an other Thread will destroy the content of the global container and causes the exception mentioned above.

Is it difficult to transform `org.verapdf.gf.model.impl.containers.StaticContainers` into an *non-static* class, a new/other instance of it is used by validation of an new/other PDF?
Or as an alternative: Use one contaier per Thread - see [java.lang.ThreadLocal](https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadLocal.html)

**Comment by JSLair** [comment]
We also really need VeraPdf to be threadsafe. I'm in charge of developping an archiving system used by big French ministries for billions of documents, and PDF/A validation have to be very performant. As we work in java, it would be far more convenient to have a threadsafe library as Jhove does for other formats.

The problem your pointing is discussed in a StackOverFlow discussion: https://stackoverflow.com/questions/41936609/want-to-run-non-threadsafe-library-in-parallel-can-it-be-done-using-multiple-c

Do you foresee any work on that point?

**Comment by bdoubrov** [comment]
Theadsafeness was implemented in veraPDF 1.12
