### ISSUE TITLE
False hit related to glyph width

### ISSUE THREAD

**Issue by DietrichSeggern** [veraPDF/veraPDF-library#941]
For attached document in veraPDF 1.10.6 the following error is output:

"Specification: ISO 19005-1:2005, Clause: 6.3.6, Test number: 1	
For every font embedded in a conforming file and used for rendering, the glyph width information in the font dictionary and in the embedded font program shall be consistent.	Failed
1 occurrences	Hide
Glyph	
renderingMode == 3 || isWidthConsistent == null || isWidthConsistent == true	
root/document[0]/pages[0](9 0 obj PDPage)/contentStream[0]/operators[1716]/usedGlyphs[0](EWVPNN+ArialMT 160 0 0)"

I believe this refers to Character ID 160. The glyph width for this glyph in the width array in the PDF is at place 116 which has 277, which is 0.277 since this is in 1/1000 units. The glyph width in the font is according to the htmx table 569 divided by 2084 (as defined in the header) = 0.27783.

As far as we can see the glyph widths entries are within the limits that are usually applied (and defined in PDF/A-2) which is 1/1000.

[Orginal_1000053114_-_nur_8._Seite-blind_out2.pdf](https://github.com/veraPDF/veraPDF-library/files/1728536/Orginal_1000053114_-_nur_8._Seite-blind_out2.pdf)

**Comment by a20god** [comment]
Note that the document is PDF/A-1, not PDF/A-2.

Do you agree with the following analysis?

160 is not an encoding of a character in WinAnsiEncoding. Therefore this note in appendix D of PDF Reference 1.4 applies: "In WinAnsiEncoding, all unused codes greater than 40 map to the bullet character." (40 is octal.) Then, "bullet" is mapped to U+2022. The (3, 1) subtable of cmap does not map U+2022. The post table doesn't map "bullet" either. The result is implementation-defined. PDF/A-1 does not prohibit implementation-defined mappings.

How do you obtain a GID for which hmtx contains 569?

**Comment by DietrichSeggern** [comment]
The nonbreakingspace encoding is defined in Appendix D footnote 6: 
"The space character is also encoded as 312 in MacRomanEncoding and as 240 in
WinAnsiEncoding. This duplicate code signifies a nonbreaking space; it is typographically the
same as SPACE (U+0020)."
In this PDF the post table maps nbspace to 44 and that you will find in the htmx as described before.

**Comment by bdoubrov** [comment]
This sounds like an implementation specific logic. In case of PDF/A we should reply only on the Unicode cmap (3,1) of the embedded font and use Unicode value of the SPACE character, ie. U+0020, which maps to GID=50 in this case.

**Comment by DietrichSeggern** [comment]
Footnote 6 clearly says that it refers to a nonbreaking space which is a valid Unicode character http://www.fileformat.info/info/unicode/char/00a0/index.htm. If there is width information in the font for this character that has to be used, so I really do not see anything implementation spec here.

**Comment by a20god** [comment]
I missed footnote 6. With footnote 6, 160 (240 octal) is mapped to the name "space" (not "nbspace"!), which is mapped to U+0020, which is mapped to GID 50, which has a width of 0. Still no match with the Width entry.

Note that footnote 6 is attached to the entry for "space".

**Comment by DarrenHoffman** [comment]
Acrobat XI Pro doesn't flag this width inconsistency, does anybody have any idea why? I have a similar issue in another document with a regular space glyph having 0 width in the font but not the width's array that IS flagged by Acrobat XI, but NOT by Acrobat 2015 (or DS or whatever it's called).

**Comment by DarrenHoffman** [comment]
[sample_space_character(Preflight).pdf](https://github.com/veraPDF/veraPDF-library/files/2314941/sample_space_character.Preflight.pdf)

Hi, sorry I didn't respond sooner. This file was created with Acrobat Pro DC and verifies in  I believe, but does not verify in Acrobat XI Pro (or apparently 9 or 10 FWIW). It does not verify in veraPDF either. The space character's width does NOT match the font width (226 vs 0) unless I am mistaken about something. 
I have speculated that perhaps Acrobat had decided that stand-alone space characters did not need to adhere to this particular PDF/A rule if such space characters do not have any affect on the layout of other visible text. In a certain sense such space glyphs could perhaps be treated equivalent to text rendered in mode 3. So one could argue this behavior is in accordance "with the spirit of the law" though it seems to not be in accordance with "the letter of the law".
We actually have a customer complaining about this but I am unsure how or what I should be trying to justify to them.

**Comment by DietrichSeggern** [comment]
Hi Darren,
Thank you for the file.
Preflight (written by us, callas) finds for both width entries the same value 226. I have attached two screenshots from Preflight's "Browse internal PDF structure" available via the options menu to show what it finds.
1. I think we are in agreement on the Widths array:
![image](https://user-images.githubusercontent.com/28397656/44546512-76dc4180-a718-11e8-9f9a-dfbaffb81bf8.png)
2. For the width of the glyph in the font the Charset says that the space is on position 1 and that glyph is empty but has 226 endchar.
![image](https://user-images.githubusercontent.com/28397656/44546622-c7539f00-a718-11e8-82e3-435ccc59d05b.png)
The reason is definitely not that the requirement does not apply to space glyphs, it definitely does.
Dietrich

**Comment by DarrenHoffman** [comment]
I see, thanks. I guess I need to look into my font parsing code a little closer. I guess older versions of Acrobat must not be reading the width information correctly from this particular font either.
Again, thanks a lot. I had jumped to the wrong conclusion after all. This was very helpful, thanks.

**Comment by DarrenHoffman** [comment]
It is my understanding that it is technically invalid to have the same SID assigned to two different glyphs. The SIDs are supposed to be unique.

**Comment by DarrenHoffman** [comment]
So perhaps there is no PDF/A rule explicitly mentioning this case, but basically the font is invalid, no? And the correct glyph for the \space character is not well defined. So this would really seem to constitute a violation of PDF/A standard, right? Since the correct glyph is not well defined you could probably even apply rule 6.3.5 paragraph one from the PDF/A-1 spec.

**Comment by DietrichSeggern** [comment]
Hi Darren,
I think that you are right that this is at least problematic from a CFF point of view.
From the PDF/A view, this is in my point of view not clear. During several discussions we came to the conclusion that a PDF/A validator should only flag violations of a) explicit PDF/A requirements or b) violations that limit the rendering of a PDF (for conformance level B). Since rendering is not limited (1 and 43 are rendering in the same way) I would say that this should not be considered as a PDF/A violation.
But I think this deserves some further discussion on TWG level of the PDF Association and I will take it to there.
Thanks for bringing this up,
Dietrich

**Comment by DarrenHoffman** [comment]
Thank you. But I am not clearly convinced that rendering is not potentially affected: I am not 100% sure the best way to think about this issue nor am I confident in exactly how the combined specs should be interpreted, but I am still concerned that the rendering is not deterministic. To me a viewer should be able to use either the widths array or the widths from the font without worrying about it. If they use the widths from the font they will be rendering with different widths if they use GID 1 vs 43, and while this doesn't matter for standalone space characters, it certainly would matter if the character were in the middle of a show text string of visible glyphs, no?) 
I hope I am making sense. I am sort of thinking as typing here.

**Comment by DietrichSeggern** [comment]
Yes, that makes sense and in addition the glyphs might actually also render differently from each other (which is not the case in THIS case). As I have said: I will make sure that we will discuss this in one of the next Technical Working Group meetings of the PDF Association...

**Comment by DarrenHoffman** [comment]
> Yes, that makes sense and in addition the glyphs might actually also render differently from each other (which is not the case in THIS case). As I have said: I will make sure that we will discuss this in one of the next Technical Working Group meetings of the PDF Association...

Do you know by when that might happen to actually be discussed (it it hasn't already)? How frequently do TWG meetings occur?

**Comment by DietrichSeggern** [comment]
Next meeting is scheduled for October 11 at 4pm CEST. Usually we meet every one or two months.

**Comment by DarrenHoffman** [comment]
yikes

**Comment by DarrenHoffman** [comment]
> Next meeting is scheduled for October 11 at 4pm CEST. Usually we meet every one or two months.

Did the group have a chance to discuss this issue at all?

**Comment by DietrichSeggern** [comment]
This was discussed but sent back to the TWG mailinglist. The topic will be discussed there. If there is a resolution we will bring that to your attention.

**Comment by bdoubrov** [comment]
Final resolutions:
- The space (U+0020) character is also encoded as 312 (octal) in MacRomanEncoding and as 240 (octal) in WinAnsiEncoding. Windows Code Page 1252 associates this character code with the non-breaking space (U+00A0) character. If the PDF producer intends to map this character code to the "nonbreakingspace" character from the Adobe Glyph List, this may be specified using a Differences array in the Encoding dictionary.

- all glyph names in the CFF font Charset array shall be unique. This is implicit in the CFF specification (Adobe Technical Note 5176), but unfortunately not explicitly stated. As the font in the sample above  has two glyphs with identical glyph name "space", it is considered invalid with further undefined PDF/A validation status.

This concludes the discussions above, and I'm closing this issue for now.
