### ISSUE TITLE
GreenField: Tmp-file stays open after validation 

### ISSUE THREAD

**Issue by r-pf** [veraPDF/veraPDF-library#942]
As mentioned in [GreenField: java.util.EmptyStackException in MultiThread-Context#939](https://github.com/veraPDF/veraPDF-library/issues/939) we intend to use veraPDF within a server context.

When validating e.g. [HelloWorld.pdf](https://github.com/veraPDF/veraPDF-library/files/1756689/HelloWorld.pdf) with Greenfield-implementation 1.11.3 it occurs that in the tmp-directory a tmp-file will be created.
This tmp-file will **stay open** (= unclosed) **after validation** of *HelloWorld.pdf*, **if the JVM doesn't 
terminates** (server-context).

This causes two problems:
- Available file-handles will be descreased because they are consumed by unclosed tmp-files
- The free disk-space in the tmp-partition will descrease because of undeleted tmp-files

So - please **close** and **delete** the tmp-files if they aren't needed any longer.

**Comment by BezrukovM** [comment]
@r-pf I can't reproduce that problem on my machine (Linux Debian 8, java 8). 
Can you please provide us you configuration (OS, java version) and maybe the temp file which stay opened, please?

**Comment by r-pf** [comment]
Her is the source-code I used to reproduce the problem:
  
    public static void main(
      String [] args
    )throws IOException, ModelParsingException, EncryptedPdfException, ValidationException
    {
      VeraPDFFoundry  veraPDFFoundry;
      boolean         isCompliant;
      
      VeraGreenfieldFoundryProvider.initialise();
      
      veraPDFFoundry = Foundries.defaultInstance();
      
      try( InputStream  inputStream = GFTmpFileMain.class.getResourceAsStream("HelloWorld.pdf");
           PDFAParser   pdfaParser  = veraPDFFoundry.createParser(inputStream) ){
        PDFAValidator     pdfaValidator;
        ValidationResult  validationResult;
        
        pdfaValidator = veraPDFFoundry.createValidator(pdfaParser.getFlavour(), false);
        
        validationResult= pdfaValidator.validate(pdfaParser);
        
        isCompliant = validationResult.isCompliant();
      }
      
      System.err.println(isCompliant);
      
      while(true); // <- to simulate a server - which doesn't terminate after one validation
    }
  
I startet the program with `-Djava.io.tmpdir=/tmp/GFTmpFileMain` to separate the tmp-Files of the program from the other files in `/tmp`. `/tmp/GFTmpFileMain` is a new directory I created for that purpose.

With `lsof +d /tmp/GFTmpFileMain` I can inspect the open files in `/tmp/GFTmpFileMain`.

I use the following dependency (but it occurs also with other versions)

    <dependency>
      <groupId>org.verapdf</groupId>
      <artifactId>validation-model</artifactId>
      <version>1.11.3</version>
    </dependency>

My OS is 
  `$ uname -a`
  `Linux c15al 4.14.11-1-ARCH #1 SMP PREEMPT Wed Jan 3 07:02:42 UTC 2018 x86_64 GNU/Linux`

It's also reproducable with Windows 7 - Test of open file: While the tmp-file is open Windows 7 doesn't allow to delete it.
