### ISSUE TITLE
Font not recognized as standard font if encoding has Differences entry

### ISSUE THREAD

**Issue by marhop** [veraPDF/veraPDF-library#946]
I encountered a PDF/A-2b file that uses a standard font (Type1 Helvetica) combined with an encoding dictionary that contains a Differences entry to remap some character codes to different character names (don't ask me why). I cannot share the file, but the relevant parts look like this in iText RUPS:

![RUPSscreenshot](https://user-images.githubusercontent.com/5216507/37032502-12dddcc6-2143-11e8-8ed9-714ab26caadd.png)

When I throw this file at Adobe Professional (Preflight) and Callas they say it is valid, but veraPDF complains about missing entries in the font dictionary:

    <buildInformation>
      <releaseDetails id="core" version="1.11.2" buildDate="2018-02-07T12:34:00+01:00"></releaseDetails>
      <releaseDetails id="validation-model" version="1.11.4" buildDate="2018-02-26T08:46:00+01:00"></releaseDetails>
      <releaseDetails id="gui" version="1.11.5" buildDate="2018-02-26T08:54:00+01:00"></releaseDetails>
    </buildInformation>
    
    <validationReport profileName="PDF/A-2B validation profile" statement="PDF file is not compliant with Validation Profile requirements." isCompliant="false">
      <details passedRules="118" failedRules="3" passedChecks="1693294" failedChecks="3">
        <rule specification="ISO 19005-2:2011" clause="6.2.11.2" testNumber="5" status="failed" passedChecks="0" failedChecks="1">
          <description>All fonts and font programs used in a conforming file, regardless of rendering mode usage, shall conform to the provisions
  		in ISO 32000-1:2008, 9.6 and 9.7, as well as to the font specifications referenced by these provisions.
  		FirstChar - integer - (Required except for the standard 14 fonts) The first character code defined in the font's Widths array</description>
          <object>PDSimpleFont</object>
          <test>isStandard == true || LastChar != null</test>
          <check status="failed">
            <context>root/document[0]/pages[1](6 0 obj PDPage)/contentStream[0](17 0 obj PDContentStream)/operators[408]/font[0](Helvetica)</context>
          </check>
        </rule>
        <rule specification="ISO 19005-2:2011" clause="6.2.11.2" testNumber="6" status="failed" passedChecks="0" failedChecks="1">
          <description>All fonts and font programs used in a conforming file, regardless of rendering mode usage, shall conform to the provisions
  		in ISO 32000-1:2008, 9.6 and 9.7, as well as to the font specifications referenced by these provisions.
  		Widths - array - (Required except for the standard 14 fonts; indirect reference preferred) An array of (LastChar − FirstChar + 1) widths</description>
          <object>PDSimpleFont</object>
          <test>isStandard == true || (Widths_size != null &amp;&amp; Widths_size == LastChar - FirstChar + 1)</test>
          <check status="failed">
            <context>root/document[0]/pages[1](6 0 obj PDPage)/contentStream[0](17 0 obj PDContentStream)/operators[408]/font[0](Helvetica)</context>
          </check>
        </rule>
        <rule specification="ISO 19005-2:2011" clause="6.2.11.2" testNumber="4" status="failed" passedChecks="0" failedChecks="1">
          <description>All fonts and font programs used in a conforming file, regardless of rendering mode usage, shall conform to the provisions
  		in ISO 32000-1:2008, 9.6 and 9.7, as well as to the font specifications referenced by these provisions.
  		FirstChar - integer - (Required except for the standard 14 fonts) The first character code defined in the font's Widths array</description>
          <object>PDSimpleFont</object>
          <test>isStandard == true || FirstChar != null</test>
          <check status="failed">
            <context>root/document[0]/pages[1](6 0 obj PDPage)/contentStream[0](17 0 obj PDContentStream)/operators[408]/font[0](Helvetica)</context>
          </check>
        </rule>
      </details>
    </validationReport>

I think the actual problem is that veraPDF does not recognize the font as a standard font because of the Differences entry, see [the source code](https://github.com/veraPDF/veraPDF-parser/blob/bfbf7313c4d63bc72089a743fb39fc119e93bf14/src/main/java/org/verapdf/pd/font/type1/PDType1Font.java#L188). It seems to think that no font with such an entry can ever be a standard font. However, the restrictions regarding this entry in ISO 19005-2, section 6.2.11.6 apply only to TrueType fonts, not to Type1 fonts!

What do you think?

Thanks,
Martin

**Comment by marhop** [comment]
By the way, ISO 32000-1, section 9.6, table 111 has the same requirements for a font dictionary's FontDescriptor entry as for the FirstChar, LastChar and Widths entries mentioned in the error message quoted above: Required except for the standard 14 fonts.

If the above error were indeed an error, shouldn't the FontDescriptor entry then be stated as missing as well?

**Comment by bdoubrov** [comment]
Martin, thanks a lot for reporting this issue. Your analysis is fully correct. Indeed, veraPDF does not allow differences in the encoding of any of the 14 standard fonts. 

I think, proper handling of Differences array is not possible if /FirstChar, /LastChar and /Widths array are missing. It makes glyph widths ambiguous. This is why we assume that the font is no longer "Standard" if Differences are present. 

We'll double check this within our expert group and, if this is not a correct interpretation, we'll fix this in veraPDF code.

**Comment by bdoubrov** [comment]
We'll remove the requirement to have no Differences for the standard fonts. However, I note that as soon as the font is embedded, it is no longer treated as a standard one.

And the font embedding is required in PDF/A for all fonts, unless they are used exclusively in text rendering mode 3.
