### ISSUE TITLE
Absolute path in `config/plugins.xml`

### ISSUE THREAD

**Issue by r-pf** [veraPDF/veraPDF-library#949]
## Dev Effort
1D

## Description
The result of the installation of e.g. `verapdf-pdfbox-1.10.6-installer.zip` is in principle like an unzipped archive-file. (no modification in e.g. an registry is performed, all files are located within a single sub-directory).

Because of e. g. reorganization of departments we are forced to reorganize the location of some similar programs within our file-system.

Before moving the installation of veraPDF-GUI from one location to an other I checked the content of some files of the installations.
In the file `config/plugins.xml` I found that value of element `pluginJar` is an absolute path.

Is it possible to change this value in future releases to a relative path, which is relative to the installation directory (the System-Property `app.home` set in `verapdf-gui.bat` reflects this directory)?

This modification allows to move the installation from one directory to an other.
(Moving is faster than re-installation)

**Comment by carlwilson** [comment]
Closed by veraPDF/veraPDF-plugins#22 and #1023 combined. Added relative path support and improved warnings when things go wrong.
