### ISSUE TITLE
Question: Is 6.2.11.4-1 really an error?

### ISSUE THREAD

**Issue by Chlara** [veraPDF/veraPDF-library#953]
Hi

veraPDF 1.10.4 claims that some documents violates 6.2.11.4-1 of ISO 19005-2:2011:

**PDF/A-2 Rule: 6.2.11.4-1**
- Requirement: The font programs for all fonts used for rendering within a conforming file shall be embedded within that file, as defined in ISO 32000-1:2008, 9.9. 
- Error details: The font program is not embedded

However, three other PDF/A validators (callas, 3-Heights, intarsys) think that the document is compliant. Moreover, in ISO 32000-1:2008, 9.9 is also written, "**A font program may be embedded in a PDF file as data contained in a PDF stream object**".

Unfortunately, the documents are confidential :-(

I am not sure if this should really be an error or not (like the other PDF/A validators). Can you please check it?

Thanks,
Chlara

**Comment by BezrukovM** [comment]
Fixed in 1.11.19
https://github.com/veraPDF/veraPDF-parser/pull/350
