### ISSUE TITLE
org.verapdf.pdfbox:pdfbox:2.0.19 is a jar while others are bundles

### ISSUE THREAD

**Issue by r-pf** [veraPDF/veraPDF-library#954]
Hi,
is there a reason for artifact `org.verapdf.pdfbox:pdfbox:2.0.19` to be (only) a jar, whereas the artifacts `fontbox`, `preflight` and `xmpbox` of the same groupId `org.verapdf.pdfbox` and version `2.0.19` are bundles?
(The corresponding artifacts with groupId `org.apache.pdfbox` and version `2.0.8` are all bundles.)

Unless artifact `pdfbox` of groupId `org.verapdf.pdfbox` is also a bundle, the other artifacts can't be used as bundles within OSGi-context.

Mixing the artifacts and versions from groupIds `org.verapdf.pdfbox` and `org.apache.pdfbox` can't be practiced, because e.g. `org.apache.pdfbox.pdmodel.font.Standard14Fonts.addAFM(String, String)` of `org.apache.pdfbox:pdfbox:2.0.8` calls `org.apache.fontbox.afm.AFMParser.parse(boolean)` which is present in `org.apache.pdfbox:fontbox:2.0.8`, but not in `org.verapdf.pdfbox:fontbox:2.0.19` (it isn't backward-compatible).

So please modify the build-process of artifact `pdfbox` in a way which results this artifact as bundle also (according to groupId `org.apache.pdfbox`).

**Comment by carlwilson** [comment]
Hi @r-pf, this build merely reflects PDFbox’s build strategy and is not something we’d look to change.
