### ISSUE TITLE
Differnet Result for GreenField- and PDFBox-Implementation 2

### ISSUE THREAD

**Issue by r-pf** [veraPDF/veraPDF-library#955]
For the file
[SigFields_Normal_ReadOnly_Required.pdf](https://github.com/veraPDF/veraPDF-library/files/1915916/SigFields_Normal_ReadOnly_Required.pdf) 
the PDFBox-implementations 1.10.2 and 1.11.6 reports an error - means the file is invalid - whereas 
the Greenfield-implementations 1.10.5 and 1.11.12 reports that the PDF-File is valid.

Which result is correct?

**Comment by a20god** [comment]
That document violates at least 12.7.4.5 ("the field value (V), if present, shall be a signature dictionary") and 7.5.4 ("For a file that has never been incrementally updated, the cross-reference section shall contain only one subsection") of ISO 32000-1:2008 and therefore 5.1 ("Conforming PDF/A-2 files shall adhere to all requirements of ISO 32000-1 as modified by this part of ISO 19005") of ISO 19005-2:2011 and is therefore not a valid PDF/A document.
However, veraPDF does not check such stuff so you must be talking about something else...
