### ISSUE TITLE
LaTeX pdfx package - PDF/A-1b: Adobe Preflight verification passes and veraPDF fails

### ISSUE THREAD

**Issue by wollmich** [veraPDF/veraPDF-library#957]
I have the following problem with veraPDF V1.10.6:

I can create a PDF/A-1b using LaTeX using the pdfx package.
If I verify this PDF with Adobe Preflight it passes.
If I use verPDF to verify the PDF it fails and I get the following error ISO 19005-1:2005, Clause: 6.3.4, Test number: 1.

See as well https://tex.stackexchange.com/questions/426946/pdf-a-1b-adobe-preflight-verification-passes-and-verapdf-fails

The font is embed in the PDF file, so it seems to be a problem of veraPDF

See the following file: [test 1b.pdf](https://github.com/veraPDF/veraPDF-library/files/1920726/test.1b.pdf)

**Comment by bdoubrov** [comment]
I confirm this has been an issue in PostScript font parser in the 1.10.6 release. It has been fixed in dev. Please check the latest dev version: 
http://software.verapdf.org/develop/1.11/verapdf-greenfield-1.11.19-installer.zip

**Comment by bdoubrov** [comment]
Thanks for bringing this to us. I'll open a new issue, as this seems to be different one
