### ISSUE TITLE
ASInputStream not closed

### ISSUE THREAD

**Issue by B748** [veraPDF/veraPDF-library#958]
As in #840 and #882 I have a couple of Files with remaining open handles. Temporary Files remain undeleted when creating a parser with a FileInputStream argument:

        File file = new File(...)
        try [...] Foundries.defaultInstance().createParser(new FileInputStream(file))) [...]

and source files remain undeletable until JVM closes when creating a parser with a File argument:

        File file = new File(...)
        try [...] Foundries.defaultInstance().createParser(file)) [...]

Current config:

        <dependency>
            <groupId>org.verapdf</groupId>
            <artifactId>core</artifactId>
            <version>1.10.3</version>
        </dependency>

        <dependency>
            <groupId>org.verapdf</groupId>
            <artifactId>validation-model</artifactId>
            <version>1.10.5</version>
        </dependency>

I stepped through the code and noticed that the `numOfFileUsers` property does not reach 0 for the source after completing the validation. The property of temporary files created throughout the process though drop to 0 leading to their deletion in the `closeResource()` method of the respective class (`ASFileInStream` or `InternalInputStream`).
Furthermore only creating the parser already produces this issue.

I tried this with different PDFs and ended up with the following results:

PDF-Type | max val `numOfFileUsers` | remaining val `numOfFileUsers`
------------ | ------------- | -------------
PDF  | 4 | 1
PDF/A-1a | 7 | 1
PDF/A-1b | 11 | 2
PDF/A-2a | 10 | 2
PDF/A-2b | 13 | 3
PDF/A-2u | 13 | 3
PDF/A-3a | 13 | 3
PDF/A-3b | 16 | 4
PDF/A-3u | 16 | 4

Complete code:

    private static String verifyPDFFile(File file) {
        VeraGreenfieldFoundryProvider.initialise();

        try (PDFAParser parser = Foundries.defaultInstance().createParser(file)) {
            PDFAValidator validator = Foundries.defaultInstance().createValidator(parser.getFlavour(), false);

            ValidationResult result = validator.validate(parser);

            validator.close();
            // parser.close();

            if (result.isCompliant()) {
                return "PDF/A-" + result.getPDFAFlavour().getId();
            }

        } catch (IOException | ModelParsingException | EncryptedPdfException e) {
            e.printStackTrace();
        } catch (ValidationException e) {
            e.printStackTrace();
        } catch (NoSuchElementException e) {
            return "PDF";
        }

        return "PDF";
    }

Is it possible that there are on or more missing closeResource() calls in the createParser() code?

**Comment by bdoubrov** [comment]
Would you please test this with the latest dev version? There were several fixes for this problem, but they are available only in the latest dev version (1.11.22).

**Comment by B748** [comment]
Not sure if I tested the right dev version, I was unable to find a definite designated code `1.11.22`. Would you be so kind to post a link?

Tried it whith a clone of the current integration branch and some code designated 1.11.4 (?) though...

Testing both codes the results were unchanged. The amount of remaining `numOfFileUsers` are identical to those in release `1.10.3`

**Comment by BezrukovM** [comment]
@B748 Can you test again with new versions, please?
`    <dependency>
        <groupId>org.verapdf</groupId>
        <artifactId>core</artifactId>
        <version>1.11.6</version>
    </dependency>

    <dependency>
        <groupId>org.verapdf</groupId>
        <artifactId>validation-model</artifactId>
        <version>1.11.23</version>
    </dependency>`

Note that org.verapdf:parser version in maven downloaded dependencies has to be at least 1.11.15 (nested dependency from org.verapdf:validation-model).
I have made some fixes relating to remaining temp files for https://github.com/veraPDF/veraPDF-library/issues/959 issue.
In case if it doesn't help: can you attach here your pdf files? Or, if they are not public, then maybe you could send them to me by email? (maksim.bezrukov@duallab.com)

**Comment by B748** [comment]
Simple PDF-testfiles created with ABBYY Finereader 14. As a side note: I noticed that in some of the new code auto-specification didn't work reliably.

The released versions 1.10.3 & 1.10.5 (see above) did classify correctly though.

[test.pdf](https://github.com/veraPDF/veraPDF-library/files/1946536/test.pdf)
[test.1a.pdf](https://github.com/veraPDF/veraPDF-library/files/1946528/test.1a.pdf)
[test.1b.pdf](https://github.com/veraPDF/veraPDF-library/files/1946529/test.1b.pdf)
[test.2a.pdf](https://github.com/veraPDF/veraPDF-library/files/1946530/test.2a.pdf)
[test.2b.pdf](https://github.com/veraPDF/veraPDF-library/files/1946531/test.2b.pdf)
[test.2u.pdf](https://github.com/veraPDF/veraPDF-library/files/1946532/test.2u.pdf)
[test.3a.pdf](https://github.com/veraPDF/veraPDF-library/files/1946533/test.3a.pdf)
[test.3b.pdf](https://github.com/veraPDF/veraPDF-library/files/1946534/test.3b.pdf)
[test.3u.pdf](https://github.com/veraPDF/veraPDF-library/files/1946535/test.3u.pdf)

When I tested the `new FileInputStream(file)` variant the remaining files were always the source files (i.e. the stream saved to the drive) - never one of the temp files which were created during the specification testing (I could observe them beeing created and deleted from disk in the process). Having said that I am not sure if a fix for #959 adresses the same root cause...

**Comment by BezrukovM** [comment]
@B748 I have tested last dev version with new fixes on your code sample with all your files attached to previous comment. I don't have any left temp files at the end. Can you double test again with new versions, please?
`<dependency>
        <groupId>org.verapdf</groupId>
        <artifactId>core</artifactId>
        <version>1.11.6</version>
    </dependency>

<dependency>
    <groupId>org.verapdf</groupId>
    <artifactId>validation-model</artifactId>
    <version>1.11.24</version>
</dependency>`

Note that org.verapdf:parser version in maven downloaded dependencies has to be at least 1.11.16 (nested dependency from org.verapdf:validation-model).
I have made some fixes relating to remaining temp files for https://github.com/veraPDF/veraPDF-library/issues/959 issue.
If everything will be ok, then feel free to close the issue. In other case: let me know, please, the code you using and failed pdf files.
Thank you.

**Comment by B748** [comment]
@BezrukovM: Allright, will test again.

Please make sure that 1.11.24 is available on Maven. I can use the `core` artifact 1.11.6 and v1.11.23 of the `validation-model`. No success with 1.11.24 though.

Executing my code with 1.11.6 & 1.11.23 threw this Exception when creating the `PDFAParser`:
```
java.lang.NoClassDefFoundError: org/verapdf/model/baselayer/Object
	at org.verapdf.pdfa.VeraFoundry.createParser(VeraFoundry.java:80)
	at org.verapdf.pdfa.VeraFoundry.createParser(VeraFoundry.java:86)
```
I guess this is due to some wrong pre-1.11.16 `org.verapdf:validation-model` dependency you were noting in your post?

**Comment by B748** [comment]
OK. I finally managed to find your artifacts on JFrog artifactory.org (I was using intelliJ with standard Maven repo).

I can confirm that the files are deletable and there are no left-over tmp-files in `1.11.6` & `1.11.24`.

However:
Letting the software decide which flavour the file has does identify type "a" pdfs only now. I'll open a new issue if this proves consistent after some more testing...

Thanks so far!
