### ISSUE TITLE
PDF/A-3: AF in unreferenced CharProc of a Type 3 font

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#973]
## Dev Effort
2D

## Description
The document
[6.8-fail-12.pdf](https://github.com/veraPDF/veraPDF-library/files/2244380/6.8-fail-12.pdf)
differs from the one in
https://github.com/veraPDF/veraPDF-library/issues/809
by not referencing the character that has the AF marked-content property.

Both callas pdftoolBox and 3-Heights PDF Validator report that 6.8-fail-12.pdf does not conform to PDF/A-3b as the embedded file is not referenced by an AF entry, whereas veraPDF 1.12.1 claims that the document conforms to PDF/A-3b. Who's correct?

**Comment by carlwilson** [comment]
veraPDF 1.14 still declares the document as valid, @bdoubrov could you provide a status update please.

**Comment by bdoubrov** [comment]
The embedded file is referenced from a Type3 CharProc. The fact that this CharProc is not used anywhere on the page, is not relevant for verifying this PDF/A requirement.
