### ISSUE TITLE
Form XObjects and font in inherited graphics state

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#975]
According to veraPDF 1.12.1, this document:
[xobject-1.pdf](https://github.com/veraPDF/veraPDF-library/files/2265659/xobject-1.pdf)
is  non-compliant (clause 6.2.2, test 2). Additionally, this message is logged on stderr:
> SEVERE: Font object is not a dictionary

I guess that veraPDF resets the font in the inherited graphics state of the Form XObject to null.

According to other PDF/A validators, the document is compliant.

**Comment by BezrukovM** [comment]
That message shall not be logged for that file. Fixed in https://github.com/veraPDF/veraPDF-parser/pull/367

**Comment by a20god** [comment]
Will the fix affect the (non-)conformance reported for that file or will it only remove the message?

**Comment by bdoubrov** [comment]
The fix so far only removes the message. I see that there is an empty Resources dictionary of the XObject that uses Tj opeators to reference the fonts from the page graphics state. To me this contradicts the PDF/A-2 requirement:

> A content stream that references other objects, such as images and fonts that are necessary to fully render or process the stream, shall have an explicitly associated Resources dictionary as described in
ISO 32000-1:2008, 7.8.3. 

But I'll double check this at the validation TWG.

**Comment by a20god** [comment]
The Form XObject does not load the font from its (or the page's) resources. The font has already been selected into the graphics state.

**Comment by a20god** [comment]
What about all the other graphics state parameters, such as the colour spaces? Certainly, those don't have to be copied into the Form XObject's Resource dictionary. Why should fonts be different? The Form XObject even doesn't "know" the names of all those resources.

**Comment by bdoubrov** [comment]
You might well be right. And I see indeed that veraPDF doesn't care about the color space in this file, but checks the font. This indeed looks inconsistent. But let me check a few things first.
