### ISSUE TITLE
Exception caught when validaing item [sic]

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#976]
veraPDF 1.12.1 throws (and catches) an exception when validating this document:
[a-2.pdf](https://github.com/veraPDF/veraPDF-library/files/2266266/a-2.pdf)
This message is sent to stderr:
> WARNING: Exception caught when validaing item

Note the typo (a "t" is missing in "validaing").

The exception is this:
> Caused by: java.lang.NullPointerException
> 	at java.util.HashMap.putMapEntries(HashMap.java:501)
> 	at java.util.HashMap.<init>(HashMap.java:490)
> 	at org.verapdf.gf.model.impl.external.GFEmbeddedFile.saveStaticContainersState(GFEmbeddedFile.java:139)

**Comment by a20god** [comment]
Please don't forget to fix the typo in the message...

**Comment by BezrukovM** [comment]
@a20god thanks. Missed that before. Fixed in new PR: https://github.com/veraPDF/veraPDF-library/pull/980
