### ISSUE TITLE
Embedded Type1 fonts not recognized as such in veraPdf 1.12.1

### ISSUE THREAD

**Issue by gumboSoftware** [veraPDF/veraPDF-library#977]
This identical to #742, but still present in veraPdf 1.12.1. A Type1 font is embedded but <rule specification="ISO 19005-2:2011" clause="6.2.11.4" testNumber="1" ...>, which doesn't apply, complains.

[QPGMR_QPDSPLIB_pfb.pdf](https://github.com/veraPDF/veraPDF-library/files/2279467/QPGMR_QPDSPLIB_pfb.pdf)

**Comment by bdoubrov** [comment]
The font in question is embedded as raw PFB file, including binary markers, which are not allowed in Type1 Adobe fonts. This is the reason why veraPDF considers this embedded font file as invalid. 

I note that Adobe Preflight reports the same issue.

**Comment by gumboSoftware** [comment]
We tested that as a possible explanation by using a raw conversion of pfb > pfa and got the same results. The type 0, 3 rule is triggered. See attached QPGMR_QPDSPLIB_pfa.pdf.

The font has an atypical comment section so we ran it through convertio (FontForge) to clean it up. This gets the file past Acrobat, but it still fails with font not embedded. See attached QPGMR_QPDSPLIB_convertio.pdf.
[QPGMR_QPDSPLIB_pfa.pdf](https://github.com/veraPDF/veraPDF-library/files/2284343/QPGMR_QPDSPLIB_pfa.pdf)
[QPGMR_QPDSPLIB_convertio.pdf](https://github.com/veraPDF/veraPDF-library/files/2284344/QPGMR_QPDSPLIB_convertio.pdf)

**Comment by bdoubrov** [comment]
These two new files indeed embed the font as PFA files. In particular, their encrypted portion is stored in ASCII hexadecimal format. However, PDF specification supports only the binary format of the encrypted part. And this is what causes veraPDF validation error. Again, Adobe Preflight reports the same issue on both new files.

See NOTE 2 after Table 127 in ISO 32000-1:
> A standard Type 1 font program, as described in the Adobe Type 1 Font Format specification, consists of three parts: a clear-text portion (written using PostScript syntax), an encrypted portion, and a fixed-content portion. The fixed-content portion contains 512 ASCII zeros followed by a cleartomark operator, and perhaps followed by additional data. Although the encrypted portion of a standard Type 1 font may be in binary or ASCII hexadecimal format, PDF supports only the binary format. However, the entire font program may be encoded using any filters.

**Comment by gumboSoftware** [comment]
Got it. We conflated the header fields with binary format. We apparently have plenty of company.

Thank you.

**Comment by PetruGit** [comment]
@gumboSoftware can you post the final version of the pdf, that works? If you still got it?
Or maybe you have another one that is valid. Thx
