### ISSUE TITLE
Inconsistent behavior for implicit vs. explicit DeviceGray colour space

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#978]
veraPDF 1.12.1 reports different results for these documents:
[invalid-cs-1.pdf](https://github.com/veraPDF/veraPDF-library/files/2306061/invalid-cs-1.pdf)
[invalid-cs-2.pdf](https://github.com/veraPDF/veraPDF-library/files/2306062/invalid-cs-2.pdf)
Both share the same problem: they use a CalRGB colour space for DefaultGray (and the Gamma entry is incorrect). The difference between the documents is that the second one uses a g operator in the content stream to select DeviceGray whereas the first one does not select a colour space in the content stream and therefore uses DeviceGray by default. veraPDF should report the same result for both documents.

**Comment by bdoubrov** [comment]
Indeed I confirm the issue with the remapping of initial DeviceGray color space to CalRGB. We'll fix it.

However, validation of the Gamma entry is a part of full ISO 32000-1 validation and is still out of scope of veraPDF. So, after the fix the file would be validated successfully by veraPDF.
