### ISSUE TITLE
Invalid PDF/A-1B with Charter-BT (Bitstream Charter) and Mathdesign

### ISSUE THREAD

**Issue by bdoubrov** [veraPDF/veraPDF-library#981]
## Dev Effort
1D

## Description
The issue has been reported here:

https://tex.stackexchange.com/questions/462972/invalid-pdf-a-1b-with-charter-bt-bitstream-charter-and-mathdesign

**Comment by jmvezic** [comment]
Can confirm this bug occurs when using Charter font in a PDF. It results in:

`The font programs for all fonts used within a conforming file shall be embedded within that file, as defined in PDF Reference 5.8, except when the fonts are used exclusively with text rendering mode 3` 

while Acrobat verification passes.

**Comment by bdoubrov** [comment]
yes, lookl like this is the duplicate of #969. veraPDF has issues parsing Charter fonts.
