### ISSUE TITLE
Fix CIDSet / CharSet validation for PDF/A-1

### ISSUE THREAD

**Issue by bdoubrov** [veraPDF/veraPDF-library#983]
## Dev Effort
3D

## Description
According to the latest discussions of the Validation TWG, in case of PDF/A-1 the CharSet / CIDSet entry shall list *all used glyphs* from the embedded font subset.

At the moment veraPDF just checks the presence of this entry for PDF/A-1 and does the full check of this entry (if present) for PDF/A-2 and PDF/A-3.

**Comment by carlwilson** [comment]
@bdoubrov could you please provide a status update please

**Comment by bdoubrov** [comment]
Fix released in v1.20
