### ISSUE TITLE
CLI: stderr is written to the stdout in mrr report

### ISSUE THREAD

**Issue by DmitryRemezow** [veraPDF/veraPDF-library#987]
stderr is written inside the stdout in mrr report. For example:

<jobsNov 28, 2017 1:53:00 PM org.verapdf.parser.PDFParser parseHeader
WARNING: Can't parse the header version.
java.lang.NumberFormatException: For input string: "a.4"
...>

Full report is attached - [1.txt](https://github.com/veraPDF/veraPDF-apps/files/1509686/1.txt)
File for testing - [1.pdf](https://github.com/veraPDF/veraPDF-apps/files/1509681/1.pdf)

**Comment by bdoubrov** [comment]
Duplicate of #926
