### ISSUE TITLE
Value of passedChecks in policyReport always 0

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-library#990]
it seems that the value of the *passedChecks*  attribute in the *policyReport* is always 0, even if this contradicts the information in the features report! 

For example, from the same call described [here](<https://github.com/veraPDF/veraPDF-apps/issues/196>), I end up with:

    <policyReport passedChecks="0" failedChecks="6" xmlns:vera="http://www.verapdf.org/MachineReadableReport">

But in this case the features report shows multiple occurrences of fonts that *are* embedded (and thus should have resulted in a passed check).

Version 1.4.7.

**Comment by carlwilson** [comment]
Closing this now as it's documentation of a little-used feature.
