### ISSUE TITLE
Switch --maxfailuresdisplayed  does not seem to affect policy output

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-library#991]
For a a policy-based assessment I use the following command:

    ~/verapdf/verapdf -x --maxfailuresdisplayed 1 --policyfile /home/johan/pdfPolicyVeraPDF/schemas/demo-policy.sch ~/pdfAcrobatEngineering/multimedia//MusicalScore.pdf > MusicalScore.xml

The schema  (*demo-policy.sch*, reproduced below) has a rule that checks if fonts are embedded. In order to suppress multiple instances of failure message on the same rule I set  `--maxfailuresdisplayed` to 1. Nevertheless my output looks like this, with 5 occurrences of the font-embedding rule: 

    <failedChecks>
    <check status="failed" test="not(embedded = 'false')" location="/report/jobs/job/featuresReport/documentResources/fonts/font[1]/fontDescriptor">
    <message>No fonts that are not embedded.</message>
    </check>
    <check status="failed" test="not(embedded = 'false')" location="/report/jobs/job/featuresReport/documentResources/fonts/font[2]/fontDescriptor">
    <message>No fonts that are not embedded.</message>
    </check>
    <check status="failed" test="not(embedded = 'false')" location="/report/jobs/job/featuresReport/documentResources/fonts/font[3]/fontDescriptor">
    <message>No fonts that are not embedded.</message>
    </check>
    <check status="failed" test="not(embedded = 'false')" location="/report/jobs/job/featuresReport/documentResources/fonts/font[8]/fontDescriptor">
    <message>No fonts that are not embedded.</message>
    </check>
    <check status="failed" test="not(embedded = 'false')" location="/report/jobs/job/featuresReport/documentResources/fonts/font[9]/fontDescriptor">
    <message>No fonts that are not embedded.</message>
    </check>
    <check status="failed" test="not(subType='Screen')" location="/report/jobs/job/featuresReport/annotations/annotation[1]">
    <message>No screen annotations.</message>
    </check>
    </failedChecks>

I would expect only 1 occurrence here (unless this option is designed to affect PDF/A validation only and not the policy checks).

Below my Schematron: 

    <?xml version="1.0"?>

    <sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt">
        <sch:pattern name="Disallow encryption.">
            <sch:rule context="/report/jobs/job/featuresReport/documentSecurity">
                <sch:assert test="not(encryptMetadata = 'true')">Encrypt in trailer dictionary is not allowed.</sch:assert>
            </sch:rule>
            <sch:rule context="/report/jobs/job/taskResult/exceptionMessage">
                <sch:assert test="not(contains(.,'encrypted'))">Encryption with open password is not allowed.</sch:assert>
            </sch:rule>
        </sch:pattern>
        <sch:pattern name="Fonts must be embedded.">
            <sch:rule context="/report/jobs/job/featuresReport/documentResources/fonts/font/fontDescriptor">
                <sch:assert test="not(embedded = 'false')">No fonts that are not embedded.</sch:assert>
            </sch:rule>
        </sch:pattern>
        <sch:pattern name="Multimedia not allowed.">
            <sch:rule context="/report/jobs/job/featuresReport/annotations/annotation">
                <sch:assert test="not(subType='Screen')">No screen annotations.</sch:assert>
            </sch:rule>
        </sch:pattern>
        <sch:pattern name="File attachments and embedded files not allowed.">
            <sch:rule context="/report/jobs/job/featuresReport/annotations/annotation">
                <sch:assert test="not(subType='FileAttachment')">No file attachments.</sch:assert>
            </sch:rule>
            <sch:rule context="/report/jobs/job/featuresReport/embeddedFiles">
                <sch:assert test="not('embeddedFile')">No embedded files.</sch:assert>
            </sch:rule>
        </sch:pattern>
        <sch:pattern name="Document must be parsable (poor man's proxy for canonical PDF validation).">
            <sch:rule context="/report/jobs/job/taskResult">
                <sch:assert test="not(@type='PARSE' and @isSuccess='false')">Document must be parsable.</sch:assert>
            </sch:rule>
        </sch:pattern>
    </sch:schema>

--maxfailuresdisplayed

**Comment by carlwilson** [comment]
@bdoubrov do we want to commit to adding a similar option to policy check reporting?

**Comment by bdoubrov** [comment]
We can check if any of the existing Schematron implementations support this option or can be easily patched.

**Comment by carlwilson** [comment]
I think that we could control the number of errors displayed, rather than the number detected. It's probably on me to investigate.

**Comment by carlwilson** [comment]
While this is possible it's not the intended function of the parameter as it stands. Closing as we're not looking to implement this.
