### ISSUE TITLE
Use the "features" report to check policy?

### ISSUE THREAD

**Issue by beyo-ra** [veraPDF/veraPDF-library#995]
## Dev Effort
2D

## Description
veraPDF
1. generates a "features" report of a PDF,
2. then it uses the report for any policy check.

Is it currently possible to check, and if not currently possible to possibly implement checking,
a policy against an existing feature report?

EXAMPLE
`$ verapdf --format xml -x ./documents/veraPDFPDFAConformanceCheckerGUI.pdf > ./veraPDFPDFAConformanceCheckerGUI.xml`

`$ verapdf --features-report ./veraPDFPDFAConformanceCheckerGUI.xml --policyfile ./disallowfontx.sch`

**Comment by carlwilson** [comment]
We're not going to implement this as it stands.
