### ISSUE TITLE
1.4.6 GUI # Some error in saving the HTML report: ...

### ISSUE THREAD

**Issue by beyo-ra** [veraPDF/veraPDF-library#997]
On Windows 7 Professional SP1

Running attached file
-- [Program  för Hands on seminariet 29 maj 2017.a1a.pdf](https://github.com/veraPDF/veraPDF-apps/files/1018984/Program.for.Hands.on.seminariet.29.maj.2017.a1a.pdf)
returns
-- "PDF file is complient with Validation Profile requirements"

however the following alert message appears

`Some error in saving the HTML report: javax.xml.transform.TransformException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Invalid byte 2 in UTF-8 sequence for 4 bytes.`

**Comment by beckymcg** [comment]
Duplicate #754
